use super::super::super::RuntimeRequest;
use super::super::json::{json_str_array, json_string, option_u64_json};
use super::json_items::{
    imported_kv_blocks_json, recursive_chunks_json, recursive_execution_waves_json,
    recursive_merge_rounds_json, runtime_adapter_observations_json, task_profile_str,
    tool_blueprints_json, transformer_layers_json,
};

pub fn runtime_request_json(request: &RuntimeRequest) -> String {
    let transformer_counts = request.transformer_plan.counts();
    let transformer_layers = transformer_layers_json(request);
    let recursive_chunks = recursive_chunks_json(request);
    let recursive_merge_rounds = recursive_merge_rounds_json(request);
    let recursive_execution_waves = recursive_execution_waves_json(request);
    let adapter_hints = request
        .hardware_plan
        .execution
        .adapter_hints
        .iter()
        .map(|adapter| adapter.as_str())
        .collect::<Vec<_>>();
    let runtime_adapter_observations =
        runtime_adapter_observations_json(&request.runtime_adapter_observations);
    let tool_blueprints = tool_blueprints_json(&request.toolsmith_plan.blueprints);
    let agent_team_messages = request.agent_team_plan.message_summaries(16);
    let agent_team_conflicts = request.agent_team_plan.conflict_summaries(8);
    let agent_team_evolution = request.agent_team_plan.evolution_summaries(8);
    let imported_kv_blocks = imported_kv_blocks_json(&request.imported_kv_blocks);

    format!(
        "{{\
         \"schema\":{},\
         \"prompt\":{},\
         \"profile\":{},\
         \"max_tokens\":{},\
         \"runtime\":{{\
         \"model_id\":{},\
         \"tokenizer\":{},\
         \"native_context_window\":{},\
         \"embedding_dimensions\":{},\
         \"supports_kv_import\":{},\
         \"supports_kv_export\":{},\
         \"max_kv_import_blocks\":{},\
         \"max_kv_export_blocks\":{},\
         \"hot_kv_precision_bits\":{},\
         \"cold_kv_precision_bits\":{}\
         }},\
         \"runtime_architecture\":{{\
         \"layer_count\":{},\
         \"hidden_size\":{},\
         \"attention_heads\":{},\
         \"kv_heads\":{},\
         \"local_window_tokens\":{}\
         }},\
         \"route\":{{\
         \"threshold\":{:.6},\
         \"attention_fraction\":{:.6},\
         \"attention_tokens\":{},\
         \"fast_tokens\":{}\
         }},\
         \"hierarchy\":{{\
         \"global\":{:.6},\
         \"local\":{:.6},\
         \"convolution\":{:.6}\
         }},\
         \"transformer\":{{\
         \"template\":{},\
         \"global_layers\":{},\
         \"local_layers\":{},\
         \"convolution_layers\":{},\
         \"layers\":[{}]\
         }},\
         \"recursive\":{{\
         \"required\":{},\
         \"prompt_tokens\":{},\
         \"native_window\":{},\
         \"chunk_tokens\":{},\
         \"overlap_tokens\":{},\
         \"merge_fan_in\":{},\
         \"max_parallel_chunks\":{},\
         \"chunks\":[{}],\
         \"merge_rounds\":[{}],\
         \"execution_waves\":[{}]\
         }},\
         \"hardware\":{{\
         \"device\":{},\
         \"tier\":{},\
         \"pressure\":{:.6},\
         \"runtime_device_contract\":{},\
         \"latency_budget_ms\":{},\
         \"local_kv_token_budget\":{},\
         \"global_kv_token_budget\":{},\
         \"execution\":{{\
         \"primary_lane\":{},\
         \"fallback_lane\":{},\
         \"memory_mode\":{},\
         \"adapter_hints\":{},\
         \"max_parallel_chunks\":{},\
         \"kv_prefetch_blocks\":{},\
         \"hot_kv_precision_bits\":{},\
         \"cold_kv_precision_bits\":{},\
         \"allow_disk_spill\":{}\
         }},\
         \"notes\":{}\
         }},\
         \"memory_hints\":{},\
         \"infini_memory_hints\":{},\
         \"experience_hints\":{},\
         \"imported_kv_blocks\":[{}],\
         \"toolsmith\":{{\
         \"rust_only\":{},\
         \"exploration_required\":{},\
         \"blueprint_count\":{},\
         \"ready\":{},\
         \"held\":{},\
         \"rejected\":{},\
         \"gate_passed\":{},\
         \"notes\":{},\
         \"rejected_requests\":{},\
         \"blueprints\":[{}]\
         }},\
         \"agent_team\":{{\
         \"enabled\":{},\
         \"summary\":{},\
         \"run_id\":{},\
         \"main_thread_goal\":{},\
         \"agents\":{},\
         \"messages\":{},\
         \"conflicts\":{},\
         \"unresolved_conflicts\":{},\
         \"evolution_signals\":{},\
         \"collision_free\":{},\
         \"isolation\":{{\
         \"single_writer\":{},\
         \"read_only_subagents\":{},\
         \"namespace\":{},\
         \"allowed_outputs\":{},\
         \"denied_capabilities\":{}\
         }},\
         \"message_summaries\":{},\
         \"conflict_summaries\":{},\
         \"evolution_summaries\":{}\
         }},\
         \"runtime_adapter_observations\":[{}]\
         }}",
        json_string("rust-norion-runtime-request-v1"),
        json_string(&request.prompt),
        json_string(task_profile_str(request.profile)),
        request.max_tokens,
        json_string(&request.runtime_metadata.model_id),
        json_string(&request.runtime_metadata.tokenizer),
        request.runtime_metadata.native_context_window,
        request.runtime_metadata.embedding_dimensions,
        request.runtime_metadata.supports_kv_import,
        request.runtime_metadata.supports_kv_export,
        request.runtime_metadata.max_kv_import_blocks,
        request.runtime_metadata.max_kv_export_blocks,
        request.runtime_metadata.hot_kv_precision_bits,
        request.runtime_metadata.cold_kv_precision_bits,
        request.runtime_architecture.layer_count,
        request.runtime_architecture.hidden_size,
        request.runtime_architecture.attention_heads,
        request.runtime_architecture.kv_heads,
        request.runtime_architecture.local_window_tokens,
        request.route_budget.threshold,
        request.route_budget.attention_fraction,
        request.route_budget.attention_tokens,
        request.route_budget.fast_tokens,
        request.hierarchy.global,
        request.hierarchy.local,
        request.hierarchy.convolution,
        json_string(request.transformer_plan.template_name()),
        transformer_counts.global,
        transformer_counts.local,
        transformer_counts.convolution,
        transformer_layers,
        request.recursive_schedule.requires_recursion,
        request.recursive_schedule.prompt_tokens,
        request.recursive_schedule.native_window_tokens,
        request.recursive_schedule.chunk_tokens,
        request.recursive_schedule.overlap_tokens,
        request.recursive_schedule.merge_fan_in,
        request.recursive_schedule.max_parallel_chunks,
        recursive_chunks,
        recursive_merge_rounds,
        recursive_execution_waves,
        json_string(request.hardware_plan.device.as_str()),
        json_string(request.hardware_plan.tier.as_str()),
        request.hardware_plan.pressure,
        json_string(&request.hardware_plan.runtime_contract_summary()),
        option_u64_json(request.hardware_plan.latency_budget_ms),
        request.hardware_plan.local_kv_token_budget,
        request.hardware_plan.global_kv_token_budget,
        json_string(request.hardware_plan.execution.primary_lane.as_str()),
        json_string(request.hardware_plan.execution.fallback_lane.as_str()),
        json_string(request.hardware_plan.execution.memory_mode.as_str()),
        json_str_array(adapter_hints),
        request.hardware_plan.execution.max_parallel_chunks,
        request.hardware_plan.execution.kv_prefetch_blocks,
        request.hardware_plan.execution.hot_kv_precision_bits,
        request.hardware_plan.execution.cold_kv_precision_bits,
        request.hardware_plan.execution.allow_disk_spill,
        json_str_array(request.hardware_plan.notes.iter().map(String::as_str)),
        json_str_array(request.memory_hints.iter().map(String::as_str)),
        json_str_array(request.infini_memory_hints.iter().map(String::as_str)),
        json_str_array(request.experience_hints.iter().map(String::as_str)),
        imported_kv_blocks,
        request.toolsmith_plan.rust_only,
        request.toolsmith_plan.exploration_required,
        request.toolsmith_plan.blueprint_count(),
        request.toolsmith_plan.ready_count(),
        request.toolsmith_plan.held_count(),
        request.toolsmith_plan.rejected_count(),
        request.toolsmith_plan.passed_rust_gate(),
        json_str_array(request.toolsmith_plan.notes.iter().map(String::as_str)),
        json_str_array(
            request
                .toolsmith_plan
                .rejected_requests
                .iter()
                .map(String::as_str)
        ),
        tool_blueprints,
        request.agent_team_plan.enabled,
        json_string(&request.agent_team_plan.summary()),
        json_string(&request.agent_team_plan.run_id),
        json_string(&request.agent_team_plan.main_thread_goal),
        request.agent_team_plan.active_agent_count(),
        request.agent_team_plan.message_count(),
        request.agent_team_plan.conflict_count(),
        request.agent_team_plan.unresolved_conflict_count(),
        request.agent_team_plan.evolution_signal_count(),
        request.agent_team_plan.collision_free(),
        request.agent_team_plan.isolation.single_writer,
        request.agent_team_plan.isolation.read_only_subagents,
        json_string(&request.agent_team_plan.isolation.namespace),
        json_str_array(
            request
                .agent_team_plan
                .isolation
                .allowed_outputs
                .iter()
                .map(String::as_str)
        ),
        json_str_array(
            request
                .agent_team_plan
                .isolation
                .denied_capabilities
                .iter()
                .map(String::as_str)
        ),
        json_str_array(agent_team_messages.iter().map(String::as_str)),
        json_str_array(agent_team_conflicts.iter().map(String::as_str)),
        json_str_array(agent_team_evolution.iter().map(String::as_str)),
        runtime_adapter_observations
    )
}
