use super::DeviceClass;
use crate::hardware::DeviceProfileDescriptor;

pub(super) fn descriptor_for(device: DeviceClass) -> DeviceProfileDescriptor {
    match device {
        DeviceClass::Auto => DeviceProfileDescriptor {
            device,
            tier: device.tier(),
            scope: "best-effort local probe with manual override",
            aliases: &["auto"],
        },
        DeviceClass::CpuOnly => DeviceProfileDescriptor {
            device,
            tier: device.tier(),
            scope: "portable CPU-only PCs / VMs / generic fallback targets",
            aliases: &[
                "cpu",
                "cpu-only",
                "pc-cpu",
                "desktop-cpu",
                "generic",
                "fallback",
                "unknown",
                "unknown-device",
                "x86",
                "x86_64",
                "amd64",
                "arm64",
                "aarch64",
                "loongarch64",
                "avx2",
                "avx512",
                "sse4",
                "neon",
                "portable",
            ],
        },
        DeviceClass::IntegratedGpu => DeviceProfileDescriptor {
            device,
            tier: device.tier(),
            scope: "laptops / mini PCs / handheld PCs / APU and iGPU machines",
            aliases: &[
                "integrated",
                "igpu",
                "integrated-gpu",
                "laptop",
                "notebook",
                "ultrabook",
                "mini-pc",
                "handheld-pc",
                "steamdeck",
                "handheld-console",
                "portable-console",
                "intel-iris",
                "intel-xe",
                "intel-uhd",
                "intel-hd",
                "amd-apu",
                "apu",
                "amd-radeon-graphics",
                "rdna-apu",
            ],
        },
        DeviceClass::DiscreteGpu => DeviceProfileDescriptor {
            device,
            tier: device.tier(),
            scope: "desktop GPUs / single accelerator workstations",
            aliases: &[
                "discrete",
                "dgpu",
                "discrete-gpu",
                "desktop-gpu",
                "gpu",
                "cuda",
                "rtx",
                "nvidia",
                "nvidia-gpu",
                "radeon",
                "amd-gpu",
                "arc",
                "intel-arc",
                "vulkan-gpu",
                "opencl",
                "directml",
                "dml",
                "egpu",
            ],
        },
        DeviceClass::UnifiedMemory => DeviceProfileDescriptor {
            device,
            tier: device.tier(),
            scope: "unified-memory machines such as Apple Silicon and UMA APUs",
            aliases: &[
                "uma",
                "unified",
                "unified-memory",
                "apple",
                "mac",
                "macbook",
                "apple-silicon",
                "m-series",
                "m1",
                "m2",
                "m3",
                "m4",
                "m5",
            ],
        },
        DeviceClass::Mobile => DeviceProfileDescriptor {
            device,
            tier: device.tier(),
            scope: "phones / tablets / wearables / XR devices / mobile OS targets",
            aliases: &[
                "mobile",
                "phone",
                "tablet",
                "android",
                "ios",
                "handheld",
                "iphone",
                "ipad",
                "harmonyos",
                "ohos",
                "visionos",
                "smartphone",
                "wearable",
                "wear-os",
                "wearos",
                "watch",
                "xr",
                "vr",
                "ar",
                "quest",
                "mobile-vr",
                "smart-tv",
                "tvos",
                "android-tv",
            ],
        },
        DeviceClass::Embedded => DeviceProfileDescriptor {
            device,
            tier: device.tier(),
            scope: "embedded boards / SBCs / IoT Linux and RTOS-capable local targets",
            aliases: &[
                "embedded",
                "iot",
                "rpi",
                "raspberry-pi",
                "raspberry_pi",
                "sbc",
                "arm-sbc",
                "linux-sbc",
                "single-board",
                "single-board-computer",
                "riscv",
                "riscv64",
                "risc-v",
                "armv7",
                "armv8",
                "embedded-linux",
                "yocto",
            ],
        },
        DeviceClass::BrowserWasm => DeviceProfileDescriptor {
            device,
            tier: device.tier(),
            scope: "browser / WASM / WASI sandbox targets with optional WebGPU",
            aliases: &[
                "browser-wasm",
                "browser_wasm",
                "wasm",
                "wasm32",
                "wasm32-wasip1",
                "wasm32-unknown-unknown",
                "wasi",
                "wasip1",
                "browser",
                "web",
                "web-runtime",
                "webworker",
                "service-worker",
                "webgpu",
            ],
        },
        DeviceClass::Microcontroller => DeviceProfileDescriptor {
            device,
            tier: device.tier(),
            scope: "microcontroller / no-std / tiny local control targets",
            aliases: &[
                "microcontroller",
                "micro",
                "mcu",
                "tiny",
                "tiny-device",
                "no-std",
                "cortex-m",
                "thumbv7",
                "thumbv8",
                "xtensa",
                "esp32",
                "esp-idf",
                "stm32",
                "arduino",
                "rp2040",
                "riscv32",
            ],
        },
        DeviceClass::NpuAccelerator => DeviceProfileDescriptor {
            device,
            tier: device.tier(),
            scope: "NPU / neural engine / AI accelerator targets",
            aliases: &[
                "npu",
                "ane",
                "tpu",
                "ai-accelerator",
                "npu-accelerator",
                "neural",
                "neural-engine",
                "snapdragon",
                "qualcomm",
                "hexagon",
                "qnn-htp",
                "apple-neural-engine",
                "ascend",
                "cann",
                "cambricon",
                "mlu",
                "kunlun",
                "sophgo",
                "bm1684",
                "rockchip-npu",
                "rknn",
                "horizon-bpu",
                "hailo",
                "ethos",
                "directml-npu",
                "vitis-ai",
                "npu-smi",
                "mediatek-apu",
            ],
        },
        DeviceClass::MultiGpu => DeviceProfileDescriptor {
            device,
            tier: device.tier(),
            scope: "heterogeneous multi-accelerator / distributed local boxes",
            aliases: &[
                "multi-gpu",
                "multi_gpu",
                "multi",
                "multi-accelerator",
                "multi-accel",
                "multi-npu",
                "multi-device",
                "heterogeneous",
                "distributed",
                "cluster",
                "nvlink",
                "tensor-parallel",
                "pipeline-parallel",
                "mpi",
                "slurm-cluster",
            ],
        },
        DeviceClass::Edge => DeviceProfileDescriptor {
            device,
            tier: device.tier(),
            scope: "edge gateways / Jetson-class devices / NAS / industrial PCs",
            aliases: &[
                "edge",
                "gateway",
                "edge-gateway",
                "jetson",
                "nas",
                "home-server",
                "router",
                "industrial-pc",
                "ipc",
                "robot",
                "robotics",
                "drone",
                "vehicle",
                "automotive",
                "car",
                "camera",
                "nvr",
                "edge-box",
                "smart-camera",
            ],
        },
        DeviceClass::Server => DeviceProfileDescriptor {
            device,
            tier: device.tier(),
            scope: "servers / racks / datacenter nodes / HPC / local cloud hosts",
            aliases: &[
                "server",
                "workstation",
                "rack",
                "datacenter",
                "local-cloud",
                "hpc",
                "hpc-node",
                "k8s",
                "kubernetes",
                "bare-metal",
                "cloud-host",
                "epyc",
                "xeon",
                "threadripper",
                "rackmount",
                "slurm",
                "pbs",
            ],
        },
    }
}
