use super::*;
use std::path::Path;

#[test]
fn parses_self_goal_queue_flags() {
    let args = Args::parse(vec![
        "--self-goal-queue-store".to_owned(),
        "target/self-goal-queue.ndkv".to_owned(),
        "--self-goal-queue-store-apply".to_owned(),
        "--self-goal-queue-evidence".to_owned(),
        "candidate_index=0;kind=cargo_check;passed=true".to_owned(),
        "--self-goal-queue-evidence-file".to_owned(),
        "target/self-goal-evidence.txt".to_owned(),
        "--self-goal-queue-local-evidence".to_owned(),
        "--self-goal-queue-local-evidence-dry-run".to_owned(),
        "--self-goal-queue-tenant".to_owned(),
        "tenant-a".to_owned(),
        "--self-goal-queue-workspace".to_owned(),
        "workspace-b".to_owned(),
        "--self-goal-queue-session".to_owned(),
        "session-c".to_owned(),
        "--self-goal-queue-key".to_owned(),
        "queue-key".to_owned(),
        "--self-goal-queue-operator".to_owned(),
        "operator-1".to_owned(),
        "--self-goal-queue-ticket".to_owned(),
        "ticket-2".to_owned(),
    ]);

    assert!(args.self_goal_queue);
    assert_eq!(
        args.self_goal_queue_store_path.as_deref(),
        Some(Path::new("target/self-goal-queue.ndkv"))
    );
    assert!(args.self_goal_queue_store_apply);
    assert_eq!(
        args.self_goal_queue_evidence_packets,
        vec!["candidate_index=0;kind=cargo_check;passed=true".to_owned()]
    );
    assert_eq!(
        args.self_goal_queue_evidence_path.as_deref(),
        Some(Path::new("target/self-goal-evidence.txt"))
    );
    assert!(args.self_goal_queue_local_evidence);
    assert!(args.self_goal_queue_local_evidence_dry_run);
    assert_eq!(args.self_goal_queue_tenant, "tenant-a");
    assert_eq!(args.self_goal_queue_workspace, "workspace-b");
    assert_eq!(args.self_goal_queue_session, "session-c");
    assert_eq!(args.self_goal_queue_key, "queue-key");
    assert_eq!(args.self_goal_queue_operator, "operator-1");
    assert_eq!(args.self_goal_queue_ticket, "ticket-2");
}

#[test]
fn parses_reasoning_genome_benchmark_gate_flags() {
    let args = Args::parse(vec![
        "--benchmark-min-reasoning-genome-expression-cases".to_owned(),
        "2".to_owned(),
        "--benchmark-min-reasoning-genome-expression-device-profiles".to_owned(),
        "3".to_owned(),
        "--benchmark-min-reasoning-genome-splice-cases".to_owned(),
        "4".to_owned(),
        "--benchmark-min-reasoning-genome-splice-device-profiles".to_owned(),
        "5".to_owned(),
        "--benchmark-min-gene-scissors-proposal-cases".to_owned(),
        "6".to_owned(),
        "--benchmark-min-gene-scissors-proposal-device-profiles".to_owned(),
        "7".to_owned(),
        "--benchmark-min-reasoning-genome-repair-payloads".to_owned(),
        "8".to_owned(),
        "--benchmark-min-reasoning-genome-regeneration-payloads".to_owned(),
        "9".to_owned(),
    ]);

    assert!(args.benchmark_gate_enabled);
    assert!(args.benchmark_all_devices);
    assert_eq!(
        args.benchmark_min_reasoning_genome_expression_cases,
        Some(2)
    );
    assert_eq!(
        args.benchmark_min_reasoning_genome_expression_device_profiles,
        Some(3)
    );
    assert_eq!(args.benchmark_min_reasoning_genome_splice_cases, Some(4));
    assert_eq!(
        args.benchmark_min_reasoning_genome_splice_device_profiles,
        Some(5)
    );
    assert_eq!(args.benchmark_min_gene_scissors_proposal_cases, Some(6));
    assert_eq!(
        args.benchmark_min_gene_scissors_proposal_device_profiles,
        Some(7)
    );
    assert_eq!(args.benchmark_min_reasoning_genome_repair_payloads, Some(8));
    assert_eq!(
        args.benchmark_min_reasoning_genome_regeneration_payloads,
        Some(9)
    );
    let gate = args.benchmark_gate();
    assert_eq!(gate.min_reasoning_genome_expression_cases, Some(2));
    assert_eq!(
        gate.min_reasoning_genome_expression_device_profiles,
        Some(3)
    );
    assert_eq!(gate.min_reasoning_genome_splice_cases, Some(4));
    assert_eq!(gate.min_reasoning_genome_splice_device_profiles, Some(5));
    assert_eq!(gate.min_gene_scissors_proposal_cases, Some(6));
    assert_eq!(gate.min_gene_scissors_proposal_device_profiles, Some(7));
    assert_eq!(gate.min_reasoning_genome_repair_payloads, Some(8));
    assert_eq!(gate.min_reasoning_genome_regeneration_payloads, Some(9));
}

#[test]
fn parses_recursive_scheduler_flags() {
    let args = Args::parse(vec![
        "--profile".to_owned(),
        "long".to_owned(),
        "--native-window".to_owned(),
        "8".to_owned(),
        "--chunk-tokens".to_owned(),
        "6".to_owned(),
        "--chunk-overlap".to_owned(),
        "2".to_owned(),
        "--merge-fan-in".to_owned(),
        "2".to_owned(),
        "--replay".to_owned(),
        "3".to_owned(),
        "--auto-replay".to_owned(),
        "4".to_owned(),
        "--retention-stale-after".to_owned(),
        "12".to_owned(),
        "--retention-decay-rate".to_owned(),
        "0.25".to_owned(),
        "--retention-remove-below".to_owned(),
        "0.08".to_owned(),
        "--retention-remove-after-failures".to_owned(),
        "7".to_owned(),
        "--compaction-threshold".to_owned(),
        "0.88".to_owned(),
        "--compaction-max-candidates".to_owned(),
        "64".to_owned(),
        "--compaction-max-merges".to_owned(),
        "5".to_owned(),
        "--trace".to_owned(),
        "trace.jsonl".to_owned(),
        "--trace-schema-gate".to_owned(),
        "trace-schema.jsonl".to_owned(),
        "--benchmark".to_owned(),
        "benchmark.jsonl".to_owned(),
        "--benchmark-all-devices".to_owned(),
        "--benchmark-min-quality".to_owned(),
        "0.6".to_owned(),
        "--benchmark-min-reward".to_owned(),
        "0.5".to_owned(),
        "--benchmark-max-total-ms".to_owned(),
        "10000".to_owned(),
        "--benchmark-max-recursive-chunks".to_owned(),
        "8".to_owned(),
        "--benchmark-min-recursive-cases".to_owned(),
        "1".to_owned(),
        "--benchmark-min-recursive-runtime-calls".to_owned(),
        "4".to_owned(),
        "--benchmark-min-auto-replay-router-updates".to_owned(),
        "1".to_owned(),
        "--benchmark-min-auto-replay-hierarchy-updates".to_owned(),
        "1".to_owned(),
        "--benchmark-min-auto-replay-router-threshold-mutations".to_owned(),
        "1".to_owned(),
        "--benchmark-min-auto-replay-hierarchy-weight-mutations".to_owned(),
        "1".to_owned(),
        "--benchmark-min-auto-replay-router-threshold-delta".to_owned(),
        "0.01".to_owned(),
        "--benchmark-min-auto-replay-hierarchy-weight-delta".to_owned(),
        "0.01".to_owned(),
        "--benchmark-min-auto-replay-memory-updates".to_owned(),
        "1".to_owned(),
        "--benchmark-min-live-memory-feedback-updates".to_owned(),
        "2".to_owned(),
        "--benchmark-min-auto-replay-live-memory-feedback-updates".to_owned(),
        "3".to_owned(),
        "--benchmark-min-auto-replay-live-memory-feedback-detail-items".to_owned(),
        "2".to_owned(),
        "--benchmark-min-auto-replay-live-memory-feedback-applied".to_owned(),
        "4".to_owned(),
        "--benchmark-min-auto-replay-live-memory-feedback-strength-delta".to_owned(),
        "0.15".to_owned(),
        "--benchmark-min-auto-replay-recursive-items".to_owned(),
        "1".to_owned(),
        "--benchmark-min-auto-replay-recursive-call-pressure".to_owned(),
        "0.05".to_owned(),
        "--benchmark-max-auto-replay-recursive-call-pressure".to_owned(),
        "0.25".to_owned(),
        "--benchmark-min-evolution-live-inference-runs".to_owned(),
        "8".to_owned(),
        "--benchmark-min-evolution-live-router-threshold-mutations".to_owned(),
        "2".to_owned(),
        "--benchmark-min-evolution-live-hierarchy-weight-mutations".to_owned(),
        "1".to_owned(),
        "--benchmark-min-evolution-live-router-threshold-delta".to_owned(),
        "0.04".to_owned(),
        "--benchmark-min-evolution-live-hierarchy-weight-delta".to_owned(),
        "0.03".to_owned(),
        "--benchmark-min-evolution-live-online-reward-feedbacks".to_owned(),
        "3".to_owned(),
        "--benchmark-min-evolution-live-online-reward-reinforcements".to_owned(),
        "2".to_owned(),
        "--benchmark-min-evolution-live-online-reward-penalties".to_owned(),
        "1".to_owned(),
        "--benchmark-min-evolution-live-online-reward-strength".to_owned(),
        "1.4".to_owned(),
        "--benchmark-min-evolution-live-online-reward-reinforcement-strength".to_owned(),
        "0.8".to_owned(),
        "--benchmark-min-evolution-live-online-reward-penalty-strength".to_owned(),
        "0.6".to_owned(),
        "--benchmark-min-evolution-live-memory-updates".to_owned(),
        "5".to_owned(),
        "--benchmark-min-evolution-live-stored-memory-updates".to_owned(),
        "4".to_owned(),
        "--benchmark-min-evolution-live-reflection-issues".to_owned(),
        "3".to_owned(),
        "--benchmark-min-evolution-live-critical-reflection-issues".to_owned(),
        "1".to_owned(),
        "--benchmark-min-evolution-live-revision-actions".to_owned(),
        "2".to_owned(),
        "--benchmark-min-evolution-live-inference-device-profiles".to_owned(),
        "12".to_owned(),
        "--benchmark-min-evolution-live-router-threshold-mutation-device-profiles".to_owned(),
        "12".to_owned(),
        "--benchmark-min-evolution-live-hierarchy-weight-mutation-device-profiles".to_owned(),
        "12".to_owned(),
        "--benchmark-min-evolution-live-online-reward-device-profiles".to_owned(),
        "12".to_owned(),
        "--benchmark-min-evolution-live-online-reward-strength-device-profiles".to_owned(),
        "11".to_owned(),
        "--benchmark-min-evolution-live-memory-update-device-profiles".to_owned(),
        "12".to_owned(),
        "--benchmark-min-evolution-live-stored-memory-update-device-profiles".to_owned(),
        "12".to_owned(),
        "--benchmark-min-evolution-live-reflection-issue-device-profiles".to_owned(),
        "12".to_owned(),
        "--benchmark-min-evolution-live-critical-reflection-issue-device-profiles".to_owned(),
        "6".to_owned(),
        "--benchmark-min-evolution-live-revision-action-device-profiles".to_owned(),
        "12".to_owned(),
        "--benchmark-min-evolution-replay-runs".to_owned(),
        "1".to_owned(),
        "--benchmark-min-evolution-replay-items".to_owned(),
        "2".to_owned(),
        "--benchmark-min-evolution-router-threshold-mutations".to_owned(),
        "3".to_owned(),
        "--benchmark-min-evolution-hierarchy-weight-mutations".to_owned(),
        "4".to_owned(),
        "--benchmark-min-evolution-router-threshold-delta".to_owned(),
        "0.02".to_owned(),
        "--benchmark-min-evolution-hierarchy-weight-delta".to_owned(),
        "0.03".to_owned(),
        "--benchmark-min-evolution-memory-updates".to_owned(),
        "5".to_owned(),
        "--benchmark-min-evolution-replay-live-memory-feedback-updates".to_owned(),
        "6".to_owned(),
        "--benchmark-min-evolution-replay-live-memory-feedback-detail-items".to_owned(),
        "7".to_owned(),
        "--benchmark-min-evolution-replay-live-memory-feedback-applied".to_owned(),
        "8".to_owned(),
        "--benchmark-min-evolution-replay-live-memory-feedback-strength-delta".to_owned(),
        "0.09".to_owned(),
        "--benchmark-min-evolution-replay-rust-check-items".to_owned(),
        "1".to_owned(),
        "--benchmark-min-evolution-replay-rust-check-passed".to_owned(),
        "1".to_owned(),
        "--benchmark-max-evolution-replay-rust-check-failed".to_owned(),
        "0".to_owned(),
        "--benchmark-min-evolution-replay-rust-check-live-memory-feedback-updates".to_owned(),
        "2".to_owned(),
        "--benchmark-min-evolution-replay-rust-check-live-memory-feedback-applied".to_owned(),
        "2".to_owned(),
        "--benchmark-min-evolution-replay-rust-check-live-memory-feedback-strength-delta"
            .to_owned(),
        "0.36".to_owned(),
        "--benchmark-min-evolution-replay-live-evolution-items".to_owned(),
        "9".to_owned(),
        "--benchmark-min-evolution-replay-live-evolution-online-reward-feedbacks".to_owned(),
        "4".to_owned(),
        "--benchmark-min-evolution-replay-live-evolution-online-reward-reinforcements".to_owned(),
        "3".to_owned(),
        "--benchmark-min-evolution-replay-live-evolution-online-reward-penalties".to_owned(),
        "1".to_owned(),
        "--benchmark-min-evolution-replay-live-evolution-online-reward-strength".to_owned(),
        "1.1".to_owned(),
        "--benchmark-min-evolution-replay-live-evolution-online-reward-reinforcement-strength"
            .to_owned(),
        "0.7".to_owned(),
        "--benchmark-min-evolution-replay-live-evolution-online-reward-penalty-strength".to_owned(),
        "0.4".to_owned(),
        "--benchmark-min-evolution-replay-live-evolution-memory-updates".to_owned(),
        "10".to_owned(),
        "--benchmark-min-evolution-replay-live-evolution-stored-memory-updates".to_owned(),
        "11".to_owned(),
        "--benchmark-min-evolution-replay-live-evolution-reflection-issues".to_owned(),
        "12".to_owned(),
        "--benchmark-min-evolution-replay-live-evolution-critical-reflection-issues".to_owned(),
        "13".to_owned(),
        "--benchmark-min-evolution-replay-live-evolution-revision-actions".to_owned(),
        "14".to_owned(),
        "--benchmark-min-evolution-replay-live-evolution-device-profiles".to_owned(),
        "12".to_owned(),
        "--benchmark-min-evolution-replay-live-evolution-online-reward-device-profiles".to_owned(),
        "12".to_owned(),
        "--benchmark-min-evolution-replay-live-evolution-online-reward-strength-device-profiles"
            .to_owned(),
        "11".to_owned(),
        "--benchmark-min-evolution-replay-live-evolution-memory-update-device-profiles".to_owned(),
        "12".to_owned(),
        "--benchmark-min-evolution-replay-live-evolution-critical-reflection-issue-device-profiles"
            .to_owned(),
        "6".to_owned(),
        "--benchmark-min-evolution-replay-live-evolution-revision-action-device-profiles"
            .to_owned(),
        "12".to_owned(),
        "--benchmark-min-evolution-recursive-replay-items".to_owned(),
        "6".to_owned(),
        "--benchmark-min-evolution-recursive-runtime-calls".to_owned(),
        "7".to_owned(),
        "--benchmark-max-evolution-drift-rollbacks".to_owned(),
        "0".to_owned(),
        "--benchmark-max-evolution-rollback-router-threshold-delta".to_owned(),
        "0.0".to_owned(),
        "--benchmark-max-evolution-rollback-hierarchy-weight-delta".to_owned(),
        "0.0".to_owned(),
        "--benchmark-min-sparse-skipped-cases".to_owned(),
        "1".to_owned(),
        "--benchmark-min-sparse-skipped-tokens".to_owned(),
        "3".to_owned(),
        "--benchmark-min-runtime-forward-cases".to_owned(),
        "4".to_owned(),
        "--benchmark-min-runtime-forward-energy-cases".to_owned(),
        "4".to_owned(),
        "--benchmark-min-runtime-kv-influence-cases".to_owned(),
        "4".to_owned(),
        "--benchmark-min-runtime-architecture-cases".to_owned(),
        "4".to_owned(),
        "--benchmark-min-runtime-architecture-device-profiles".to_owned(),
        "12".to_owned(),
        "--benchmark-min-runtime-kv-precision-cases".to_owned(),
        "4".to_owned(),
        "--benchmark-min-runtime-kv-precision-device-profiles".to_owned(),
        "12".to_owned(),
        "--benchmark-min-runtime-uncertainty-cases".to_owned(),
        "4".to_owned(),
        "--benchmark-min-runtime-uncertainty-tokens".to_owned(),
        "4".to_owned(),
        "--benchmark-min-runtime-uncertainty-device-profiles".to_owned(),
        "12".to_owned(),
        "--benchmark-min-runtime-uncertainty-token-device-profiles".to_owned(),
        "12".to_owned(),
        "--benchmark-min-runtime-kv-import-cases".to_owned(),
        "4".to_owned(),
        "--benchmark-min-runtime-kv-imported".to_owned(),
        "4".to_owned(),
        "--benchmark-min-runtime-kv-import-device-profiles".to_owned(),
        "6".to_owned(),
        "--benchmark-min-runtime-kv-exported".to_owned(),
        "4".to_owned(),
        "--benchmark-min-runtime-kv-export-device-profiles".to_owned(),
        "6".to_owned(),
        "--benchmark-min-runtime-kv-stored".to_owned(),
        "2".to_owned(),
        "--benchmark-min-runtime-kv-stored-device-profiles".to_owned(),
        "6".to_owned(),
        "--benchmark-min-runtime-kv-hold-cases".to_owned(),
        "1".to_owned(),
        "--benchmark-min-runtime-kv-held".to_owned(),
        "2".to_owned(),
        "--benchmark-min-runtime-kv-hold-device-profiles".to_owned(),
        "6".to_owned(),
        "--benchmark-min-runtime-adapter-contract-cases".to_owned(),
        "4".to_owned(),
        "--benchmark-min-runtime-adapter-kinds".to_owned(),
        "3".to_owned(),
        "--benchmark-min-runtime-adapter-observations".to_owned(),
        "2".to_owned(),
        "--benchmark-min-runtime-adapter-best-score".to_owned(),
        "0.25".to_owned(),
        "--benchmark-max-runtime-adapter-contract-violations".to_owned(),
        "0".to_owned(),
        "--benchmark-max-runtime-adapter-selection-mismatches".to_owned(),
        "0".to_owned(),
        "--benchmark-min-runtime-embedding-cases".to_owned(),
        "4".to_owned(),
        "--benchmark-min-runtime-embedding-device-profiles".to_owned(),
        "12".to_owned(),
        "--benchmark-max-embedding-fallback-cases".to_owned(),
        "0".to_owned(),
        "--benchmark-max-embedding-evidence-failures".to_owned(),
        "0".to_owned(),
        "--benchmark-min-runtime-device-execution-cases".to_owned(),
        "4".to_owned(),
        "--benchmark-min-runtime-device-execution-device-profiles".to_owned(),
        "12".to_owned(),
        "--benchmark-max-runtime-device-execution-violations".to_owned(),
        "0".to_owned(),
        "--benchmark-max-memory-governance-failures".to_owned(),
        "0".to_owned(),
        "--benchmark-min-memory-governance-cases".to_owned(),
        "4".to_owned(),
        "--benchmark-min-memory-governance-device-profiles".to_owned(),
        "12".to_owned(),
        "--benchmark-min-memory-retention-activity-cases".to_owned(),
        "1".to_owned(),
        "--benchmark-min-memory-compaction-activity-cases".to_owned(),
        "1".to_owned(),
        "--benchmark-min-reflection-issue-cases".to_owned(),
        "2".to_owned(),
        "--benchmark-min-reflection-issues".to_owned(),
        "3".to_owned(),
        "--benchmark-min-critical-reflection-issue-cases".to_owned(),
        "1".to_owned(),
        "--benchmark-min-critical-reflection-issues".to_owned(),
        "1".to_owned(),
        "--benchmark-min-revision-action-cases".to_owned(),
        "2".to_owned(),
        "--benchmark-min-revision-actions".to_owned(),
        "4".to_owned(),
        "--benchmark-min-reflection-issue-device-profiles".to_owned(),
        "12".to_owned(),
        "--benchmark-min-critical-reflection-issue-device-profiles".to_owned(),
        "6".to_owned(),
        "--benchmark-min-revision-action-device-profiles".to_owned(),
        "12".to_owned(),
        "--benchmark-min-device-profiles".to_owned(),
        "12".to_owned(),
        "--benchmark-min-recursive-device-profiles".to_owned(),
        "12".to_owned(),
        "--benchmark-max-drift-blocks".to_owned(),
        "0".to_owned(),
        "--benchmark-max-drift-rollbacks".to_owned(),
        "0".to_owned(),
        "--benchmark-roundtrip".to_owned(),
        "--list-devices".to_owned(),
        "--probe-device".to_owned(),
        "--device-gate".to_owned(),
        "--kv-quant-max-total-us".to_owned(),
        "100000".to_owned(),
        "--runtime-manifest-gate".to_owned(),
        "--runtime-manifest-all-devices-gate".to_owned(),
        "--runtime-weights".to_owned(),
        "weights.noiron".to_owned(),
        "--runtime-tokenizer-path".to_owned(),
        "tokenizer.noiron".to_owned(),
        "--runtime-config".to_owned(),
        "config.noiron".to_owned(),
        "--runtime-layers".to_owned(),
        "18".to_owned(),
        "--runtime-hidden-size".to_owned(),
        "128".to_owned(),
        "--runtime-attention-heads".to_owned(),
        "8".to_owned(),
        "--runtime-kv-heads".to_owned(),
        "4".to_owned(),
        "--runtime-local-window".to_owned(),
        "2048".to_owned(),
        "--inspect-state".to_owned(),
        "--inspect-limit".to_owned(),
        "2".to_owned(),
        "--inspect-gate".to_owned(),
        "--inspect-min-memories".to_owned(),
        "3".to_owned(),
        "--inspect-min-runtime-kv-memories".to_owned(),
        "1".to_owned(),
        "--inspect-min-experiences".to_owned(),
        "2".to_owned(),
        "--inspect-min-runtime-model-experiences".to_owned(),
        "2".to_owned(),
        "--inspect-min-runtime-adapter-experiences".to_owned(),
        "2".to_owned(),
        "--inspect-max-runtime-adapter-selection-mismatches".to_owned(),
        "0".to_owned(),
        "--inspect-min-runtime-forward-energy-experiences".to_owned(),
        "2".to_owned(),
        "--inspect-min-runtime-kv-influence-experiences".to_owned(),
        "2".to_owned(),
        "--inspect-min-runtime-tokens".to_owned(),
        "5".to_owned(),
        "--inspect-min-runtime-uncertainty-experiences".to_owned(),
        "2".to_owned(),
        "--inspect-min-runtime-uncertainty-tokens".to_owned(),
        "8".to_owned(),
        "--inspect-min-runtime-architecture-experiences".to_owned(),
        "2".to_owned(),
        "--inspect-min-runtime-kv-precision-experiences".to_owned(),
        "2".to_owned(),
        "--inspect-max-runtime-kv-precision-mismatches".to_owned(),
        "0".to_owned(),
        "--inspect-max-runtime-errors".to_owned(),
        "0".to_owned(),
        "--inspect-max-runtime-timeouts".to_owned(),
        "0".to_owned(),
        "--inspect-min-runtime-device-execution-experiences".to_owned(),
        "2".to_owned(),
        "--inspect-min-runtime-layer-mode-experiences".to_owned(),
        "2".to_owned(),
        "--inspect-min-runtime-all-layer-mode-experiences".to_owned(),
        "2".to_owned(),
        "--inspect-min-runtime-global-layers".to_owned(),
        "4".to_owned(),
        "--inspect-min-runtime-local-window-layers".to_owned(),
        "6".to_owned(),
        "--inspect-min-runtime-convolutional-fusion-layers".to_owned(),
        "2".to_owned(),
        "--inspect-min-runtime-kv-import-experiences".to_owned(),
        "2".to_owned(),
        "--inspect-min-runtime-kv-export-experiences".to_owned(),
        "2".to_owned(),
        "--inspect-min-runtime-kv-hold-experiences".to_owned(),
        "1".to_owned(),
        "--inspect-min-runtime-kv-held-blocks".to_owned(),
        "2".to_owned(),
        "--inspect-min-runtime-kv-memory-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-runtime-model-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-runtime-adapter-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-runtime-forward-energy-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-runtime-kv-influence-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-runtime-uncertainty-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-runtime-uncertainty-token-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-runtime-kv-precision-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-runtime-device-execution-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-runtime-layer-mode-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-runtime-all-layer-mode-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-runtime-kv-import-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-runtime-kv-export-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-runtime-kv-hold-device-profiles".to_owned(),
        "6".to_owned(),
        "--inspect-min-reflection-issue-experiences".to_owned(),
        "3".to_owned(),
        "--inspect-min-critical-reflection-issue-experiences".to_owned(),
        "1".to_owned(),
        "--inspect-min-revision-action-experiences".to_owned(),
        "2".to_owned(),
        "--inspect-min-live-memory-feedback-experiences".to_owned(),
        "2".to_owned(),
        "--inspect-min-live-memory-feedback-updates".to_owned(),
        "5".to_owned(),
        "--inspect-min-live-memory-feedback-detail-experiences".to_owned(),
        "2".to_owned(),
        "--inspect-min-live-memory-feedback-applied".to_owned(),
        "4".to_owned(),
        "--inspect-min-live-memory-feedback-strength-delta".to_owned(),
        "0.51".to_owned(),
        "--inspect-min-reflection-issue-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-critical-reflection-issue-device-profiles".to_owned(),
        "6".to_owned(),
        "--inspect-min-revision-action-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-live-memory-feedback-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-evolution-live-inference-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-evolution-live-router-threshold-mutation-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-evolution-live-hierarchy-weight-mutation-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-evolution-live-online-reward-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-evolution-live-online-reward-strength-device-profiles".to_owned(),
        "11".to_owned(),
        "--inspect-min-evolution-live-memory-update-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-evolution-live-stored-memory-update-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-evolution-live-reflection-issue-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-evolution-live-critical-reflection-issue-device-profiles".to_owned(),
        "6".to_owned(),
        "--inspect-min-evolution-live-revision-action-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-evolution-replay-run-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-evolution-replay-item-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-evolution-router-threshold-mutation-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-evolution-hierarchy-weight-mutation-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-evolution-memory-update-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-evolution-replay-live-memory-feedback-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-evolution-replay-live-memory-feedback-detail-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-evolution-replay-live-evolution-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-evolution-replay-live-evolution-online-reward-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-evolution-replay-live-evolution-online-reward-strength-device-profiles"
            .to_owned(),
        "11".to_owned(),
        "--inspect-min-evolution-replay-live-evolution-memory-update-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-evolution-replay-live-evolution-critical-reflection-issue-device-profiles"
            .to_owned(),
        "6".to_owned(),
        "--inspect-min-evolution-replay-live-evolution-revision-action-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-evolution-recursive-replay-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-evolution-recursive-runtime-call-device-profiles".to_owned(),
        "12".to_owned(),
        "--inspect-min-router-observations".to_owned(),
        "4".to_owned(),
        "--inspect-min-evolution-live-inference-runs".to_owned(),
        "4".to_owned(),
        "--inspect-min-evolution-live-router-threshold-mutations".to_owned(),
        "5".to_owned(),
        "--inspect-min-evolution-live-hierarchy-weight-mutations".to_owned(),
        "6".to_owned(),
        "--inspect-min-evolution-live-router-threshold-delta".to_owned(),
        "0.06".to_owned(),
        "--inspect-min-evolution-live-hierarchy-weight-delta".to_owned(),
        "0.07".to_owned(),
        "--inspect-min-evolution-live-online-reward-feedbacks".to_owned(),
        "4".to_owned(),
        "--inspect-min-evolution-live-online-reward-reinforcements".to_owned(),
        "3".to_owned(),
        "--inspect-min-evolution-live-online-reward-penalties".to_owned(),
        "1".to_owned(),
        "--inspect-min-evolution-live-online-reward-strength".to_owned(),
        "1.9".to_owned(),
        "--inspect-min-evolution-live-online-reward-reinforcement-strength".to_owned(),
        "1.2".to_owned(),
        "--inspect-min-evolution-live-online-reward-penalty-strength".to_owned(),
        "0.7".to_owned(),
        "--inspect-min-evolution-live-memory-updates".to_owned(),
        "8".to_owned(),
        "--inspect-min-evolution-live-stored-memory-updates".to_owned(),
        "7".to_owned(),
        "--inspect-min-evolution-live-reflection-issues".to_owned(),
        "6".to_owned(),
        "--inspect-min-evolution-live-critical-reflection-issues".to_owned(),
        "2".to_owned(),
        "--inspect-min-evolution-live-revision-actions".to_owned(),
        "5".to_owned(),
        "--inspect-min-evolution-replay-runs".to_owned(),
        "5".to_owned(),
        "--inspect-min-evolution-replay-items".to_owned(),
        "6".to_owned(),
        "--inspect-min-evolution-router-threshold-mutations".to_owned(),
        "7".to_owned(),
        "--inspect-min-evolution-hierarchy-weight-mutations".to_owned(),
        "8".to_owned(),
        "--inspect-min-evolution-router-threshold-delta".to_owned(),
        "0.04".to_owned(),
        "--inspect-min-evolution-hierarchy-weight-delta".to_owned(),
        "0.05".to_owned(),
        "--inspect-min-evolution-memory-updates".to_owned(),
        "9".to_owned(),
        "--inspect-min-evolution-external-feedbacks".to_owned(),
        "2".to_owned(),
        "--inspect-min-evolution-external-feedback-memory-updates".to_owned(),
        "3".to_owned(),
        "--inspect-min-evolution-external-feedback-strength-delta".to_owned(),
        "0.14".to_owned(),
        "--inspect-min-evolution-replay-live-memory-feedback-updates".to_owned(),
        "10".to_owned(),
        "--inspect-min-evolution-replay-live-memory-feedback-detail-items".to_owned(),
        "11".to_owned(),
        "--inspect-min-evolution-replay-live-memory-feedback-applied".to_owned(),
        "12".to_owned(),
        "--inspect-min-evolution-replay-live-memory-feedback-strength-delta".to_owned(),
        "0.13".to_owned(),
        "--inspect-min-evolution-replay-rust-check-items".to_owned(),
        "1".to_owned(),
        "--inspect-min-evolution-replay-rust-check-passed".to_owned(),
        "1".to_owned(),
        "--inspect-max-evolution-replay-rust-check-failed".to_owned(),
        "0".to_owned(),
        "--inspect-min-evolution-replay-rust-check-live-memory-feedback-updates".to_owned(),
        "2".to_owned(),
        "--inspect-min-evolution-replay-rust-check-live-memory-feedback-applied".to_owned(),
        "2".to_owned(),
        "--inspect-min-evolution-replay-rust-check-live-memory-feedback-strength-delta".to_owned(),
        "0.36".to_owned(),
        "--inspect-min-evolution-replay-live-evolution-items".to_owned(),
        "13".to_owned(),
        "--inspect-min-evolution-replay-live-evolution-online-reward-feedbacks".to_owned(),
        "4".to_owned(),
        "--inspect-min-evolution-replay-live-evolution-online-reward-reinforcements".to_owned(),
        "3".to_owned(),
        "--inspect-min-evolution-replay-live-evolution-online-reward-penalties".to_owned(),
        "1".to_owned(),
        "--inspect-min-evolution-replay-live-evolution-online-reward-strength".to_owned(),
        "1.3".to_owned(),
        "--inspect-min-evolution-replay-live-evolution-online-reward-reinforcement-strength"
            .to_owned(),
        "0.8".to_owned(),
        "--inspect-min-evolution-replay-live-evolution-online-reward-penalty-strength".to_owned(),
        "0.5".to_owned(),
        "--inspect-min-evolution-replay-live-evolution-memory-updates".to_owned(),
        "14".to_owned(),
        "--inspect-min-evolution-replay-live-evolution-stored-memory-updates".to_owned(),
        "15".to_owned(),
        "--inspect-min-evolution-replay-live-evolution-reflection-issues".to_owned(),
        "16".to_owned(),
        "--inspect-min-evolution-replay-live-evolution-critical-reflection-issues".to_owned(),
        "17".to_owned(),
        "--inspect-min-evolution-replay-live-evolution-revision-actions".to_owned(),
        "18".to_owned(),
        "--inspect-min-evolution-recursive-replay-items".to_owned(),
        "10".to_owned(),
        "--inspect-min-evolution-recursive-runtime-calls".to_owned(),
        "11".to_owned(),
        "--inspect-max-evolution-drift-rollbacks".to_owned(),
        "0".to_owned(),
        "--inspect-max-evolution-rollback-router-threshold-delta".to_owned(),
        "0.0".to_owned(),
        "--inspect-max-evolution-rollback-hierarchy-weight-delta".to_owned(),
        "0.0".to_owned(),
        "--inspect-require-runtime-kv-dimensions".to_owned(),
        "--local-runtime".to_owned(),
        "--production-runtime".to_owned(),
        "--production-reference-kernel".to_owned(),
        "--production-local-kernel".to_owned(),
        "--production-kernel-conformance-gate".to_owned(),
        "--production-kernel-conformance-all-devices-gate".to_owned(),
        "--runtime-model-id".to_owned(),
        "dev-transformer".to_owned(),
        "--runtime-tokenizer".to_owned(),
        "dev-bpe".to_owned(),
        "--runtime-wire-format".to_owned(),
        "json".to_owned(),
        "--runtime-native-window".to_owned(),
        "4096".to_owned(),
        "--runtime-embedding-dims".to_owned(),
        "128".to_owned(),
        "--runtime-kv-exchange".to_owned(),
        "--device".to_owned(),
        "cpu".to_owned(),
        "--cpu-load".to_owned(),
        "75".to_owned(),
        "--ram-load".to_owned(),
        "0.5".to_owned(),
        "one two three four five six seven eight nine".to_owned(),
    ]);

    assert_eq!(args.profile, TaskProfile::LongDocument);
    assert_eq!(args.native_window_tokens, 8);
    assert_eq!(args.chunk_tokens, 6);
    assert_eq!(args.chunk_overlap_tokens, 2);
    assert_eq!(args.merge_fan_in, 2);
    assert_eq!(args.replay_limit, 3);
    assert_eq!(args.auto_replay_limit, 4);
    assert_eq!(args.retention_stale_after, Some(12));
    assert_eq!(args.retention_decay_rate, Some(0.25));
    assert_eq!(args.retention_remove_below, Some(0.08));
    assert_eq!(args.retention_remove_after_failures, Some(7));
    assert_eq!(args.compaction_similarity_threshold, Some(0.88));
    assert_eq!(args.compaction_max_candidates, Some(64));
    assert_eq!(args.compaction_max_merges, Some(5));
    assert_eq!(
        args.trace_path.as_ref().unwrap(),
        &PathBuf::from("trace.jsonl")
    );
    assert_eq!(
        args.trace_schema_gate_path.as_ref().unwrap(),
        &PathBuf::from("trace-schema.jsonl")
    );
    assert_eq!(
        args.benchmark_path.as_ref().unwrap(),
        &PathBuf::from("benchmark.jsonl")
    );
    assert!(args.benchmark_all_devices);
    assert!(args.benchmark_gate_enabled);
    assert_eq!(args.benchmark_min_quality, Some(0.6));
    assert_eq!(args.benchmark_min_reward, Some(0.5));
    assert_eq!(args.benchmark_max_total_ms, Some(10000));
    assert_eq!(args.benchmark_max_recursive_chunks, Some(8));
    assert_eq!(args.benchmark_min_recursive_cases, Some(1));
    assert_eq!(args.benchmark_min_recursive_runtime_calls, Some(4));
    assert_eq!(args.benchmark_min_auto_replay_router_updates, Some(1));
    assert_eq!(args.benchmark_min_auto_replay_hierarchy_updates, Some(1));
    assert_eq!(
        args.benchmark_min_auto_replay_router_threshold_mutations,
        Some(1)
    );
    assert_eq!(
        args.benchmark_min_auto_replay_hierarchy_weight_mutations,
        Some(1)
    );
    assert_eq!(
        args.benchmark_min_auto_replay_router_threshold_delta,
        Some(0.01)
    );
    assert_eq!(
        args.benchmark_min_auto_replay_hierarchy_weight_delta,
        Some(0.01)
    );
    assert_eq!(args.benchmark_min_auto_replay_memory_updates, Some(1));
    assert_eq!(args.benchmark_min_live_memory_feedback_updates, Some(2));
    assert_eq!(
        args.benchmark_min_auto_replay_live_memory_feedback_updates,
        Some(3)
    );
    assert_eq!(
        args.benchmark_min_auto_replay_live_memory_feedback_detail_items,
        Some(2)
    );
    assert_eq!(
        args.benchmark_min_auto_replay_live_memory_feedback_applied,
        Some(4)
    );
    assert_eq!(
        args.benchmark_min_auto_replay_live_memory_feedback_strength_delta,
        Some(0.15)
    );
    assert_eq!(
        args.benchmark_gate().min_auto_replay_router_updates,
        Some(1)
    );
    assert_eq!(
        args.benchmark_gate().min_auto_replay_hierarchy_updates,
        Some(1)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_auto_replay_router_threshold_mutations,
        Some(1)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_auto_replay_hierarchy_weight_mutations,
        Some(1)
    );
    assert_eq!(
        args.benchmark_gate().min_auto_replay_router_threshold_delta,
        Some(0.01)
    );
    assert_eq!(
        args.benchmark_gate().min_auto_replay_hierarchy_weight_delta,
        Some(0.01)
    );
    assert_eq!(
        args.benchmark_gate().min_auto_replay_memory_updates,
        Some(1)
    );
    assert_eq!(
        args.benchmark_gate().min_live_memory_feedback_updates,
        Some(2)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_auto_replay_live_memory_feedback_updates,
        Some(3)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_auto_replay_live_memory_feedback_detail_items,
        Some(2)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_auto_replay_live_memory_feedback_applied,
        Some(4)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_auto_replay_live_memory_feedback_strength_delta,
        Some(0.15)
    );
    assert_eq!(args.benchmark_min_auto_replay_recursive_items, Some(1));
    assert_eq!(
        args.benchmark_min_auto_replay_recursive_call_pressure,
        Some(0.05)
    );
    assert_eq!(
        args.benchmark_max_auto_replay_recursive_call_pressure,
        Some(0.25)
    );
    assert_eq!(
        args.benchmark_gate().min_auto_replay_recursive_items,
        Some(1)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_auto_replay_recursive_call_pressure,
        Some(0.05)
    );
    assert_eq!(
        args.benchmark_gate()
            .max_auto_replay_recursive_call_pressure,
        Some(0.25)
    );
    assert_eq!(args.benchmark_min_evolution_live_inference_runs, Some(8));
    assert_eq!(
        args.benchmark_min_evolution_live_router_threshold_mutations,
        Some(2)
    );
    assert_eq!(
        args.benchmark_min_evolution_live_hierarchy_weight_mutations,
        Some(1)
    );
    assert_eq!(
        args.benchmark_min_evolution_live_router_threshold_delta,
        Some(0.04)
    );
    assert_eq!(
        args.benchmark_min_evolution_live_hierarchy_weight_delta,
        Some(0.03)
    );
    assert_eq!(args.benchmark_min_evolution_live_memory_updates, Some(5));
    assert_eq!(
        args.benchmark_min_evolution_live_stored_memory_updates,
        Some(4)
    );
    assert_eq!(args.benchmark_min_evolution_live_reflection_issues, Some(3));
    assert_eq!(
        args.benchmark_min_evolution_live_critical_reflection_issues,
        Some(1)
    );
    assert_eq!(args.benchmark_min_evolution_live_revision_actions, Some(2));
    assert_eq!(
        args.benchmark_gate().min_evolution_live_inference_runs,
        Some(8)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_live_router_threshold_mutations,
        Some(2)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_live_hierarchy_weight_mutations,
        Some(1)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_live_router_threshold_delta,
        Some(0.04)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_live_hierarchy_weight_delta,
        Some(0.03)
    );
    assert_eq!(
        args.benchmark_min_evolution_live_online_reward_feedbacks,
        Some(3)
    );
    assert_eq!(
        args.benchmark_min_evolution_live_online_reward_reinforcements,
        Some(2)
    );
    assert_eq!(
        args.benchmark_min_evolution_live_online_reward_penalties,
        Some(1)
    );
    assert_eq!(
        args.benchmark_min_evolution_live_online_reward_strength,
        Some(1.4)
    );
    assert_eq!(
        args.benchmark_min_evolution_live_online_reward_reinforcement_strength,
        Some(0.8)
    );
    assert_eq!(
        args.benchmark_min_evolution_live_online_reward_penalty_strength,
        Some(0.6)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_live_online_reward_feedbacks,
        Some(3)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_live_online_reward_reinforcements,
        Some(2)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_live_online_reward_penalties,
        Some(1)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_live_online_reward_strength,
        Some(1.4)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_live_online_reward_reinforcement_strength,
        Some(0.8)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_live_online_reward_penalty_strength,
        Some(0.6)
    );
    assert_eq!(
        args.benchmark_gate().min_evolution_live_memory_updates,
        Some(5)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_live_stored_memory_updates,
        Some(4)
    );
    assert_eq!(
        args.benchmark_gate().min_evolution_live_reflection_issues,
        Some(3)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_live_critical_reflection_issues,
        Some(1)
    );
    assert_eq!(
        args.benchmark_gate().min_evolution_live_revision_actions,
        Some(2)
    );
    assert_eq!(
        args.benchmark_min_evolution_live_inference_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.benchmark_min_evolution_live_router_threshold_mutation_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.benchmark_min_evolution_live_hierarchy_weight_mutation_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.benchmark_min_evolution_live_online_reward_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.benchmark_min_evolution_live_online_reward_strength_device_profiles,
        Some(11)
    );
    assert_eq!(
        args.benchmark_min_evolution_live_memory_update_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.benchmark_min_evolution_live_stored_memory_update_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.benchmark_min_evolution_live_reflection_issue_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.benchmark_min_evolution_live_critical_reflection_issue_device_profiles,
        Some(6)
    );
    assert_eq!(
        args.benchmark_min_evolution_live_revision_action_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_live_inference_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_live_router_threshold_mutation_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_live_hierarchy_weight_mutation_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_live_online_reward_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_live_online_reward_strength_device_profiles,
        Some(11)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_live_memory_update_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_live_stored_memory_update_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_live_reflection_issue_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_live_critical_reflection_issue_device_profiles,
        Some(6)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_live_revision_action_device_profiles,
        Some(12)
    );
    assert_eq!(args.benchmark_min_evolution_replay_runs, Some(1));
    assert_eq!(args.benchmark_min_evolution_replay_items, Some(2));
    assert_eq!(
        args.benchmark_min_evolution_router_threshold_mutations,
        Some(3)
    );
    assert_eq!(
        args.benchmark_min_evolution_hierarchy_weight_mutations,
        Some(4)
    );
    assert_eq!(
        args.benchmark_min_evolution_router_threshold_delta,
        Some(0.02)
    );
    assert_eq!(
        args.benchmark_min_evolution_hierarchy_weight_delta,
        Some(0.03)
    );
    assert_eq!(args.benchmark_min_evolution_memory_updates, Some(5));
    assert_eq!(
        args.benchmark_min_evolution_replay_live_memory_feedback_updates,
        Some(6)
    );
    assert_eq!(
        args.benchmark_min_evolution_replay_live_memory_feedback_detail_items,
        Some(7)
    );
    assert_eq!(
        args.benchmark_min_evolution_replay_live_memory_feedback_applied,
        Some(8)
    );
    assert_eq!(
        args.benchmark_min_evolution_replay_live_memory_feedback_strength_delta,
        Some(0.09)
    );
    assert_eq!(
        args.benchmark_min_evolution_replay_rust_check_items,
        Some(1)
    );
    assert_eq!(
        args.benchmark_min_evolution_replay_rust_check_passed,
        Some(1)
    );
    assert_eq!(
        args.benchmark_max_evolution_replay_rust_check_failed,
        Some(0)
    );
    assert_eq!(
        args.benchmark_min_evolution_replay_rust_check_live_memory_feedback_updates,
        Some(2)
    );
    assert_eq!(
        args.benchmark_min_evolution_replay_rust_check_live_memory_feedback_applied,
        Some(2)
    );
    assert_eq!(
        args.benchmark_min_evolution_replay_rust_check_live_memory_feedback_strength_delta,
        Some(0.36)
    );
    assert_eq!(
        args.benchmark_min_evolution_replay_live_evolution_items,
        Some(9)
    );
    assert_eq!(
        args.benchmark_min_evolution_replay_live_evolution_online_reward_feedbacks,
        Some(4)
    );
    assert_eq!(
        args.benchmark_min_evolution_replay_live_evolution_online_reward_reinforcements,
        Some(3)
    );
    assert_eq!(
        args.benchmark_min_evolution_replay_live_evolution_online_reward_penalties,
        Some(1)
    );
    assert_eq!(
        args.benchmark_min_evolution_replay_live_evolution_online_reward_strength,
        Some(1.1)
    );
    assert_eq!(
        args.benchmark_min_evolution_replay_live_evolution_online_reward_reinforcement_strength,
        Some(0.7)
    );
    assert_eq!(
        args.benchmark_min_evolution_replay_live_evolution_online_reward_penalty_strength,
        Some(0.4)
    );
    assert_eq!(
        args.benchmark_min_evolution_replay_live_evolution_memory_updates,
        Some(10)
    );
    assert_eq!(
        args.benchmark_min_evolution_replay_live_evolution_stored_memory_updates,
        Some(11)
    );
    assert_eq!(
        args.benchmark_min_evolution_replay_live_evolution_reflection_issues,
        Some(12)
    );
    assert_eq!(
        args.benchmark_min_evolution_replay_live_evolution_critical_reflection_issues,
        Some(13)
    );
    assert_eq!(
        args.benchmark_min_evolution_replay_live_evolution_revision_actions,
        Some(14)
    );
    assert_eq!(
        args.benchmark_min_evolution_replay_live_evolution_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.benchmark_min_evolution_replay_live_evolution_online_reward_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.benchmark_min_evolution_replay_live_evolution_online_reward_strength_device_profiles,
        Some(11)
    );
    assert_eq!(
        args.benchmark_min_evolution_replay_live_evolution_memory_update_device_profiles,
        Some(12)
    );
    assert_eq!(
            args.benchmark_min_evolution_replay_live_evolution_critical_reflection_issue_device_profiles,
            Some(6)
        );
    assert_eq!(
        args.benchmark_min_evolution_replay_live_evolution_revision_action_device_profiles,
        Some(12)
    );
    assert_eq!(args.benchmark_min_evolution_recursive_replay_items, Some(6));
    assert_eq!(
        args.benchmark_min_evolution_recursive_runtime_calls,
        Some(7)
    );
    assert_eq!(args.benchmark_max_evolution_drift_rollbacks, Some(0));
    assert_eq!(
        args.benchmark_max_evolution_rollback_router_threshold_delta,
        Some(0.0)
    );
    assert_eq!(
        args.benchmark_max_evolution_rollback_hierarchy_weight_delta,
        Some(0.0)
    );
    assert_eq!(args.benchmark_gate().min_evolution_replay_runs, Some(1));
    assert_eq!(args.benchmark_gate().min_evolution_replay_items, Some(2));
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_router_threshold_mutations,
        Some(3)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_hierarchy_weight_mutations,
        Some(4)
    );
    assert_eq!(
        args.benchmark_gate().min_evolution_router_threshold_delta,
        Some(0.02)
    );
    assert_eq!(
        args.benchmark_gate().min_evolution_hierarchy_weight_delta,
        Some(0.03)
    );
    assert_eq!(args.benchmark_gate().min_evolution_memory_updates, Some(5));
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_replay_live_memory_feedback_updates,
        Some(6)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_replay_live_memory_feedback_detail_items,
        Some(7)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_replay_live_memory_feedback_applied,
        Some(8)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_replay_live_memory_feedback_strength_delta,
        Some(0.09)
    );
    assert_eq!(
        args.benchmark_gate().min_evolution_replay_rust_check_items,
        Some(1)
    );
    assert_eq!(
        args.benchmark_gate().min_evolution_replay_rust_check_passed,
        Some(1)
    );
    assert_eq!(
        args.benchmark_gate().max_evolution_replay_rust_check_failed,
        Some(0)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_replay_rust_check_live_memory_feedback_updates,
        Some(2)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_replay_rust_check_live_memory_feedback_applied,
        Some(2)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_replay_rust_check_live_memory_feedback_strength_delta,
        Some(0.36)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_replay_live_evolution_items,
        Some(9)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_replay_live_evolution_online_reward_feedbacks,
        Some(4)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_replay_live_evolution_online_reward_reinforcements,
        Some(3)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_replay_live_evolution_online_reward_penalties,
        Some(1)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_replay_live_evolution_online_reward_strength,
        Some(1.1)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_replay_live_evolution_online_reward_reinforcement_strength,
        Some(0.7)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_replay_live_evolution_online_reward_penalty_strength,
        Some(0.4)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_replay_live_evolution_memory_updates,
        Some(10)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_replay_live_evolution_stored_memory_updates,
        Some(11)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_replay_live_evolution_reflection_issues,
        Some(12)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_replay_live_evolution_critical_reflection_issues,
        Some(13)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_replay_live_evolution_revision_actions,
        Some(14)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_replay_live_evolution_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_replay_live_evolution_online_reward_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_replay_live_evolution_online_reward_strength_device_profiles,
        Some(11)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_replay_live_evolution_memory_update_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_replay_live_evolution_critical_reflection_issue_device_profiles,
        Some(6)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_evolution_replay_live_evolution_revision_action_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.benchmark_gate().min_evolution_recursive_replay_items,
        Some(6)
    );
    assert_eq!(
        args.benchmark_gate().min_evolution_recursive_runtime_calls,
        Some(7)
    );
    assert_eq!(args.benchmark_gate().max_evolution_drift_rollbacks, Some(0));
    assert_eq!(
        args.benchmark_gate()
            .max_evolution_rollback_router_threshold_delta,
        Some(0.0)
    );
    assert_eq!(
        args.benchmark_gate()
            .max_evolution_rollback_hierarchy_weight_delta,
        Some(0.0)
    );
    assert_eq!(args.benchmark_min_sparse_skipped_cases, Some(1));
    assert_eq!(args.benchmark_min_sparse_skipped_tokens, Some(3));
    assert_eq!(args.benchmark_gate().min_sparse_skipped_cases, Some(1));
    assert_eq!(args.benchmark_gate().min_sparse_skipped_tokens, Some(3));
    assert_eq!(args.benchmark_min_runtime_forward_cases, Some(4));
    assert_eq!(args.benchmark_min_runtime_forward_energy_cases, Some(4));
    assert_eq!(args.benchmark_min_runtime_kv_influence_cases, Some(4));
    assert_eq!(args.benchmark_min_runtime_architecture_cases, Some(4));
    assert_eq!(
        args.benchmark_min_runtime_architecture_device_profiles,
        Some(12)
    );
    assert_eq!(args.benchmark_min_runtime_kv_precision_cases, Some(4));
    assert_eq!(
        args.benchmark_min_runtime_kv_precision_device_profiles,
        Some(12)
    );
    assert_eq!(args.benchmark_min_runtime_uncertainty_cases, Some(4));
    assert_eq!(args.benchmark_min_runtime_uncertainty_tokens, Some(4));
    assert_eq!(
        args.benchmark_min_runtime_uncertainty_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.benchmark_min_runtime_uncertainty_token_device_profiles,
        Some(12)
    );
    assert_eq!(args.benchmark_min_runtime_kv_import_cases, Some(4));
    assert_eq!(args.benchmark_min_runtime_kv_imported, Some(4));
    assert_eq!(
        args.benchmark_min_runtime_kv_import_device_profiles,
        Some(6)
    );
    assert_eq!(args.benchmark_min_runtime_kv_exported, Some(4));
    assert_eq!(
        args.benchmark_min_runtime_kv_export_device_profiles,
        Some(6)
    );
    assert_eq!(args.benchmark_min_runtime_kv_stored, Some(2));
    assert_eq!(
        args.benchmark_min_runtime_kv_stored_device_profiles,
        Some(6)
    );
    assert_eq!(args.benchmark_min_runtime_kv_hold_cases, Some(1));
    assert_eq!(args.benchmark_min_runtime_kv_held, Some(2));
    assert_eq!(args.benchmark_min_runtime_kv_hold_device_profiles, Some(6));
    assert_eq!(
        args.benchmark_gate().min_runtime_kv_hold_device_profiles,
        Some(6)
    );
    assert_eq!(args.benchmark_min_runtime_adapter_contract_cases, Some(4));
    assert_eq!(args.benchmark_min_runtime_adapter_kinds, Some(3));
    assert_eq!(args.benchmark_min_runtime_adapter_observations, Some(2));
    assert_eq!(args.benchmark_min_runtime_adapter_best_score, Some(0.25));
    assert_eq!(
        args.benchmark_max_runtime_adapter_contract_violations,
        Some(0)
    );
    assert_eq!(
        args.benchmark_max_runtime_adapter_selection_mismatches,
        Some(0)
    );
    assert_eq!(args.benchmark_min_runtime_embedding_cases, Some(4));
    assert_eq!(
        args.benchmark_min_runtime_embedding_device_profiles,
        Some(12)
    );
    assert_eq!(args.benchmark_max_embedding_fallback_cases, Some(0));
    assert_eq!(args.benchmark_max_embedding_evidence_failures, Some(0));
    assert_eq!(args.benchmark_min_runtime_device_execution_cases, Some(4));
    assert_eq!(
        args.benchmark_min_runtime_device_execution_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.benchmark_max_runtime_device_execution_violations,
        Some(0)
    );
    assert_eq!(args.benchmark_max_memory_governance_failures, Some(0));
    assert_eq!(args.benchmark_min_memory_governance_cases, Some(4));
    assert_eq!(
        args.benchmark_min_memory_governance_device_profiles,
        Some(12)
    );
    assert_eq!(args.benchmark_min_memory_retention_activity_cases, Some(1));
    assert_eq!(args.benchmark_min_memory_compaction_activity_cases, Some(1));
    assert_eq!(args.benchmark_min_reflection_issue_cases, Some(2));
    assert_eq!(args.benchmark_min_reflection_issues, Some(3));
    assert_eq!(args.benchmark_min_critical_reflection_issue_cases, Some(1));
    assert_eq!(args.benchmark_min_critical_reflection_issues, Some(1));
    assert_eq!(args.benchmark_min_revision_action_cases, Some(2));
    assert_eq!(args.benchmark_min_revision_actions, Some(4));
    assert_eq!(
        args.benchmark_min_reflection_issue_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.benchmark_min_critical_reflection_issue_device_profiles,
        Some(6)
    );
    assert_eq!(args.benchmark_min_revision_action_device_profiles, Some(12));
    assert_eq!(args.benchmark_min_device_profiles, Some(12));
    assert_eq!(args.benchmark_min_recursive_device_profiles, Some(12));
    assert_eq!(args.benchmark_gate().min_runtime_forward_cases, Some(4));
    assert_eq!(
        args.benchmark_gate().min_runtime_forward_energy_cases,
        Some(4)
    );
    assert_eq!(
        args.benchmark_gate().min_runtime_kv_influence_cases,
        Some(4)
    );
    assert_eq!(
        args.benchmark_gate().min_runtime_architecture_cases,
        Some(4)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_runtime_architecture_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.benchmark_gate().min_runtime_kv_precision_cases,
        Some(4)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_runtime_kv_precision_device_profiles,
        Some(12)
    );
    assert_eq!(args.benchmark_gate().min_runtime_uncertainty_cases, Some(4));
    assert_eq!(
        args.benchmark_gate().min_runtime_uncertainty_tokens,
        Some(4)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_runtime_uncertainty_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_runtime_uncertainty_token_device_profiles,
        Some(12)
    );
    assert_eq!(args.benchmark_gate().min_runtime_kv_import_cases, Some(4));
    assert_eq!(args.benchmark_gate().min_runtime_kv_imported, Some(4));
    assert_eq!(
        args.benchmark_gate().min_runtime_kv_import_device_profiles,
        Some(6)
    );
    assert_eq!(args.benchmark_gate().min_runtime_kv_exported, Some(4));
    assert_eq!(
        args.benchmark_gate().min_runtime_kv_export_device_profiles,
        Some(6)
    );
    assert_eq!(args.benchmark_gate().min_runtime_kv_stored, Some(2));
    assert_eq!(
        args.benchmark_gate().min_runtime_kv_stored_device_profiles,
        Some(6)
    );
    assert_eq!(args.benchmark_gate().min_runtime_kv_hold_cases, Some(1));
    assert_eq!(args.benchmark_gate().min_runtime_kv_held, Some(2));
    assert_eq!(
        args.benchmark_gate().min_runtime_adapter_contract_cases,
        Some(4)
    );
    assert_eq!(args.benchmark_gate().min_runtime_adapter_kinds, Some(3));
    assert_eq!(
        args.benchmark_gate().min_runtime_adapter_observations,
        Some(2)
    );
    assert_eq!(
        args.benchmark_gate().min_runtime_adapter_best_score,
        Some(0.25)
    );
    assert_eq!(
        args.benchmark_gate()
            .max_runtime_adapter_contract_violations,
        Some(0)
    );
    assert_eq!(
        args.benchmark_gate()
            .max_runtime_adapter_selection_mismatches,
        Some(0)
    );
    assert_eq!(args.benchmark_gate().min_runtime_embedding_cases, Some(4));
    assert_eq!(
        args.benchmark_gate().min_runtime_embedding_device_profiles,
        Some(12)
    );
    assert_eq!(args.benchmark_gate().max_embedding_fallback_cases, Some(0));
    assert_eq!(
        args.benchmark_gate().max_embedding_evidence_failures,
        Some(0)
    );
    assert_eq!(
        args.benchmark_gate().min_runtime_device_execution_cases,
        Some(4)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_runtime_device_execution_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.benchmark_gate()
            .max_runtime_device_execution_violations,
        Some(0)
    );
    assert_eq!(
        args.benchmark_gate().max_memory_governance_failures,
        Some(0)
    );
    assert_eq!(args.benchmark_gate().min_memory_governance_cases, Some(4));
    assert_eq!(
        args.benchmark_gate().min_memory_governance_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.benchmark_gate().min_memory_retention_activity_cases,
        Some(1)
    );
    assert_eq!(
        args.benchmark_gate().min_memory_compaction_activity_cases,
        Some(1)
    );
    assert_eq!(args.benchmark_gate().min_reflection_issue_cases, Some(2));
    assert_eq!(args.benchmark_gate().min_reflection_issues, Some(3));
    assert_eq!(
        args.benchmark_gate().min_critical_reflection_issue_cases,
        Some(1)
    );
    assert_eq!(
        args.benchmark_gate().min_critical_reflection_issues,
        Some(1)
    );
    assert_eq!(args.benchmark_gate().min_revision_action_cases, Some(2));
    assert_eq!(args.benchmark_gate().min_revision_actions, Some(4));
    assert_eq!(
        args.benchmark_gate().min_reflection_issue_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.benchmark_gate()
            .min_critical_reflection_issue_device_profiles,
        Some(6)
    );
    assert_eq!(
        args.benchmark_gate().min_revision_action_device_profiles,
        Some(12)
    );
    assert_eq!(args.benchmark_gate().min_device_profiles, Some(12));
    assert_eq!(
        args.benchmark_gate().min_recursive_device_profiles,
        Some(12)
    );
    assert_eq!(args.benchmark_max_drift_blocks, Some(0));
    assert_eq!(args.benchmark_max_drift_rollbacks, Some(0));
    assert!(args.benchmark_roundtrip);
    assert!(args.list_devices);
    assert!(args.probe_device);
    assert!(args.device_gate);
    assert!(args.kv_quant_gate);
    assert_eq!(args.kv_quant_max_total_us, Some(100000));
    assert!(args.runtime_manifest_gate);
    assert!(args.runtime_manifest_all_devices_gate);
    assert_eq!(
        args.runtime_weights_path.as_ref().unwrap(),
        &PathBuf::from("weights.noiron")
    );
    assert_eq!(
        args.runtime_tokenizer_path.as_ref().unwrap(),
        &PathBuf::from("tokenizer.noiron")
    );
    assert_eq!(
        args.runtime_config_path.as_ref().unwrap(),
        &PathBuf::from("config.noiron")
    );
    assert_eq!(args.runtime_layer_count, Some(18));
    assert_eq!(args.runtime_hidden_size, Some(128));
    assert_eq!(args.runtime_attention_heads, Some(8));
    assert_eq!(args.runtime_kv_heads, Some(4));
    assert_eq!(args.runtime_local_window_tokens, Some(2048));
    assert!(args.inspect_state);
    assert_eq!(args.inspect_limit, 2);
    assert!(args.inspect_gate);
    assert_eq!(args.inspect_min_memories, Some(3));
    assert_eq!(args.inspect_min_runtime_kv_memories, Some(1));
    assert_eq!(args.inspect_min_experiences, Some(2));
    assert_eq!(args.inspect_min_runtime_model_experiences, Some(2));
    assert_eq!(args.inspect_min_runtime_adapter_experiences, Some(2));
    assert_eq!(args.inspect_min_runtime_forward_energy_experiences, Some(2));
    assert_eq!(args.inspect_min_runtime_kv_influence_experiences, Some(2));
    assert_eq!(args.inspect_min_runtime_tokens, Some(5));
    assert_eq!(args.inspect_min_runtime_uncertainty_experiences, Some(2));
    assert_eq!(args.inspect_min_runtime_architecture_experiences, Some(2));
    assert_eq!(args.inspect_min_runtime_kv_precision_experiences, Some(2));
    assert_eq!(
        args.inspect_min_runtime_device_execution_experiences,
        Some(2)
    );
    assert_eq!(args.inspect_min_runtime_layer_mode_experiences, Some(2));
    assert_eq!(args.inspect_min_runtime_all_layer_mode_experiences, Some(2));
    assert_eq!(args.inspect_min_runtime_global_layers, Some(4));
    assert_eq!(args.inspect_min_runtime_local_window_layers, Some(6));
    assert_eq!(
        args.inspect_min_runtime_convolutional_fusion_layers,
        Some(2)
    );
    assert_eq!(args.inspect_min_runtime_kv_import_experiences, Some(2));
    assert_eq!(args.inspect_min_runtime_kv_export_experiences, Some(2));
    assert_eq!(args.inspect_min_runtime_kv_hold_experiences, Some(1));
    assert_eq!(args.inspect_min_runtime_kv_held_blocks, Some(2));
    assert_eq!(args.inspect_min_runtime_kv_memory_device_profiles, Some(12));
    assert_eq!(args.inspect_min_runtime_model_device_profiles, Some(12));
    assert_eq!(args.inspect_min_runtime_adapter_device_profiles, Some(12));
    assert_eq!(
        args.inspect_min_runtime_forward_energy_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.inspect_min_runtime_kv_influence_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.inspect_min_runtime_uncertainty_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.inspect_min_runtime_kv_precision_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.inspect_min_runtime_device_execution_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.inspect_min_runtime_layer_mode_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.inspect_min_runtime_all_layer_mode_device_profiles,
        Some(12)
    );
    assert_eq!(args.inspect_min_runtime_kv_import_device_profiles, Some(12));
    assert_eq!(args.inspect_min_runtime_kv_export_device_profiles, Some(12));
    assert_eq!(args.inspect_min_runtime_kv_hold_device_profiles, Some(6));
    assert_eq!(args.inspect_min_reflection_issue_experiences, Some(3));
    assert_eq!(
        args.inspect_min_critical_reflection_issue_experiences,
        Some(1)
    );
    assert_eq!(args.inspect_min_revision_action_experiences, Some(2));
    assert_eq!(args.inspect_min_live_memory_feedback_experiences, Some(2));
    assert_eq!(args.inspect_min_live_memory_feedback_updates, Some(5));
    assert_eq!(
        args.inspect_min_live_memory_feedback_detail_experiences,
        Some(2)
    );
    assert_eq!(args.inspect_min_live_memory_feedback_applied, Some(4));
    assert_eq!(
        args.inspect_min_live_memory_feedback_strength_delta,
        Some(0.51)
    );
    assert_eq!(args.inspect_min_reflection_issue_device_profiles, Some(12));
    assert_eq!(
        args.inspect_min_critical_reflection_issue_device_profiles,
        Some(6)
    );
    assert_eq!(args.inspect_min_revision_action_device_profiles, Some(12));
    assert_eq!(
        args.inspect_min_live_memory_feedback_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.inspect_min_evolution_live_inference_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.inspect_min_evolution_live_router_threshold_mutation_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.inspect_min_evolution_live_hierarchy_weight_mutation_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.inspect_min_evolution_live_online_reward_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.inspect_min_evolution_live_online_reward_strength_device_profiles,
        Some(11)
    );
    assert_eq!(
        args.inspect_min_evolution_live_memory_update_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.inspect_min_evolution_live_stored_memory_update_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.inspect_min_evolution_live_reflection_issue_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.inspect_min_evolution_live_critical_reflection_issue_device_profiles,
        Some(6)
    );
    assert_eq!(
        args.inspect_min_evolution_live_revision_action_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.inspect_min_evolution_replay_run_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.inspect_min_evolution_replay_item_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.inspect_min_evolution_router_threshold_mutation_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.inspect_min_evolution_hierarchy_weight_mutation_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.inspect_min_evolution_memory_update_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.inspect_min_evolution_replay_live_memory_feedback_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.inspect_min_evolution_replay_live_memory_feedback_detail_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.inspect_min_evolution_replay_live_evolution_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.inspect_min_evolution_replay_live_evolution_online_reward_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.inspect_min_evolution_replay_live_evolution_online_reward_strength_device_profiles,
        Some(11)
    );
    assert_eq!(
        args.inspect_min_evolution_replay_live_evolution_memory_update_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.inspect_min_evolution_replay_live_evolution_critical_reflection_issue_device_profiles,
        Some(6)
    );
    assert_eq!(
        args.inspect_min_evolution_replay_live_evolution_revision_action_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.inspect_min_evolution_recursive_replay_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.inspect_min_evolution_recursive_runtime_call_device_profiles,
        Some(12)
    );
    assert_eq!(args.inspect_min_router_observations, Some(4));
    assert_eq!(args.inspect_min_evolution_live_inference_runs, Some(4));
    assert_eq!(
        args.inspect_min_evolution_live_router_threshold_mutations,
        Some(5)
    );
    assert_eq!(
        args.inspect_min_evolution_live_hierarchy_weight_mutations,
        Some(6)
    );
    assert_eq!(
        args.inspect_min_evolution_live_router_threshold_delta,
        Some(0.06)
    );
    assert_eq!(
        args.inspect_min_evolution_live_hierarchy_weight_delta,
        Some(0.07)
    );
    assert_eq!(
        args.inspect_min_evolution_live_online_reward_feedbacks,
        Some(4)
    );
    assert_eq!(
        args.inspect_min_evolution_live_online_reward_reinforcements,
        Some(3)
    );
    assert_eq!(
        args.inspect_min_evolution_live_online_reward_penalties,
        Some(1)
    );
    assert_eq!(
        args.inspect_min_evolution_live_online_reward_strength,
        Some(1.9)
    );
    assert_eq!(
        args.inspect_min_evolution_live_online_reward_reinforcement_strength,
        Some(1.2)
    );
    assert_eq!(
        args.inspect_min_evolution_live_online_reward_penalty_strength,
        Some(0.7)
    );
    assert_eq!(args.inspect_min_evolution_live_memory_updates, Some(8));
    assert_eq!(
        args.inspect_min_evolution_live_stored_memory_updates,
        Some(7)
    );
    assert_eq!(args.inspect_min_evolution_live_reflection_issues, Some(6));
    assert_eq!(
        args.inspect_min_evolution_live_critical_reflection_issues,
        Some(2)
    );
    assert_eq!(args.inspect_min_evolution_live_revision_actions, Some(5));
    assert_eq!(args.inspect_min_evolution_replay_runs, Some(5));
    assert_eq!(args.inspect_min_evolution_replay_items, Some(6));
    assert_eq!(
        args.inspect_min_evolution_router_threshold_mutations,
        Some(7)
    );
    assert_eq!(
        args.inspect_min_evolution_hierarchy_weight_mutations,
        Some(8)
    );
    assert_eq!(
        args.inspect_min_evolution_router_threshold_delta,
        Some(0.04)
    );
    assert_eq!(
        args.inspect_min_evolution_hierarchy_weight_delta,
        Some(0.05)
    );
    assert_eq!(args.inspect_min_evolution_memory_updates, Some(9));
    assert_eq!(args.inspect_min_evolution_external_feedbacks, Some(2));
    assert_eq!(
        args.inspect_min_evolution_external_feedback_memory_updates,
        Some(3)
    );
    assert_eq!(
        args.inspect_min_evolution_external_feedback_strength_delta,
        Some(0.14)
    );
    assert_eq!(
        args.inspect_min_evolution_replay_live_memory_feedback_updates,
        Some(10)
    );
    assert_eq!(
        args.inspect_min_evolution_replay_live_memory_feedback_detail_items,
        Some(11)
    );
    assert_eq!(
        args.inspect_min_evolution_replay_live_memory_feedback_applied,
        Some(12)
    );
    assert_eq!(
        args.inspect_min_evolution_replay_live_memory_feedback_strength_delta,
        Some(0.13)
    );
    assert_eq!(args.inspect_min_evolution_replay_rust_check_items, Some(1));
    assert_eq!(args.inspect_min_evolution_replay_rust_check_passed, Some(1));
    assert_eq!(args.inspect_max_evolution_replay_rust_check_failed, Some(0));
    assert_eq!(
        args.inspect_min_evolution_replay_rust_check_live_memory_feedback_updates,
        Some(2)
    );
    assert_eq!(
        args.inspect_min_evolution_replay_rust_check_live_memory_feedback_applied,
        Some(2)
    );
    assert_eq!(
        args.inspect_min_evolution_replay_rust_check_live_memory_feedback_strength_delta,
        Some(0.36)
    );
    assert_eq!(
        args.inspect_min_evolution_replay_live_evolution_items,
        Some(13)
    );
    assert_eq!(
        args.inspect_min_evolution_replay_live_evolution_online_reward_feedbacks,
        Some(4)
    );
    assert_eq!(
        args.inspect_min_evolution_replay_live_evolution_online_reward_reinforcements,
        Some(3)
    );
    assert_eq!(
        args.inspect_min_evolution_replay_live_evolution_online_reward_penalties,
        Some(1)
    );
    assert_eq!(
        args.inspect_min_evolution_replay_live_evolution_online_reward_strength,
        Some(1.3)
    );
    assert_eq!(
        args.inspect_min_evolution_replay_live_evolution_online_reward_reinforcement_strength,
        Some(0.8)
    );
    assert_eq!(
        args.inspect_min_evolution_replay_live_evolution_online_reward_penalty_strength,
        Some(0.5)
    );
    assert_eq!(
        args.inspect_min_evolution_replay_live_evolution_memory_updates,
        Some(14)
    );
    assert_eq!(
        args.inspect_min_evolution_replay_live_evolution_stored_memory_updates,
        Some(15)
    );
    assert_eq!(
        args.inspect_min_evolution_replay_live_evolution_reflection_issues,
        Some(16)
    );
    assert_eq!(
        args.inspect_min_evolution_replay_live_evolution_critical_reflection_issues,
        Some(17)
    );
    assert_eq!(
        args.inspect_min_evolution_replay_live_evolution_revision_actions,
        Some(18)
    );
    assert_eq!(args.inspect_min_evolution_recursive_replay_items, Some(10));
    assert_eq!(args.inspect_min_evolution_recursive_runtime_calls, Some(11));
    assert_eq!(args.inspect_max_evolution_drift_rollbacks, Some(0));
    assert_eq!(
        args.inspect_max_evolution_rollback_router_threshold_delta,
        Some(0.0)
    );
    assert_eq!(
        args.inspect_max_evolution_rollback_hierarchy_weight_delta,
        Some(0.0)
    );
    assert!(args.inspect_require_runtime_kv_dimensions);
    assert_eq!(args.state_inspection_gate().min_memories, Some(3));
    assert_eq!(
        args.state_inspection_gate().min_runtime_kv_memories,
        Some(1)
    );
    assert_eq!(args.state_inspection_gate().min_experiences, Some(2));
    assert_eq!(
        args.state_inspection_gate().min_runtime_model_experiences,
        Some(2)
    );
    assert_eq!(
        args.state_inspection_gate().min_runtime_adapter_experiences,
        Some(2)
    );
    assert_eq!(
        args.inspect_max_runtime_adapter_selection_mismatches,
        Some(0)
    );
    assert_eq!(
        args.state_inspection_gate()
            .max_runtime_adapter_selection_mismatches,
        Some(0)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_runtime_forward_energy_experiences,
        Some(2)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_runtime_kv_influence_experiences,
        Some(2)
    );
    assert_eq!(args.state_inspection_gate().min_runtime_tokens, Some(5));
    assert_eq!(
        args.state_inspection_gate()
            .min_runtime_uncertainty_experiences,
        Some(2)
    );
    assert_eq!(
        args.state_inspection_gate().min_runtime_uncertainty_tokens,
        Some(8)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_runtime_architecture_experiences,
        Some(2)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_runtime_kv_precision_experiences,
        Some(2)
    );
    assert_eq!(args.inspect_max_runtime_kv_precision_mismatches, Some(0));
    assert_eq!(
        args.state_inspection_gate()
            .max_runtime_kv_precision_mismatches,
        Some(0)
    );
    assert_eq!(args.inspect_max_runtime_errors, Some(0));
    assert_eq!(args.inspect_max_runtime_timeouts, Some(0));
    assert_eq!(args.state_inspection_gate().max_runtime_errors, Some(0));
    assert_eq!(args.state_inspection_gate().max_runtime_timeouts, Some(0));
    assert_eq!(
        args.state_inspection_gate()
            .min_runtime_device_execution_experiences,
        Some(2)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_runtime_layer_mode_experiences,
        Some(2)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_runtime_all_layer_mode_experiences,
        Some(2)
    );
    assert_eq!(
        args.state_inspection_gate().min_runtime_global_layers,
        Some(4)
    );
    assert_eq!(
        args.state_inspection_gate().min_runtime_local_window_layers,
        Some(6)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_runtime_convolutional_fusion_layers,
        Some(2)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_runtime_kv_import_experiences,
        Some(2)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_runtime_kv_export_experiences,
        Some(2)
    );
    assert_eq!(
        args.state_inspection_gate().min_runtime_kv_hold_experiences,
        Some(1)
    );
    assert_eq!(
        args.state_inspection_gate().min_runtime_kv_held_blocks,
        Some(2)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_reflection_issue_experiences,
        Some(3)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_critical_reflection_issue_experiences,
        Some(1)
    );
    assert_eq!(
        args.state_inspection_gate().min_revision_action_experiences,
        Some(2)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_live_memory_feedback_experiences,
        Some(2)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_live_memory_feedback_updates,
        Some(5)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_live_memory_feedback_detail_experiences,
        Some(2)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_live_memory_feedback_applied,
        Some(4)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_live_memory_feedback_strength_delta,
        Some(0.51)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_live_inference_runs,
        Some(4)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_live_router_threshold_mutations,
        Some(5)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_live_hierarchy_weight_mutations,
        Some(6)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_live_router_threshold_delta,
        Some(0.06)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_live_hierarchy_weight_delta,
        Some(0.07)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_live_online_reward_feedbacks,
        Some(4)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_live_online_reward_reinforcements,
        Some(3)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_live_online_reward_penalties,
        Some(1)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_live_online_reward_strength,
        Some(1.9)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_live_online_reward_reinforcement_strength,
        Some(1.2)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_live_online_reward_penalty_strength,
        Some(0.7)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_live_memory_updates,
        Some(8)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_live_stored_memory_updates,
        Some(7)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_live_reflection_issues,
        Some(6)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_live_critical_reflection_issues,
        Some(2)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_live_revision_actions,
        Some(5)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_runtime_kv_memory_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_runtime_model_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_runtime_adapter_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .max_runtime_adapter_selection_mismatches,
        Some(0)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_runtime_forward_energy_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_runtime_kv_influence_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_runtime_uncertainty_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_runtime_uncertainty_token_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_runtime_kv_precision_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .max_runtime_kv_precision_mismatches,
        Some(0)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_runtime_device_execution_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_runtime_layer_mode_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_runtime_all_layer_mode_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_runtime_kv_import_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_runtime_kv_export_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_runtime_kv_hold_device_profiles,
        Some(6)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_reflection_issue_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_critical_reflection_issue_device_profiles,
        Some(6)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_revision_action_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_live_memory_feedback_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_evolution_live_inference_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_evolution_live_router_threshold_mutation_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_evolution_live_hierarchy_weight_mutation_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_evolution_live_online_reward_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_evolution_live_online_reward_strength_device_profiles,
        Some(11)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_evolution_live_memory_update_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_evolution_live_stored_memory_update_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_evolution_live_reflection_issue_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_evolution_live_critical_reflection_issue_device_profiles,
        Some(6)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_evolution_live_revision_action_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_evolution_replay_run_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_evolution_replay_item_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_evolution_router_threshold_mutation_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_evolution_hierarchy_weight_mutation_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_evolution_memory_update_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_evolution_replay_live_memory_feedback_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_evolution_replay_live_memory_feedback_detail_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_evolution_replay_live_evolution_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_evolution_replay_live_evolution_online_reward_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_evolution_replay_live_evolution_online_reward_strength_device_profiles,
        Some(11)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_evolution_replay_live_evolution_memory_update_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_evolution_replay_live_evolution_critical_reflection_issue_device_profiles,
        Some(6)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_evolution_replay_live_evolution_revision_action_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_evolution_recursive_replay_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_matrix_gate()
            .min_evolution_recursive_runtime_call_device_profiles,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_router_threshold_delta,
        Some(0.04)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_hierarchy_weight_delta,
        Some(0.05)
    );
    assert_eq!(
        args.state_inspection_gate().min_evolution_memory_updates,
        Some(9)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_external_feedbacks,
        Some(2)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_external_feedback_memory_updates,
        Some(3)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_external_feedback_strength_delta,
        Some(0.14)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_replay_live_memory_feedback_updates,
        Some(10)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_replay_live_memory_feedback_detail_items,
        Some(11)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_replay_live_memory_feedback_applied,
        Some(12)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_replay_live_memory_feedback_strength_delta,
        Some(0.13)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_replay_rust_check_items,
        Some(1)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_replay_rust_check_passed,
        Some(1)
    );
    assert_eq!(
        args.state_inspection_gate()
            .max_evolution_replay_rust_check_failed,
        Some(0)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_replay_rust_check_live_memory_feedback_updates,
        Some(2)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_replay_rust_check_live_memory_feedback_applied,
        Some(2)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_replay_rust_check_live_memory_feedback_strength_delta,
        Some(0.36)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_replay_live_evolution_items,
        Some(13)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_replay_live_evolution_online_reward_feedbacks,
        Some(4)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_replay_live_evolution_online_reward_reinforcements,
        Some(3)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_replay_live_evolution_online_reward_penalties,
        Some(1)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_replay_live_evolution_online_reward_strength,
        Some(1.3)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_replay_live_evolution_online_reward_reinforcement_strength,
        Some(0.8)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_replay_live_evolution_online_reward_penalty_strength,
        Some(0.5)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_replay_live_evolution_memory_updates,
        Some(14)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_replay_live_evolution_stored_memory_updates,
        Some(15)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_replay_live_evolution_reflection_issues,
        Some(16)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_replay_live_evolution_critical_reflection_issues,
        Some(17)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_replay_live_evolution_revision_actions,
        Some(18)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_recursive_replay_items,
        Some(10)
    );
    assert_eq!(
        args.state_inspection_gate()
            .min_evolution_recursive_runtime_calls,
        Some(11)
    );
    assert_eq!(
        args.state_inspection_gate()
            .max_evolution_rollback_router_threshold_delta,
        Some(0.0)
    );
    assert_eq!(
        args.state_inspection_gate()
            .max_evolution_rollback_hierarchy_weight_delta,
        Some(0.0)
    );
    assert!(args.state_inspection_gate().require_runtime_kv_dimensions);
    assert!(args.local_runtime);
    assert!(args.production_runtime);
    assert!(args.production_reference_kernel);
    assert!(args.production_local_kernel);
    assert!(args.production_kernel_conformance_gate);
    assert!(args.production_kernel_conformance_all_devices_gate);
    assert_eq!(args.runtime_metadata.model_id, "dev-transformer");
    assert_eq!(args.runtime_metadata.tokenizer, "dev-bpe");
    assert_eq!(args.runtime_wire_format, CommandWireFormat::Json);
    assert_eq!(args.runtime_metadata.native_context_window, 4096);
    assert_eq!(args.runtime_metadata.embedding_dimensions, 128);
    assert!(args.runtime_metadata.supports_kv_import);
    assert!(args.runtime_metadata.supports_kv_export);
    assert_eq!(args.runtime_metadata.max_kv_import_blocks, 8);
    assert_eq!(args.runtime_metadata.max_kv_export_blocks, 4);
    assert_eq!(args.runtime_metadata.hot_kv_precision_bits, 8);
    assert_eq!(args.runtime_metadata.cold_kv_precision_bits, 4);
    assert_eq!(args.runtime_manifest().architecture.layer_count, 18);
    assert_eq!(args.runtime_manifest().architecture.hidden_size, 128);
    assert_eq!(args.runtime_manifest().architecture.attention_heads, 8);
    assert_eq!(args.runtime_manifest().architecture.kv_heads, 4);
    assert_eq!(
        args.runtime_manifest().architecture.local_window_tokens,
        2048
    );
    assert_eq!(args.device, DeviceClass::CpuOnly);
    assert_eq!(args.cpu_load, 75.0);
    assert_eq!(args.ram_load, 0.5);
    assert!(args.prompt.contains("nine"));
}
