use super::{TraceRequiredField, required_field};

pub(super) const AUTO_REPLAY_TRACE_REQUIRED_FIELDS: &[TraceRequiredField] = &[
    required_field("auto_replay", "\"auto_replay\":{"),
    required_field("auto_replay_router_updates", "\"router_updates\":"),
    required_field("auto_replay_hierarchy_updates", "\"hierarchy_updates\":"),
    required_field(
        "auto_replay_router_threshold_mutations",
        "\"router_threshold_mutations\":",
    ),
    required_field(
        "auto_replay_hierarchy_weight_mutations",
        "\"hierarchy_weight_mutations\":",
    ),
    required_field(
        "auto_replay_router_threshold_delta",
        "\"router_threshold_delta\":",
    ),
    required_field(
        "auto_replay_hierarchy_weight_delta",
        "\"hierarchy_weight_delta\":",
    ),
    required_field(
        "auto_replay_memory_reinforcements",
        "\"memory_reinforcements\":",
    ),
    required_field("auto_replay_memory_penalties", "\"memory_penalties\":"),
    required_field(
        "auto_replay_live_memory_feedback_items",
        "\"live_memory_feedback_items\":",
    ),
    required_field(
        "auto_replay_live_memory_feedback_updates",
        "\"live_memory_feedback_updates\":",
    ),
    required_field(
        "auto_replay_live_memory_feedback_reinforcements",
        "\"live_memory_feedback_reinforcements\":",
    ),
    required_field(
        "auto_replay_live_memory_feedback_penalties",
        "\"live_memory_feedback_penalties\":",
    ),
    required_field(
        "auto_replay_live_memory_feedback_detail_items",
        "\"live_memory_feedback_detail_items\":",
    ),
    required_field(
        "auto_replay_live_memory_feedback_applied",
        "\"live_memory_feedback_applied\":",
    ),
    required_field(
        "auto_replay_live_memory_feedback_removed",
        "\"live_memory_feedback_removed\":",
    ),
    required_field(
        "auto_replay_live_memory_feedback_missing",
        "\"live_memory_feedback_missing\":",
    ),
    required_field(
        "auto_replay_live_memory_feedback_strength_delta",
        "\"live_memory_feedback_strength_delta\":",
    ),
    required_field(
        "auto_replay_business_contract_items",
        "\"business_contract_items\":",
    ),
    required_field(
        "auto_replay_business_contract_passed",
        "\"business_contract_passed\":",
    ),
    required_field(
        "auto_replay_business_contract_failed",
        "\"business_contract_failed\":",
    ),
    required_field(
        "auto_replay_business_contract_raw_passed",
        "\"business_contract_raw_passed\":",
    ),
    required_field(
        "auto_replay_business_contract_raw_failed",
        "\"business_contract_raw_failed\":",
    ),
    required_field(
        "auto_replay_business_contract_response_normalized",
        "\"business_contract_response_normalized\":",
    ),
    required_field(
        "auto_replay_business_contract_sanitized",
        "\"business_contract_sanitized\":",
    ),
    required_field(
        "auto_replay_business_contract_canonical_fallbacks",
        "\"business_contract_canonical_fallbacks\":",
    ),
    required_field(
        "auto_replay_live_evolution_items",
        "\"live_evolution_items\":",
    ),
    required_field(
        "auto_replay_live_evolution_online_reward_feedbacks",
        "\"live_evolution_online_reward_feedbacks\":",
    ),
    required_field(
        "auto_replay_live_evolution_online_reward_reinforcements",
        "\"live_evolution_online_reward_reinforcements\":",
    ),
    required_field(
        "auto_replay_live_evolution_online_reward_penalties",
        "\"live_evolution_online_reward_penalties\":",
    ),
    required_field(
        "auto_replay_live_evolution_online_reward_strength",
        "\"live_evolution_online_reward_strength\":",
    ),
    required_field(
        "auto_replay_live_evolution_online_reward_reinforcement_strength",
        "\"live_evolution_online_reward_reinforcement_strength\":",
    ),
    required_field(
        "auto_replay_live_evolution_online_reward_penalty_strength",
        "\"live_evolution_online_reward_penalty_strength\":",
    ),
    required_field(
        "auto_replay_live_evolution_memory_updates",
        "\"live_evolution_memory_updates\":",
    ),
    required_field(
        "auto_replay_live_evolution_stored_memory_updates",
        "\"live_evolution_stored_memory_updates\":",
    ),
    required_field(
        "auto_replay_live_evolution_reflection_issues",
        "\"live_evolution_reflection_issues\":",
    ),
    required_field(
        "auto_replay_live_evolution_critical_reflection_issues",
        "\"live_evolution_critical_reflection_issues\":",
    ),
    required_field(
        "auto_replay_live_evolution_revision_actions",
        "\"live_evolution_revision_actions\":",
    ),
    required_field(
        "auto_replay_recursive_runtime_calls",
        "\"recursive_runtime_calls\":",
    ),
    required_field(
        "auto_replay_recursive_call_pressure",
        "\"max_recursive_call_pressure\":",
    ),
];
