use super::{TraceRequiredField, required_field};

pub(super) const CORE_TRACE_REQUIRED_FIELDS: &[TraceRequiredField] = &[
    required_field("schema", "\"schema\":\"rust-norion-trace-v1\""),
    required_field("case", "\"case\":"),
    required_field("profile", "\"profile\":"),
    required_field("reflection", "\"reflection\":{"),
    required_field("revision_passes", "\"revision_passes\":"),
    required_field("route", "\"route\":{"),
    required_field("runtime_tokens", "\"runtime_tokens\":{"),
    required_field("embedding", "\"embedding\":{"),
    required_field("embedding_query_source", "\"query_source\":"),
    required_field("embedding_runtime_calls", "\"runtime_embedding_calls\":"),
    required_field("runtime_diagnostics", "\"runtime_diagnostics\":{"),
    required_field("runtime_adapter_cache_mode", "\"adapter_cache_mode\":"),
    required_field(
        "runtime_adapter_stream_trace_id",
        "\"adapter_stream_trace_id\":",
    ),
    required_field(
        "runtime_adapter_stream_gate_summary_digest",
        "\"adapter_stream_gate_summary_digest\":",
    ),
    required_field(
        "runtime_adapter_stream_read_only",
        "\"adapter_stream_read_only\":",
    ),
    required_field(
        "runtime_adapter_stream_write_allowed",
        "\"adapter_stream_write_allowed\":",
    ),
    required_field(
        "runtime_adapter_stream_applied",
        "\"adapter_stream_applied\":",
    ),
    required_field("runtime_device_profile", "\"device_profile\":"),
    required_field(
        "runtime_device_execution_source",
        "\"device_execution_source\":",
    ),
    required_field(
        "runtime_hot_kv_precision_bits",
        "\"hot_kv_precision_bits\":",
    ),
    required_field(
        "runtime_cold_kv_precision_bits",
        "\"cold_kv_precision_bits\":",
    ),
    required_field(
        "runtime_kv_precision_signal",
        "\"has_kv_precision_signal\":",
    ),
    required_field(
        "runtime_adapter_observations",
        "\"runtime_adapter_observations\":{",
    ),
    required_field(
        "runtime_adapter_observation_count",
        "\"observation_count\":",
    ),
    required_field("runtime_adapter_best_adapter", "\"best_adapter\":"),
    required_field(
        "runtime_adapter_selection_mismatch",
        "\"selection_mismatch\":",
    ),
    required_field("runtime_adapter_best_score", "\"best_score\":"),
    required_field("forward_energy", "\"forward_energy\":"),
    required_field("kv_influence", "\"kv_influence\":"),
    required_field("uncertainty_perplexity", "\"uncertainty_perplexity\":"),
    required_field("hierarchy", "\"hierarchy\":{"),
    required_field("hardware", "\"hardware\":{"),
    required_field("runtime_device_contract", "\"runtime_device_contract\":"),
    required_field("adapter_hints", "\"adapter_hints\":"),
    required_field("hot_kv_bits", "\"hot_kv_bits\":"),
    required_field("cold_kv_bits", "\"cold_kv_bits\":"),
    required_field("local_kv_token_budget", "\"local_kv_token_budget\":"),
    required_field("global_kv_token_budget", "\"global_kv_token_budget\":"),
    required_field("runtime_budget", "\"runtime_budget\":{"),
    required_field("runtime_budget_selected_device", "\"selected_device\":"),
    required_field(
        "runtime_budget_quantization_profile",
        "\"quantization_profile\":",
    ),
    required_field("runtime_budget_fallback_reason", "\"fallback_reason\":"),
    required_field(
        "runtime_budget_fail_closed_cpu_stub",
        "\"fail_closed_cpu_stub\":",
    ),
    required_field("recursive", "\"recursive\":{"),
    required_field("execution_waves", "\"execution_waves\":"),
    required_field("recursive_runtime_calls", "\"runtime_calls\":"),
    required_field("tiers", "\"tiers\":{"),
    required_field("infini_memory", "\"infini_memory\":{"),
    required_field("infini_local_window", "\"local_window\":"),
    required_field("infini_global_memory", "\"global_memory\":"),
    required_field("infini_sparse_skipped", "\"sparse_skipped\":"),
    required_field("infini_skipped_tokens", "\"skipped_tokens\":"),
    required_field("transformer", "\"transformer\":{"),
    required_field("toolsmith", "\"toolsmith\":{"),
    required_field("toolsmith_blueprints", "\"blueprint_summaries\":"),
    required_field("toolsmith_gate", "\"gate_passed\":"),
    required_field("agent_team", "\"agent_team\":{"),
    required_field("agent_team_isolation", "\"isolation\":{"),
    required_field("agent_team_messages", "\"messages\":"),
    required_field("agent_team_conflicts", "\"conflicts\":"),
    required_field("agent_team_evolution", "\"evolution_signals\":"),
    required_field("agent_team_collision_free", "\"collision_free\":"),
    required_field("agent_team_aggregation", "\"aggregation\":{"),
    required_field("agent_team_budget_scope", "\"budget_scope\":"),
    required_field("agent_team_main_thread_writer", "\"main_thread_writer\":"),
];
