use super::{TraceRequiredField, required_field};

pub(super) const EVOLUTION_LEDGER_TRACE_REQUIRED_FIELDS: &[TraceRequiredField] = &[
    required_field("evolution_ledger", "\"evolution_ledger\":{"),
    required_field("evolution_replay_runs", "\"replay_runs\":"),
    required_field("evolution_live_inference_runs", "\"live_inference_runs\":"),
    required_field(
        "evolution_live_router_threshold_mutations",
        "\"cumulative_live_router_threshold_mutations\":",
    ),
    required_field(
        "evolution_live_hierarchy_weight_mutations",
        "\"cumulative_live_hierarchy_weight_mutations\":",
    ),
    required_field(
        "evolution_live_router_threshold_delta",
        "\"cumulative_live_router_threshold_delta\":",
    ),
    required_field(
        "evolution_live_hierarchy_weight_delta",
        "\"cumulative_live_hierarchy_weight_delta\":",
    ),
    required_field(
        "evolution_live_online_reward_feedbacks",
        "\"cumulative_live_online_reward_feedbacks\":",
    ),
    required_field(
        "evolution_live_online_reward_reinforcements",
        "\"cumulative_live_online_reward_reinforcements\":",
    ),
    required_field(
        "evolution_live_online_reward_penalties",
        "\"cumulative_live_online_reward_penalties\":",
    ),
    required_field(
        "evolution_live_online_reward_strength",
        "\"cumulative_live_online_reward_strength\":",
    ),
    required_field(
        "evolution_live_online_reward_reinforcement_strength",
        "\"cumulative_live_online_reward_reinforcement_strength\":",
    ),
    required_field(
        "evolution_live_online_reward_penalty_strength",
        "\"cumulative_live_online_reward_penalty_strength\":",
    ),
    required_field(
        "evolution_live_memory_reinforcements",
        "\"cumulative_live_memory_reinforcements\":",
    ),
    required_field(
        "evolution_live_memory_penalties",
        "\"cumulative_live_memory_penalties\":",
    ),
    required_field(
        "evolution_live_memory_updates",
        "\"cumulative_live_memory_updates\":",
    ),
    required_field(
        "evolution_live_stored_memories",
        "\"cumulative_live_stored_memories\":",
    ),
    required_field(
        "evolution_live_stored_gist_memories",
        "\"cumulative_live_stored_gist_memories\":",
    ),
    required_field(
        "evolution_live_stored_runtime_kv_memories",
        "\"cumulative_live_stored_runtime_kv_memories\":",
    ),
    required_field(
        "evolution_live_stored_memory_updates",
        "\"cumulative_live_stored_memory_updates\":",
    ),
    required_field(
        "evolution_live_reflection_issues",
        "\"cumulative_live_reflection_issues\":",
    ),
    required_field(
        "evolution_live_critical_reflection_issues",
        "\"cumulative_live_critical_reflection_issues\":",
    ),
    required_field(
        "evolution_live_revision_actions",
        "\"cumulative_live_revision_actions\":",
    ),
    required_field(
        "evolution_router_threshold_mutations",
        "\"cumulative_router_threshold_mutations\":",
    ),
    required_field(
        "evolution_hierarchy_weight_mutations",
        "\"cumulative_hierarchy_weight_mutations\":",
    ),
    required_field("evolution_memory_updates", "\"cumulative_memory_updates\":"),
    required_field(
        "evolution_replay_live_memory_feedback_updates",
        "\"cumulative_replay_live_memory_feedback_updates\":",
    ),
    required_field(
        "evolution_replay_live_memory_feedback_detail_items",
        "\"cumulative_replay_live_memory_feedback_detail_items\":",
    ),
    required_field(
        "evolution_replay_live_memory_feedback_applied",
        "\"cumulative_replay_live_memory_feedback_applied\":",
    ),
    required_field(
        "evolution_replay_live_memory_feedback_removed",
        "\"cumulative_replay_live_memory_feedback_removed\":",
    ),
    required_field(
        "evolution_replay_live_memory_feedback_missing",
        "\"cumulative_replay_live_memory_feedback_missing\":",
    ),
    required_field(
        "evolution_replay_live_memory_feedback_strength_delta",
        "\"cumulative_replay_live_memory_feedback_strength_delta\":",
    ),
    required_field(
        "evolution_replay_business_contract_items",
        "\"cumulative_replay_business_contract_items\":",
    ),
    required_field(
        "evolution_replay_business_contract_passed",
        "\"cumulative_replay_business_contract_passed\":",
    ),
    required_field(
        "evolution_replay_business_contract_failed",
        "\"cumulative_replay_business_contract_failed\":",
    ),
    required_field(
        "evolution_replay_business_contract_raw_passed",
        "\"cumulative_replay_business_contract_raw_passed\":",
    ),
    required_field(
        "evolution_replay_business_contract_raw_failed",
        "\"cumulative_replay_business_contract_raw_failed\":",
    ),
    required_field(
        "evolution_replay_business_contract_response_normalized",
        "\"cumulative_replay_business_contract_response_normalized\":",
    ),
    required_field(
        "evolution_replay_business_contract_sanitized",
        "\"cumulative_replay_business_contract_sanitized\":",
    ),
    required_field(
        "evolution_replay_business_contract_canonical_fallbacks",
        "\"cumulative_replay_business_contract_canonical_fallbacks\":",
    ),
    required_field(
        "evolution_replay_live_evolution_items",
        "\"cumulative_replay_live_evolution_items\":",
    ),
    required_field(
        "evolution_replay_live_evolution_online_reward_feedbacks",
        "\"cumulative_replay_live_evolution_online_reward_feedbacks\":",
    ),
    required_field(
        "evolution_replay_live_evolution_online_reward_reinforcements",
        "\"cumulative_replay_live_evolution_online_reward_reinforcements\":",
    ),
    required_field(
        "evolution_replay_live_evolution_online_reward_penalties",
        "\"cumulative_replay_live_evolution_online_reward_penalties\":",
    ),
    required_field(
        "evolution_replay_live_evolution_online_reward_strength",
        "\"cumulative_replay_live_evolution_online_reward_strength\":",
    ),
    required_field(
        "evolution_replay_live_evolution_online_reward_reinforcement_strength",
        "\"cumulative_replay_live_evolution_online_reward_reinforcement_strength\":",
    ),
    required_field(
        "evolution_replay_live_evolution_online_reward_penalty_strength",
        "\"cumulative_replay_live_evolution_online_reward_penalty_strength\":",
    ),
    required_field(
        "evolution_replay_live_evolution_memory_updates",
        "\"cumulative_replay_live_evolution_memory_updates\":",
    ),
    required_field(
        "evolution_replay_live_evolution_stored_memory_updates",
        "\"cumulative_replay_live_evolution_stored_memory_updates\":",
    ),
    required_field(
        "evolution_replay_live_evolution_reflection_issues",
        "\"cumulative_replay_live_evolution_reflection_issues\":",
    ),
    required_field(
        "evolution_replay_live_evolution_critical_reflection_issues",
        "\"cumulative_replay_live_evolution_critical_reflection_issues\":",
    ),
    required_field(
        "evolution_replay_live_evolution_revision_actions",
        "\"cumulative_replay_live_evolution_revision_actions\":",
    ),
    required_field(
        "evolution_recursive_runtime_calls",
        "\"cumulative_recursive_runtime_calls\":",
    ),
    required_field(
        "evolution_drift_rollbacks",
        "\"cumulative_drift_rollbacks\":",
    ),
    required_field(
        "evolution_rollback_router_threshold_delta",
        "\"cumulative_rollback_router_threshold_delta\":",
    ),
    required_field(
        "evolution_rollback_hierarchy_weight_delta",
        "\"cumulative_rollback_hierarchy_weight_delta\":",
    ),
];
