use super::{TraceRequiredField, required_field};

pub(super) const ROUTING_TRACE_REQUIRED_FIELDS: &[TraceRequiredField] = &[
    required_field("adaptive_routing", "\"adaptive_routing\":{"),
    required_field("adaptive_routing_candidates", "\"candidates\":"),
    required_field("adaptive_routing_include", "\"include\":"),
    required_field("adaptive_routing_compress", "\"compress\":"),
    required_field("adaptive_routing_defer", "\"defer\":"),
    required_field("adaptive_routing_skip", "\"skip\":"),
    required_field("adaptive_routing_input_tokens", "\"input_tokens\":"),
    required_field("adaptive_routing_retained_tokens", "\"retained_tokens\":"),
    required_field("adaptive_routing_saved_tokens", "\"saved_tokens\":"),
    required_field("adaptive_routing_min_score", "\"min_score\":"),
    required_field("adaptive_routing_max_score", "\"max_score\":"),
    required_field("adaptive_routing_average_score", "\"average_score\":"),
    required_field("adaptive_routing_actions", "\"actions\":"),
    required_field("adaptive_routing_selected_routes", "\"selected_routes\":"),
    required_field("adaptive_routing_score_summaries", "\"score_summaries\":"),
    required_field("adaptive_routing_read_only", "\"read_only\":"),
    required_field("adaptive_routing_write_allowed", "\"write_allowed\":"),
    required_field("adaptive_routing_applied", "\"applied\":"),
    required_field("task_hierarchy", "\"task_hierarchy\":{"),
    required_field("task_hierarchy_mode", "\"mode\":"),
    required_field("task_hierarchy_language", "\"language\":"),
    required_field("task_hierarchy_compute_budget", "\"compute_budget\":"),
    required_field("task_hierarchy_depth", "\"hierarchy_depth\":"),
    required_field("task_hierarchy_route_fanout", "\"route_fanout\":"),
    required_field("task_hierarchy_route_pressure", "\"route_pressure\":"),
    required_field("task_hierarchy_compute_reduction", "\"compute_reduction\":"),
    required_field("task_hierarchy_threshold_before", "\"threshold_before\":"),
    required_field("task_hierarchy_threshold_after", "\"threshold_after\":"),
    required_field("task_hierarchy_selected_lanes", "\"selected_lanes\":"),
    required_field("task_hierarchy_memory_lanes", "\"memory_lanes\":"),
    required_field("task_hierarchy_mutation_records", "\"mutation_records\":"),
    required_field(
        "task_hierarchy_mutation_summaries",
        "\"mutation_summaries\":",
    ),
    required_field("task_hierarchy_rollback_anchor", "\"rollback_anchor_id\":"),
    required_field("task_hierarchy_replayable", "\"replayable\":"),
    required_field("task_hierarchy_runtime_applied", "\"runtime_applied\":"),
    required_field(
        "task_hierarchy_state_write_allowed",
        "\"state_write_allowed\":",
    ),
];
