use std::path::PathBuf;

use rust_norion::{
    CommandPromptMode, CommandWireFormat, DeviceClass, GemmaRuntimeQuantizationMode,
    HardwareProbeReport, RuntimeMetadata, TaskProfile,
};

#[derive(Debug, Clone)]
pub(crate) struct Args {
    pub(crate) prompt: String,
    pub(crate) profile: TaskProfile,
    pub(crate) max_tokens: Option<usize>,
    pub(crate) memory_path: PathBuf,
    pub(crate) experience_path: PathBuf,
    pub(crate) adaptive_path: PathBuf,
    pub(crate) trace_path: Option<PathBuf>,
    pub(crate) trace_schema_gate_path: Option<PathBuf>,
    pub(crate) self_goal_queue: bool,
    pub(crate) self_goal_queue_store_path: Option<PathBuf>,
    pub(crate) self_goal_queue_store_apply: bool,
    pub(crate) self_goal_queue_evidence_packets: Vec<String>,
    pub(crate) self_goal_queue_evidence_path: Option<PathBuf>,
    pub(crate) self_goal_queue_local_evidence: bool,
    pub(crate) self_goal_queue_local_evidence_dry_run: bool,
    pub(crate) self_goal_queue_tenant: String,
    pub(crate) self_goal_queue_workspace: String,
    pub(crate) self_goal_queue_session: String,
    pub(crate) self_goal_queue_key: String,
    pub(crate) self_goal_queue_operator: String,
    pub(crate) self_goal_queue_ticket: String,
    pub(crate) coding_service_eval_readiness: bool,
    pub(crate) coding_service_eval_runner: bool,
    pub(crate) experience_hygiene: bool,
    pub(crate) experience_hygiene_limit: usize,
    pub(crate) experience_hygiene_quarantine: bool,
    pub(crate) experience_hygiene_apply: bool,
    pub(crate) experience_hygiene_quarantine_path: Option<PathBuf>,
    pub(crate) experience_hygiene_backup_path: Option<PathBuf>,
    pub(crate) experience_repair: bool,
    pub(crate) experience_repair_limit: usize,
    pub(crate) experience_repair_apply: bool,
    pub(crate) experience_repair_backup_path: Option<PathBuf>,
    pub(crate) experience_retrieval: bool,
    pub(crate) experience_retrieval_limit: usize,
    pub(crate) experience_cleanup_audit: bool,
    pub(crate) experience_cleanup_audit_limit: usize,
    pub(crate) experience_cleanup_audit_path: Option<PathBuf>,
    pub(crate) experience_index_add_clean_gist: bool,
    pub(crate) experience_index_record_id: Option<u64>,
    pub(crate) experience_index_clean_gist: Option<String>,
    pub(crate) experience_index_clean_gist_title: Option<String>,
    pub(crate) experience_index_clean_gist_importance: f32,
    pub(crate) experience_index_backup_path: Option<PathBuf>,
    pub(crate) benchmark_path: Option<PathBuf>,
    pub(crate) benchmark_all_devices: bool,
    pub(crate) benchmark_gate_enabled: bool,
    pub(crate) benchmark_min_quality: Option<f32>,
    pub(crate) benchmark_min_reward: Option<f32>,
    pub(crate) benchmark_max_total_ms: Option<u128>,
    pub(crate) benchmark_max_recursive_chunks: Option<usize>,
    pub(crate) benchmark_min_recursive_cases: Option<usize>,
    pub(crate) benchmark_min_recursive_runtime_calls: Option<usize>,
    pub(crate) benchmark_min_auto_replay_router_updates: Option<usize>,
    pub(crate) benchmark_min_auto_replay_hierarchy_updates: Option<usize>,
    pub(crate) benchmark_min_auto_replay_router_threshold_mutations: Option<usize>,
    pub(crate) benchmark_min_auto_replay_hierarchy_weight_mutations: Option<usize>,
    pub(crate) benchmark_min_auto_replay_router_threshold_delta: Option<f32>,
    pub(crate) benchmark_min_auto_replay_hierarchy_weight_delta: Option<f32>,
    pub(crate) benchmark_min_auto_replay_memory_updates: Option<usize>,
    pub(crate) benchmark_min_live_memory_feedback_updates: Option<usize>,
    pub(crate) benchmark_min_auto_replay_live_memory_feedback_updates: Option<usize>,
    pub(crate) benchmark_min_auto_replay_live_memory_feedback_detail_items: Option<usize>,
    pub(crate) benchmark_min_auto_replay_live_memory_feedback_applied: Option<usize>,
    pub(crate) benchmark_min_auto_replay_live_memory_feedback_strength_delta: Option<f32>,
    pub(crate) benchmark_min_auto_replay_recursive_items: Option<usize>,
    pub(crate) benchmark_min_auto_replay_recursive_call_pressure: Option<f32>,
    pub(crate) benchmark_max_auto_replay_recursive_call_pressure: Option<f32>,
    pub(crate) benchmark_min_auto_replay_runtime_kv_budget_pressure_items: Option<usize>,
    pub(crate) benchmark_min_auto_replay_runtime_kv_budget_pressure: Option<f32>,
    pub(crate) benchmark_max_auto_replay_runtime_kv_budget_pressure: Option<f32>,
    pub(crate) benchmark_min_evolution_live_inference_runs: Option<u64>,
    pub(crate) benchmark_min_evolution_live_router_threshold_mutations: Option<u64>,
    pub(crate) benchmark_min_evolution_live_hierarchy_weight_mutations: Option<u64>,
    pub(crate) benchmark_min_evolution_live_router_threshold_delta: Option<f32>,
    pub(crate) benchmark_min_evolution_live_hierarchy_weight_delta: Option<f32>,
    pub(crate) benchmark_min_evolution_live_online_reward_feedbacks: Option<u64>,
    pub(crate) benchmark_min_evolution_live_online_reward_reinforcements: Option<u64>,
    pub(crate) benchmark_min_evolution_live_online_reward_penalties: Option<u64>,
    pub(crate) benchmark_min_evolution_live_online_reward_strength: Option<f32>,
    pub(crate) benchmark_min_evolution_live_online_reward_reinforcement_strength: Option<f32>,
    pub(crate) benchmark_min_evolution_live_online_reward_penalty_strength: Option<f32>,
    pub(crate) benchmark_min_evolution_live_memory_updates: Option<u64>,
    pub(crate) benchmark_min_evolution_live_stored_memory_updates: Option<u64>,
    pub(crate) benchmark_min_evolution_live_reflection_issues: Option<u64>,
    pub(crate) benchmark_min_evolution_live_critical_reflection_issues: Option<u64>,
    pub(crate) benchmark_min_evolution_live_revision_actions: Option<u64>,
    pub(crate) benchmark_min_evolution_live_inference_device_profiles: Option<usize>,
    pub(crate) benchmark_min_evolution_live_router_threshold_mutation_device_profiles:
        Option<usize>,
    pub(crate) benchmark_min_evolution_live_hierarchy_weight_mutation_device_profiles:
        Option<usize>,
    pub(crate) benchmark_min_evolution_live_online_reward_device_profiles: Option<usize>,
    pub(crate) benchmark_min_evolution_live_online_reward_strength_device_profiles: Option<usize>,
    pub(crate) benchmark_min_evolution_live_memory_update_device_profiles: Option<usize>,
    pub(crate) benchmark_min_evolution_live_stored_memory_update_device_profiles: Option<usize>,
    pub(crate) benchmark_min_evolution_live_reflection_issue_device_profiles: Option<usize>,
    pub(crate) benchmark_min_evolution_live_critical_reflection_issue_device_profiles:
        Option<usize>,
    pub(crate) benchmark_min_evolution_live_revision_action_device_profiles: Option<usize>,
    pub(crate) benchmark_min_evolution_replay_runs: Option<u64>,
    pub(crate) benchmark_min_evolution_replay_items: Option<u64>,
    pub(crate) benchmark_min_evolution_router_threshold_mutations: Option<u64>,
    pub(crate) benchmark_min_evolution_hierarchy_weight_mutations: Option<u64>,
    pub(crate) benchmark_min_evolution_router_threshold_delta: Option<f32>,
    pub(crate) benchmark_min_evolution_hierarchy_weight_delta: Option<f32>,
    pub(crate) benchmark_min_evolution_memory_updates: Option<u64>,
    pub(crate) benchmark_min_evolution_replay_live_memory_feedback_updates: Option<u64>,
    pub(crate) benchmark_min_evolution_replay_live_memory_feedback_detail_items: Option<u64>,
    pub(crate) benchmark_min_evolution_replay_live_memory_feedback_applied: Option<u64>,
    pub(crate) benchmark_min_evolution_replay_live_memory_feedback_strength_delta: Option<f32>,
    pub(crate) benchmark_min_evolution_replay_rust_check_items: Option<u64>,
    pub(crate) benchmark_min_evolution_replay_rust_check_passed: Option<u64>,
    pub(crate) benchmark_max_evolution_replay_rust_check_failed: Option<u64>,
    pub(crate) benchmark_min_evolution_replay_rust_check_live_memory_feedback_updates: Option<u64>,
    pub(crate) benchmark_min_evolution_replay_rust_check_live_memory_feedback_applied: Option<u64>,
    pub(crate) benchmark_min_evolution_replay_rust_check_live_memory_feedback_strength_delta:
        Option<f32>,
    pub(crate) benchmark_min_evolution_replay_live_evolution_items: Option<u64>,
    pub(crate) benchmark_min_evolution_replay_live_evolution_online_reward_feedbacks: Option<u64>,
    pub(crate) benchmark_min_evolution_replay_live_evolution_online_reward_reinforcements:
        Option<u64>,
    pub(crate) benchmark_min_evolution_replay_live_evolution_online_reward_penalties: Option<u64>,
    pub(crate) benchmark_min_evolution_replay_live_evolution_online_reward_strength: Option<f32>,
    pub(crate) benchmark_min_evolution_replay_live_evolution_online_reward_reinforcement_strength:
        Option<f32>,
    pub(crate) benchmark_min_evolution_replay_live_evolution_online_reward_penalty_strength:
        Option<f32>,
    pub(crate) benchmark_min_evolution_replay_live_evolution_memory_updates: Option<u64>,
    pub(crate) benchmark_min_evolution_replay_live_evolution_stored_memory_updates: Option<u64>,
    pub(crate) benchmark_min_evolution_replay_live_evolution_reflection_issues: Option<u64>,
    pub(crate) benchmark_min_evolution_replay_live_evolution_critical_reflection_issues:
        Option<u64>,
    pub(crate) benchmark_min_evolution_replay_live_evolution_revision_actions: Option<u64>,
    pub(crate) benchmark_min_evolution_replay_live_evolution_device_profiles: Option<usize>,
    pub(crate) benchmark_min_evolution_replay_live_evolution_online_reward_device_profiles:
        Option<usize>,
    pub(crate) benchmark_min_evolution_replay_live_evolution_online_reward_strength_device_profiles:
        Option<usize>,
    pub(crate) benchmark_min_evolution_replay_live_evolution_memory_update_device_profiles:
        Option<usize>,
    pub(crate) benchmark_min_evolution_replay_live_evolution_critical_reflection_issue_device_profiles:
        Option<usize>,
    pub(crate) benchmark_min_evolution_replay_live_evolution_revision_action_device_profiles:
        Option<usize>,
    pub(crate) benchmark_min_evolution_recursive_replay_items: Option<u64>,
    pub(crate) benchmark_min_evolution_recursive_runtime_calls: Option<u64>,
    pub(crate) benchmark_max_evolution_drift_rollbacks: Option<u64>,
    pub(crate) benchmark_max_evolution_rollback_router_threshold_delta: Option<f32>,
    pub(crate) benchmark_max_evolution_rollback_hierarchy_weight_delta: Option<f32>,
    pub(crate) benchmark_min_sparse_skipped_cases: Option<usize>,
    pub(crate) benchmark_min_sparse_skipped_tokens: Option<usize>,
    pub(crate) benchmark_min_runtime_forward_cases: Option<usize>,
    pub(crate) benchmark_min_runtime_forward_energy_cases: Option<usize>,
    pub(crate) benchmark_min_runtime_kv_influence_cases: Option<usize>,
    pub(crate) benchmark_min_runtime_architecture_cases: Option<usize>,
    pub(crate) benchmark_min_runtime_architecture_device_profiles: Option<usize>,
    pub(crate) benchmark_min_runtime_kv_precision_cases: Option<usize>,
    pub(crate) benchmark_min_runtime_layer_mode_cases: Option<usize>,
    pub(crate) benchmark_min_runtime_all_layer_mode_cases: Option<usize>,
    pub(crate) benchmark_min_runtime_global_layers: Option<usize>,
    pub(crate) benchmark_min_runtime_local_window_layers: Option<usize>,
    pub(crate) benchmark_min_runtime_convolutional_fusion_layers: Option<usize>,
    pub(crate) benchmark_min_runtime_uncertainty_cases: Option<usize>,
    pub(crate) benchmark_min_runtime_uncertainty_tokens: Option<usize>,
    pub(crate) benchmark_min_runtime_uncertainty_device_profiles: Option<usize>,
    pub(crate) benchmark_min_runtime_uncertainty_token_device_profiles: Option<usize>,
    pub(crate) benchmark_min_runtime_kv_import_cases: Option<usize>,
    pub(crate) benchmark_min_runtime_kv_weak_import_skip_cases: Option<usize>,
    pub(crate) benchmark_min_weak_runtime_kv_imports_skipped: Option<usize>,
    pub(crate) benchmark_min_runtime_kv_weak_import_skip_device_profiles: Option<usize>,
    pub(crate) benchmark_min_runtime_kv_budget_import_skip_cases: Option<usize>,
    pub(crate) benchmark_min_budget_limited_runtime_kv_imports_skipped: Option<usize>,
    pub(crate) benchmark_min_runtime_kv_budget_import_skip_device_profiles: Option<usize>,
    pub(crate) benchmark_min_runtime_kv_segment_cases: Option<usize>,
    pub(crate) benchmark_min_runtime_kv_segments_included: Option<usize>,
    pub(crate) benchmark_max_runtime_kv_segments_rejected: Option<usize>,
    pub(crate) benchmark_min_runtime_kv_segment_device_profiles: Option<usize>,
    pub(crate) benchmark_min_runtime_kv_imported: Option<usize>,
    pub(crate) benchmark_min_runtime_kv_import_device_profiles: Option<usize>,
    pub(crate) benchmark_min_runtime_kv_exported: Option<usize>,
    pub(crate) benchmark_min_runtime_kv_export_device_profiles: Option<usize>,
    pub(crate) benchmark_min_runtime_kv_stored: Option<usize>,
    pub(crate) benchmark_min_runtime_kv_stored_device_profiles: Option<usize>,
    pub(crate) benchmark_min_runtime_kv_hold_cases: Option<usize>,
    pub(crate) benchmark_min_runtime_kv_held: Option<usize>,
    pub(crate) benchmark_min_runtime_kv_hold_device_profiles: Option<usize>,
    pub(crate) benchmark_min_runtime_adapter_contract_cases: Option<usize>,
    pub(crate) benchmark_min_runtime_adapter_kinds: Option<usize>,
    pub(crate) benchmark_min_runtime_adapter_cache_modes: Option<usize>,
    pub(crate) benchmark_min_runtime_adapter_stream_trace_cases: Option<usize>,
    pub(crate) benchmark_min_runtime_adapter_stream_gate_summary_cases: Option<usize>,
    pub(crate) benchmark_min_runtime_adapter_observations: Option<usize>,
    pub(crate) benchmark_min_runtime_adapter_current_signals: Option<usize>,
    pub(crate) benchmark_min_runtime_adapter_best_score: Option<f32>,
    pub(crate) benchmark_max_runtime_adapter_contract_violations: Option<usize>,
    pub(crate) benchmark_max_runtime_adapter_selection_mismatches: Option<usize>,
    pub(crate) benchmark_min_runtime_embedding_cases: Option<usize>,
    pub(crate) benchmark_min_runtime_embedding_device_profiles: Option<usize>,
    pub(crate) benchmark_max_embedding_fallback_cases: Option<usize>,
    pub(crate) benchmark_max_embedding_evidence_failures: Option<usize>,
    pub(crate) benchmark_min_runtime_device_execution_cases: Option<usize>,
    pub(crate) benchmark_min_runtime_device_execution_device_profiles: Option<usize>,
    pub(crate) benchmark_min_runtime_kv_precision_device_profiles: Option<usize>,
    pub(crate) benchmark_max_runtime_device_execution_violations: Option<usize>,
    pub(crate) benchmark_max_memory_governance_failures: Option<usize>,
    pub(crate) benchmark_min_reasoning_genome_expression_cases: Option<usize>,
    pub(crate) benchmark_min_reasoning_genome_expression_device_profiles: Option<usize>,
    pub(crate) benchmark_min_reasoning_genome_splice_cases: Option<usize>,
    pub(crate) benchmark_min_reasoning_genome_splice_device_profiles: Option<usize>,
    pub(crate) benchmark_min_gene_scissors_proposal_cases: Option<usize>,
    pub(crate) benchmark_min_gene_scissors_proposal_device_profiles: Option<usize>,
    pub(crate) benchmark_min_reasoning_genome_repair_payloads: Option<usize>,
    pub(crate) benchmark_min_reasoning_genome_regeneration_payloads: Option<usize>,
    pub(crate) benchmark_min_mutation_repair_fixtures: Option<usize>,
    pub(crate) benchmark_min_mutation_repair_fixture_kinds: Option<usize>,
    pub(crate) benchmark_min_mutation_repair_candidates: Option<usize>,
    pub(crate) benchmark_min_mutation_repair_review_packets: Option<usize>,
    pub(crate) benchmark_min_malignant_gene_recovery_drills: Option<usize>,
    pub(crate) benchmark_min_malignant_gene_quarantines: Option<usize>,
    pub(crate) benchmark_min_malignant_gene_cut_candidates: Option<usize>,
    pub(crate) benchmark_min_malignant_gene_regeneration_candidates: Option<usize>,
    pub(crate) benchmark_min_dna_evolution_reports: Option<usize>,
    pub(crate) benchmark_min_dna_evolution_candidates: Option<usize>,
    pub(crate) benchmark_min_dna_evolution_candidate_previews: Option<usize>,
    pub(crate) benchmark_max_dna_evolution_activation_eligible: Option<usize>,
    pub(crate) benchmark_min_dna_evolution_transaction_replays: Option<usize>,
    pub(crate) benchmark_min_dna_evolution_replay_passed: Option<usize>,
    pub(crate) benchmark_min_dna_evolution_validation_passed: Option<usize>,
    pub(crate) benchmark_min_dna_evolution_writer_gate_reports: Option<usize>,
    pub(crate) benchmark_min_dna_evolution_writer_gate_holds: Option<usize>,
    pub(crate) benchmark_min_dna_evolution_writer_gate_explicit_apply_required: Option<usize>,
    pub(crate) benchmark_max_dna_evolution_writer_gate_ready: Option<usize>,
    pub(crate) benchmark_max_dna_evolution_writer_gate_durable_write_allowed: Option<usize>,
    pub(crate) benchmark_min_memory_governance_cases: Option<usize>,
    pub(crate) benchmark_min_memory_governance_device_profiles: Option<usize>,
    pub(crate) benchmark_min_memory_retention_activity_cases: Option<usize>,
    pub(crate) benchmark_min_memory_compaction_activity_cases: Option<usize>,
    pub(crate) benchmark_min_reflection_issue_cases: Option<usize>,
    pub(crate) benchmark_min_reflection_issues: Option<usize>,
    pub(crate) benchmark_min_critical_reflection_issue_cases: Option<usize>,
    pub(crate) benchmark_min_critical_reflection_issues: Option<usize>,
    pub(crate) benchmark_min_revision_action_cases: Option<usize>,
    pub(crate) benchmark_min_revision_actions: Option<usize>,
    pub(crate) benchmark_min_reflection_issue_device_profiles: Option<usize>,
    pub(crate) benchmark_min_critical_reflection_issue_device_profiles: Option<usize>,
    pub(crate) benchmark_min_revision_action_device_profiles: Option<usize>,
    pub(crate) benchmark_min_device_profiles: Option<usize>,
    pub(crate) benchmark_min_recursive_device_profiles: Option<usize>,
    pub(crate) benchmark_max_drift_blocks: Option<usize>,
    pub(crate) benchmark_max_drift_rollbacks: Option<usize>,
    pub(crate) benchmark_roundtrip: bool,
    pub(crate) serve: bool,
    pub(crate) serve_bind: String,
    pub(crate) serve_max_requests: Option<usize>,
    pub(crate) model_pool_manifest_path: Option<PathBuf>,
    pub(crate) list_devices: bool,
    pub(crate) probe_device: bool,
    pub(crate) device_gate: bool,
    pub(crate) kv_quant_gate: bool,
    pub(crate) kv_quant_max_total_us: Option<u128>,
    pub(crate) runtime_manifest_gate: bool,
    pub(crate) runtime_manifest_all_devices_gate: bool,
    pub(crate) runtime_weights_path: Option<PathBuf>,
    pub(crate) runtime_tokenizer_path: Option<PathBuf>,
    pub(crate) runtime_config_path: Option<PathBuf>,
    pub(crate) runtime_layer_count: Option<usize>,
    pub(crate) runtime_hidden_size: Option<usize>,
    pub(crate) runtime_attention_heads: Option<usize>,
    pub(crate) runtime_kv_heads: Option<usize>,
    pub(crate) runtime_local_window_tokens: Option<usize>,
    pub(crate) runtime_timeout_ms: Option<u64>,
    pub(crate) runtime_stream_idle_timeout_ms: Option<u64>,
    pub(crate) inspect_state: bool,
    pub(crate) inspect_limit: usize,
    pub(crate) inspect_gate: bool,
    pub(crate) inspect_min_memories: Option<usize>,
    pub(crate) inspect_min_runtime_kv_memories: Option<usize>,
    pub(crate) inspect_min_experiences: Option<usize>,
    pub(crate) inspect_max_experience_hygiene_quarantine_candidates: Option<usize>,
    pub(crate) inspect_max_experience_repairable_legacy_metadata_lessons: Option<usize>,
    pub(crate) inspect_max_experience_repairable_index_records: Option<usize>,
    pub(crate) inspect_max_experience_repair_projected_legacy_metadata_lessons: Option<usize>,
    pub(crate) inspect_max_experience_repair_skipped_missing_clean_gist: Option<usize>,
    pub(crate) inspect_max_experience_index_overlong_records: Option<usize>,
    pub(crate) inspect_max_experience_index_overlong_without_clean_gist: Option<usize>,
    pub(crate) inspect_max_experience_index_record_chars: Option<usize>,
    pub(crate) inspect_max_experience_index_noisy_records: Option<usize>,
    pub(crate) inspect_max_experience_index_noise_penalty: Option<f32>,
    pub(crate) inspect_min_experience_index_quality_score: Option<f32>,
    pub(crate) inspect_require_experience_index_retrieval_ready: bool,
    pub(crate) inspect_min_runtime_model_experiences: Option<usize>,
    pub(crate) inspect_min_runtime_adapter_experiences: Option<usize>,
    pub(crate) inspect_max_runtime_adapter_selection_mismatches: Option<usize>,
    pub(crate) inspect_min_runtime_forward_energy_experiences: Option<usize>,
    pub(crate) inspect_min_runtime_kv_influence_experiences: Option<usize>,
    pub(crate) inspect_min_runtime_tokens: Option<usize>,
    pub(crate) inspect_min_runtime_uncertainty_experiences: Option<usize>,
    pub(crate) inspect_min_runtime_uncertainty_tokens: Option<usize>,
    pub(crate) inspect_min_runtime_architecture_experiences: Option<usize>,
    pub(crate) inspect_min_runtime_kv_precision_experiences: Option<usize>,
    pub(crate) inspect_max_runtime_kv_precision_mismatches: Option<usize>,
    pub(crate) inspect_max_runtime_errors: Option<usize>,
    pub(crate) inspect_max_runtime_timeouts: Option<usize>,
    pub(crate) inspect_min_runtime_device_execution_experiences: Option<usize>,
    pub(crate) inspect_min_runtime_layer_mode_experiences: Option<usize>,
    pub(crate) inspect_min_runtime_all_layer_mode_experiences: Option<usize>,
    pub(crate) inspect_min_runtime_global_layers: Option<usize>,
    pub(crate) inspect_min_runtime_local_window_layers: Option<usize>,
    pub(crate) inspect_min_runtime_convolutional_fusion_layers: Option<usize>,
    pub(crate) inspect_min_runtime_kv_import_experiences: Option<usize>,
    pub(crate) inspect_min_runtime_kv_weak_import_skip_experiences: Option<usize>,
    pub(crate) inspect_min_weak_runtime_kv_imports_skipped: Option<usize>,
    pub(crate) inspect_min_runtime_kv_budget_import_skip_experiences: Option<usize>,
    pub(crate) inspect_min_budget_limited_runtime_kv_imports_skipped: Option<usize>,
    pub(crate) inspect_min_runtime_kv_export_experiences: Option<usize>,
    pub(crate) inspect_min_runtime_kv_segment_experiences: Option<usize>,
    pub(crate) inspect_min_runtime_kv_segments_included: Option<usize>,
    pub(crate) inspect_max_runtime_kv_segments_rejected: Option<usize>,
    pub(crate) inspect_min_runtime_kv_hold_experiences: Option<usize>,
    pub(crate) inspect_min_runtime_kv_held_blocks: Option<usize>,
    pub(crate) inspect_min_runtime_kv_memory_device_profiles: Option<usize>,
    pub(crate) inspect_min_runtime_model_device_profiles: Option<usize>,
    pub(crate) inspect_min_runtime_adapter_device_profiles: Option<usize>,
    pub(crate) inspect_min_runtime_forward_energy_device_profiles: Option<usize>,
    pub(crate) inspect_min_runtime_kv_influence_device_profiles: Option<usize>,
    pub(crate) inspect_min_runtime_uncertainty_device_profiles: Option<usize>,
    pub(crate) inspect_min_runtime_uncertainty_token_device_profiles: Option<usize>,
    pub(crate) inspect_min_runtime_kv_precision_device_profiles: Option<usize>,
    pub(crate) inspect_min_runtime_device_execution_device_profiles: Option<usize>,
    pub(crate) inspect_min_runtime_layer_mode_device_profiles: Option<usize>,
    pub(crate) inspect_min_runtime_all_layer_mode_device_profiles: Option<usize>,
    pub(crate) inspect_min_runtime_kv_import_device_profiles: Option<usize>,
    pub(crate) inspect_min_runtime_kv_weak_import_skip_device_profiles: Option<usize>,
    pub(crate) inspect_min_runtime_kv_budget_import_skip_device_profiles: Option<usize>,
    pub(crate) inspect_min_runtime_kv_export_device_profiles: Option<usize>,
    pub(crate) inspect_min_runtime_kv_segment_device_profiles: Option<usize>,
    pub(crate) inspect_min_runtime_kv_hold_device_profiles: Option<usize>,
    pub(crate) inspect_min_reflection_issue_experiences: Option<usize>,
    pub(crate) inspect_min_critical_reflection_issue_experiences: Option<usize>,
    pub(crate) inspect_min_revision_action_experiences: Option<usize>,
    pub(crate) inspect_min_live_memory_feedback_experiences: Option<usize>,
    pub(crate) inspect_min_live_memory_feedback_updates: Option<usize>,
    pub(crate) inspect_min_live_memory_feedback_detail_experiences: Option<usize>,
    pub(crate) inspect_min_live_memory_feedback_applied: Option<usize>,
    pub(crate) inspect_min_live_memory_feedback_strength_delta: Option<f32>,
    pub(crate) inspect_min_rust_check_experiences: Option<usize>,
    pub(crate) inspect_min_rust_check_passed: Option<usize>,
    pub(crate) inspect_max_rust_check_failed: Option<usize>,
    pub(crate) inspect_min_rust_check_diagnostic_chars: Option<usize>,
    pub(crate) inspect_min_reflection_issue_device_profiles: Option<usize>,
    pub(crate) inspect_min_critical_reflection_issue_device_profiles: Option<usize>,
    pub(crate) inspect_min_revision_action_device_profiles: Option<usize>,
    pub(crate) inspect_min_live_memory_feedback_device_profiles: Option<usize>,
    pub(crate) inspect_min_evolution_live_inference_device_profiles: Option<usize>,
    pub(crate) inspect_min_evolution_live_router_threshold_mutation_device_profiles: Option<usize>,
    pub(crate) inspect_min_evolution_live_hierarchy_weight_mutation_device_profiles: Option<usize>,
    pub(crate) inspect_min_evolution_live_online_reward_device_profiles: Option<usize>,
    pub(crate) inspect_min_evolution_live_online_reward_strength_device_profiles: Option<usize>,
    pub(crate) inspect_min_evolution_live_memory_update_device_profiles: Option<usize>,
    pub(crate) inspect_min_evolution_live_stored_memory_update_device_profiles: Option<usize>,
    pub(crate) inspect_min_evolution_live_reflection_issue_device_profiles: Option<usize>,
    pub(crate) inspect_min_evolution_live_critical_reflection_issue_device_profiles: Option<usize>,
    pub(crate) inspect_min_evolution_live_revision_action_device_profiles: Option<usize>,
    pub(crate) inspect_min_evolution_replay_run_device_profiles: Option<usize>,
    pub(crate) inspect_min_evolution_replay_item_device_profiles: Option<usize>,
    pub(crate) inspect_min_evolution_router_threshold_mutation_device_profiles: Option<usize>,
    pub(crate) inspect_min_evolution_hierarchy_weight_mutation_device_profiles: Option<usize>,
    pub(crate) inspect_min_evolution_memory_update_device_profiles: Option<usize>,
    pub(crate) inspect_min_evolution_replay_live_memory_feedback_device_profiles: Option<usize>,
    pub(crate) inspect_min_evolution_replay_live_memory_feedback_detail_device_profiles:
        Option<usize>,
    pub(crate) inspect_min_evolution_replay_live_evolution_device_profiles: Option<usize>,
    pub(crate) inspect_min_evolution_replay_live_evolution_online_reward_device_profiles:
        Option<usize>,
    pub(crate) inspect_min_evolution_replay_live_evolution_online_reward_strength_device_profiles:
        Option<usize>,
    pub(crate) inspect_min_evolution_replay_live_evolution_memory_update_device_profiles:
        Option<usize>,
    pub(crate) inspect_min_evolution_replay_live_evolution_critical_reflection_issue_device_profiles:
        Option<usize>,
    pub(crate) inspect_min_evolution_replay_live_evolution_revision_action_device_profiles:
        Option<usize>,
    pub(crate) inspect_min_evolution_recursive_replay_device_profiles: Option<usize>,
    pub(crate) inspect_min_evolution_recursive_runtime_call_device_profiles: Option<usize>,
    pub(crate) inspect_min_router_observations: Option<u64>,
    pub(crate) inspect_min_evolution_live_inference_runs: Option<u64>,
    pub(crate) inspect_min_evolution_live_router_threshold_mutations: Option<u64>,
    pub(crate) inspect_min_evolution_live_hierarchy_weight_mutations: Option<u64>,
    pub(crate) inspect_min_evolution_live_router_threshold_delta: Option<f32>,
    pub(crate) inspect_min_evolution_live_hierarchy_weight_delta: Option<f32>,
    pub(crate) inspect_min_evolution_live_online_reward_feedbacks: Option<u64>,
    pub(crate) inspect_min_evolution_live_online_reward_reinforcements: Option<u64>,
    pub(crate) inspect_min_evolution_live_online_reward_penalties: Option<u64>,
    pub(crate) inspect_min_evolution_live_online_reward_strength: Option<f32>,
    pub(crate) inspect_min_evolution_live_online_reward_reinforcement_strength: Option<f32>,
    pub(crate) inspect_min_evolution_live_online_reward_penalty_strength: Option<f32>,
    pub(crate) inspect_min_evolution_live_memory_updates: Option<u64>,
    pub(crate) inspect_min_evolution_live_stored_memory_updates: Option<u64>,
    pub(crate) inspect_min_evolution_live_reflection_issues: Option<u64>,
    pub(crate) inspect_min_evolution_live_critical_reflection_issues: Option<u64>,
    pub(crate) inspect_min_evolution_live_revision_actions: Option<u64>,
    pub(crate) inspect_min_evolution_replay_runs: Option<u64>,
    pub(crate) inspect_min_evolution_replay_items: Option<u64>,
    pub(crate) inspect_min_evolution_router_threshold_mutations: Option<u64>,
    pub(crate) inspect_min_evolution_hierarchy_weight_mutations: Option<u64>,
    pub(crate) inspect_min_evolution_router_threshold_delta: Option<f32>,
    pub(crate) inspect_min_evolution_hierarchy_weight_delta: Option<f32>,
    pub(crate) inspect_min_evolution_memory_updates: Option<u64>,
    pub(crate) inspect_min_evolution_external_feedbacks: Option<u64>,
    pub(crate) inspect_min_evolution_external_feedback_memory_updates: Option<u64>,
    pub(crate) inspect_min_evolution_external_feedback_strength_delta: Option<f32>,
    pub(crate) inspect_min_evolution_replay_live_memory_feedback_updates: Option<u64>,
    pub(crate) inspect_min_evolution_replay_live_memory_feedback_detail_items: Option<u64>,
    pub(crate) inspect_min_evolution_replay_live_memory_feedback_applied: Option<u64>,
    pub(crate) inspect_min_evolution_replay_live_memory_feedback_strength_delta: Option<f32>,
    pub(crate) inspect_min_evolution_replay_rust_check_items: Option<u64>,
    pub(crate) inspect_min_evolution_replay_rust_check_passed: Option<u64>,
    pub(crate) inspect_max_evolution_replay_rust_check_failed: Option<u64>,
    pub(crate) inspect_min_evolution_replay_rust_check_live_memory_feedback_updates: Option<u64>,
    pub(crate) inspect_min_evolution_replay_rust_check_live_memory_feedback_applied: Option<u64>,
    pub(crate) inspect_min_evolution_replay_rust_check_live_memory_feedback_strength_delta:
        Option<f32>,
    pub(crate) inspect_min_evolution_replay_live_evolution_items: Option<u64>,
    pub(crate) inspect_min_evolution_replay_live_evolution_online_reward_feedbacks: Option<u64>,
    pub(crate) inspect_min_evolution_replay_live_evolution_online_reward_reinforcements:
        Option<u64>,
    pub(crate) inspect_min_evolution_replay_live_evolution_online_reward_penalties: Option<u64>,
    pub(crate) inspect_min_evolution_replay_live_evolution_online_reward_strength: Option<f32>,
    pub(crate) inspect_min_evolution_replay_live_evolution_online_reward_reinforcement_strength:
        Option<f32>,
    pub(crate) inspect_min_evolution_replay_live_evolution_online_reward_penalty_strength:
        Option<f32>,
    pub(crate) inspect_min_evolution_replay_live_evolution_memory_updates: Option<u64>,
    pub(crate) inspect_min_evolution_replay_live_evolution_stored_memory_updates: Option<u64>,
    pub(crate) inspect_min_evolution_replay_live_evolution_reflection_issues: Option<u64>,
    pub(crate) inspect_min_evolution_replay_live_evolution_critical_reflection_issues: Option<u64>,
    pub(crate) inspect_min_evolution_replay_live_evolution_revision_actions: Option<u64>,
    pub(crate) inspect_min_evolution_recursive_replay_items: Option<u64>,
    pub(crate) inspect_min_evolution_recursive_runtime_calls: Option<u64>,
    pub(crate) inspect_max_evolution_drift_rollbacks: Option<u64>,
    pub(crate) inspect_max_evolution_rollback_router_threshold_delta: Option<f32>,
    pub(crate) inspect_max_evolution_rollback_hierarchy_weight_delta: Option<f32>,
    pub(crate) inspect_require_runtime_kv_dimensions: bool,
    pub(crate) local_runtime: bool,
    pub(crate) production_runtime: bool,
    pub(crate) production_reference_kernel: bool,
    pub(crate) production_local_kernel: bool,
    pub(crate) production_kernel_conformance_gate: bool,
    pub(crate) production_kernel_conformance_all_devices_gate: bool,
    pub(crate) gemma_business_smoke: bool,
    pub(crate) gemma_business_cycle_smoke: bool,
    pub(crate) gemma_business_regression_gate_path: Option<PathBuf>,
    pub(crate) gemma_business_cycle_smoke_report_gate_path: Option<PathBuf>,
    pub(crate) gemma_model_service_smoke: bool,
    pub(crate) gemma_smoke_check_only: bool,
    pub(crate) gemma_smoke_keep_runs: usize,
    pub(crate) gemma_12b_runtime: bool,
    pub(crate) gemma_runtime_program: PathBuf,
    pub(crate) gemma_runtime_server: Option<String>,
    pub(crate) gemma_runtime_quantization: String,
    pub(crate) gemma_runtime_quantization_mode: GemmaRuntimeQuantizationMode,
    pub(crate) gemma_runtime_token_source: Option<String>,
    pub(crate) gemma_runtime_paged_attn: Option<String>,
    pub(crate) gemma_runtime_thinking: Option<String>,
    pub(crate) gemma_runtime_hf_cache: Option<PathBuf>,
    pub(crate) runtime_command: Option<PathBuf>,
    pub(crate) runtime_args: Vec<String>,
    pub(crate) runtime_prompt_mode: CommandPromptMode,
    pub(crate) runtime_wire_format: CommandWireFormat,
    pub(crate) runtime_metadata: RuntimeMetadata,
    pub(crate) native_window_tokens: usize,
    pub(crate) chunk_tokens: usize,
    pub(crate) chunk_overlap_tokens: usize,
    pub(crate) merge_fan_in: usize,
    pub(crate) replay_limit: usize,
    pub(crate) auto_replay_limit: usize,
    pub(crate) retention_stale_after: Option<u64>,
    pub(crate) retention_decay_rate: Option<f32>,
    pub(crate) retention_remove_below: Option<f32>,
    pub(crate) retention_remove_after_failures: Option<u64>,
    pub(crate) compaction_similarity_threshold: Option<f32>,
    pub(crate) compaction_max_candidates: Option<usize>,
    pub(crate) compaction_max_merges: Option<usize>,
    pub(crate) device: DeviceClass,
    pub(crate) device_flag_provided: bool,
    pub(crate) auto_device_probe: Option<HardwareProbeReport>,
    pub(crate) cpu_load_override: bool,
    pub(crate) gpu_load_override: bool,
    pub(crate) ram_load_override: bool,
    pub(crate) disk_load_override: bool,
    pub(crate) cpu_load: f32,
    pub(crate) gpu_load: f32,
    pub(crate) ram_load: f32,
    pub(crate) disk_load: f32,
}
