use super::super::*;

pub(super) fn evaluate_feedback_and_contracts(
    report: &StateInspectionReport,
    gate: &StateInspectionGate,
    failures: &mut Vec<String>,
) {
    require_min_usize(
        failures,
        "process_reward_experience_count",
        report.process_reward_experience_count,
        gate.min_process_reward_experiences,
    );
    require_min_usize(
        failures,
        "process_reward_positive_count",
        report.process_reward_positive_count,
        gate.min_process_reward_positive,
    );
    require_min_usize(
        failures,
        "process_reward_reinforce_count",
        report.process_reward_reinforce_count,
        gate.min_process_reward_reinforce,
    );
    require_min_f32(
        failures,
        "process_reward_total",
        report.process_reward_total,
        gate.min_process_reward_total,
    );
    require_max_usize(
        failures,
        "pool_dispatch_clamped_count",
        report.pool_dispatch_clamped_count,
        gate.max_pool_dispatch_clamped,
    );
    require_max_usize(
        failures,
        "pool_dispatch_low_priority_count",
        report.pool_dispatch_low_priority_count,
        gate.max_pool_dispatch_low_priority,
    );
    require_min_usize(
        failures,
        "external_semantic_context_experience_count",
        report.external_semantic_context_experience_count,
        gate.min_external_semantic_context_experiences,
    );
    require_min_usize(
        failures,
        "external_semantic_context_count",
        report.external_semantic_context_count,
        gate.min_external_semantic_contexts,
    );
    require_min_usize(
        failures,
        "reflection_issue_experience_count",
        report.reflection_issue_experience_count,
        gate.min_reflection_issue_experiences,
    );
    require_min_usize(
        failures,
        "critical_reflection_issue_experience_count",
        report.critical_reflection_issue_experience_count,
        gate.min_critical_reflection_issue_experiences,
    );
    require_min_usize(
        failures,
        "revision_action_experience_count",
        report.revision_action_experience_count,
        gate.min_revision_action_experiences,
    );
    require_min_usize(
        failures,
        "live_memory_feedback_experience_count",
        report.live_memory_feedback_experience_count,
        gate.min_live_memory_feedback_experiences,
    );
    require_min_usize(
        failures,
        "live_memory_feedback_update_count",
        report.live_memory_feedback_update_count,
        gate.min_live_memory_feedback_updates,
    );
    require_min_usize(
        failures,
        "live_memory_feedback_reinforced_count",
        report.live_memory_feedback_reinforced_count,
        gate.min_live_memory_feedback_reinforced,
    );
    require_min_usize(
        failures,
        "live_memory_feedback_penalized_count",
        report.live_memory_feedback_penalized_count,
        gate.min_live_memory_feedback_penalized,
    );
    require_min_usize(
        failures,
        "live_memory_feedback_detail_experience_count",
        report.live_memory_feedback_detail_experience_count,
        gate.min_live_memory_feedback_detail_experiences,
    );
    require_min_usize(
        failures,
        "live_memory_feedback_applied_count",
        report.live_memory_feedback_applied_count,
        gate.min_live_memory_feedback_applied,
    );
    require_max_usize(
        failures,
        "live_memory_feedback_missing_count",
        report.live_memory_feedback_missing_count,
        gate.max_live_memory_feedback_missing,
    );
    require_min_f32(
        failures,
        "live_memory_feedback_strength_delta",
        report.live_memory_feedback_strength_delta,
        gate.min_live_memory_feedback_strength_delta,
    );
    require_min_usize(
        failures,
        "rust_check_experience_count",
        report.rust_check_experience_count,
        gate.min_rust_check_experiences,
    );
    require_min_usize(
        failures,
        "rust_check_passed_count",
        report.rust_check_passed_count,
        gate.min_rust_check_passed,
    );
    require_max_usize(
        failures,
        "rust_check_failed_count",
        report.rust_check_failed_count,
        gate.max_rust_check_failed,
    );
    require_min_usize(
        failures,
        "rust_check_diagnostic_chars",
        report.rust_check_diagnostic_chars,
        gate.min_rust_check_diagnostic_chars,
    );
    require_min_usize(
        failures,
        "business_contract_experience_count",
        report.business_contract_experience_count,
        gate.min_business_contract_experiences,
    );
    require_min_usize(
        failures,
        "business_contract_passed_count",
        report.business_contract_passed_count,
        gate.min_business_contract_passed,
    );
    require_max_usize(
        failures,
        "business_contract_failed_count",
        report.business_contract_failed_count,
        gate.max_business_contract_failed,
    );
    require_max_usize(
        failures,
        "business_contract_missing_signals",
        report.business_contract_missing_signals,
        gate.max_business_contract_missing_signals,
    );
    require_max_usize(
        failures,
        "business_contract_protocol_leaks",
        report.business_contract_protocol_leaks,
        gate.max_business_contract_protocol_leaks,
    );
    require_max_usize(
        failures,
        "business_contract_substitutions",
        report.business_contract_substitutions,
        gate.max_business_contract_substitutions,
    );
    require_max_usize(
        failures,
        "business_contract_evasive_denials",
        report.business_contract_evasive_denials,
        gate.max_business_contract_evasive_denials,
    );
    require_max_usize(
        failures,
        "business_contract_missing_handling_signals",
        report.business_contract_missing_handling_signals,
        gate.max_business_contract_missing_handling_signals,
    );
    require_min_u64(
        failures,
        "router_observations",
        report.router_observations,
        gate.min_router_observations,
    );
}
