use super::super::*;

pub(super) fn evaluate_feedback_and_contracts(
    report: &StateInspectionReport,
    gate: &StateInspectionGate,
    failures: &mut Vec<String>,
) {
    require_min_usize(
        failures,
        "reflection_issue_experience_count",
        report.reflection_issue_experience_count,
        gate.min_reflection_issue_experiences,
    );
    require_min_usize(
        failures,
        "critical_reflection_issue_experience_count",
        report.critical_reflection_issue_experience_count,
        gate.min_critical_reflection_issue_experiences,
    );
    require_min_usize(
        failures,
        "revision_action_experience_count",
        report.revision_action_experience_count,
        gate.min_revision_action_experiences,
    );
    require_min_usize(
        failures,
        "live_memory_feedback_experience_count",
        report.live_memory_feedback_experience_count,
        gate.min_live_memory_feedback_experiences,
    );
    require_min_usize(
        failures,
        "live_memory_feedback_update_count",
        report.live_memory_feedback_update_count,
        gate.min_live_memory_feedback_updates,
    );
    require_min_usize(
        failures,
        "live_memory_feedback_detail_experience_count",
        report.live_memory_feedback_detail_experience_count,
        gate.min_live_memory_feedback_detail_experiences,
    );
    require_min_usize(
        failures,
        "live_memory_feedback_applied_count",
        report.live_memory_feedback_applied_count,
        gate.min_live_memory_feedback_applied,
    );
    require_min_f32(
        failures,
        "live_memory_feedback_strength_delta",
        report.live_memory_feedback_strength_delta,
        gate.min_live_memory_feedback_strength_delta,
    );
    require_min_usize(
        failures,
        "rust_check_experience_count",
        report.rust_check_experience_count,
        gate.min_rust_check_experiences,
    );
    require_min_usize(
        failures,
        "rust_check_passed_count",
        report.rust_check_passed_count,
        gate.min_rust_check_passed,
    );
    require_max_usize(
        failures,
        "rust_check_failed_count",
        report.rust_check_failed_count,
        gate.max_rust_check_failed,
    );
    require_min_usize(
        failures,
        "rust_check_diagnostic_chars",
        report.rust_check_diagnostic_chars,
        gate.min_rust_check_diagnostic_chars,
    );
    require_min_usize(
        failures,
        "business_contract_experience_count",
        report.business_contract_experience_count,
        gate.min_business_contract_experiences,
    );
    require_min_usize(
        failures,
        "business_contract_passed_count",
        report.business_contract_passed_count,
        gate.min_business_contract_passed,
    );
    require_max_usize(
        failures,
        "business_contract_failed_count",
        report.business_contract_failed_count,
        gate.max_business_contract_failed,
    );
    require_max_usize(
        failures,
        "business_contract_missing_signals",
        report.business_contract_missing_signals,
        gate.max_business_contract_missing_signals,
    );
    require_max_usize(
        failures,
        "business_contract_protocol_leaks",
        report.business_contract_protocol_leaks,
        gate.max_business_contract_protocol_leaks,
    );
    require_max_usize(
        failures,
        "business_contract_substitutions",
        report.business_contract_substitutions,
        gate.max_business_contract_substitutions,
    );
    require_max_usize(
        failures,
        "business_contract_evasive_denials",
        report.business_contract_evasive_denials,
        gate.max_business_contract_evasive_denials,
    );
    require_max_usize(
        failures,
        "business_contract_missing_handling_signals",
        report.business_contract_missing_handling_signals,
        gate.max_business_contract_missing_handling_signals,
    );
    require_min_u64(
        failures,
        "router_observations",
        report.router_observations,
        gate.min_router_observations,
    );
}
