use super::super::*;

pub(super) fn evaluate_live_evolution(
    report: &StateInspectionReport,
    gate: &StateInspectionGate,
    failures: &mut Vec<String>,
) {
    require_min_u64(
        failures,
        "evolution_live_inference_runs",
        report.evolution_ledger.live_inference_runs,
        gate.min_evolution_live_inference_runs,
    );
    require_min_u64(
        failures,
        "evolution_live_router_threshold_mutations",
        report.evolution_ledger.live_router_threshold_mutations,
        gate.min_evolution_live_router_threshold_mutations,
    );
    require_min_u64(
        failures,
        "evolution_live_hierarchy_weight_mutations",
        report.evolution_ledger.live_hierarchy_weight_mutations,
        gate.min_evolution_live_hierarchy_weight_mutations,
    );
    require_min_f32(
        failures,
        "evolution_live_router_threshold_delta",
        report.evolution_ledger.live_router_threshold_delta,
        gate.min_evolution_live_router_threshold_delta,
    );
    require_min_f32(
        failures,
        "evolution_live_hierarchy_weight_delta",
        report.evolution_ledger.live_hierarchy_weight_delta,
        gate.min_evolution_live_hierarchy_weight_delta,
    );
    require_min_u64(
        failures,
        "evolution_live_online_reward_feedbacks",
        report.evolution_ledger.live_online_reward_feedbacks,
        gate.min_evolution_live_online_reward_feedbacks,
    );
    require_min_u64(
        failures,
        "evolution_live_online_reward_reinforcements",
        report.evolution_ledger.live_online_reward_reinforcements,
        gate.min_evolution_live_online_reward_reinforcements,
    );
    require_min_u64(
        failures,
        "evolution_live_online_reward_penalties",
        report.evolution_ledger.live_online_reward_penalties,
        gate.min_evolution_live_online_reward_penalties,
    );
    require_min_f32(
        failures,
        "evolution_live_online_reward_strength",
        report.evolution_ledger.live_online_reward_strength,
        gate.min_evolution_live_online_reward_strength,
    );
    require_min_f32(
        failures,
        "evolution_live_online_reward_reinforcement_strength",
        report
            .evolution_ledger
            .live_online_reward_reinforcement_strength,
        gate.min_evolution_live_online_reward_reinforcement_strength,
    );
    require_min_f32(
        failures,
        "evolution_live_online_reward_penalty_strength",
        report.evolution_ledger.live_online_reward_penalty_strength,
        gate.min_evolution_live_online_reward_penalty_strength,
    );
    require_min_u64(
        failures,
        "evolution_live_memory_updates",
        report.evolution_ledger.live_memory_updates(),
        gate.min_evolution_live_memory_updates,
    );
    require_min_u64(
        failures,
        "evolution_live_stored_memory_updates",
        report.evolution_ledger.live_stored_memory_updates(),
        gate.min_evolution_live_stored_memory_updates,
    );
    require_min_u64(
        failures,
        "evolution_live_reflection_issues",
        report.evolution_ledger.live_reflection_issues,
        gate.min_evolution_live_reflection_issues,
    );
    require_min_u64(
        failures,
        "evolution_live_critical_reflection_issues",
        report.evolution_ledger.live_critical_reflection_issues,
        gate.min_evolution_live_critical_reflection_issues,
    );
    require_min_u64(
        failures,
        "evolution_live_revision_actions",
        report.evolution_ledger.live_revision_actions,
        gate.min_evolution_live_revision_actions,
    );
}
