use super::super::*;

pub(super) fn evaluate_replay_evolution(
    report: &StateInspectionReport,
    gate: &StateInspectionGate,
    failures: &mut Vec<String>,
) {
    require_min_u64(
        failures,
        "evolution_replay_runs",
        report.evolution_ledger.replay_runs,
        gate.min_evolution_replay_runs,
    );
    require_min_u64(
        failures,
        "evolution_replay_items",
        report.evolution_ledger.replay_items,
        gate.min_evolution_replay_items,
    );
    require_min_u64(
        failures,
        "evolution_router_threshold_mutations",
        report.evolution_ledger.router_threshold_mutations,
        gate.min_evolution_router_threshold_mutations,
    );
    require_min_u64(
        failures,
        "evolution_hierarchy_weight_mutations",
        report.evolution_ledger.hierarchy_weight_mutations,
        gate.min_evolution_hierarchy_weight_mutations,
    );
    require_min_f32(
        failures,
        "evolution_router_threshold_delta",
        report.evolution_ledger.router_threshold_delta,
        gate.min_evolution_router_threshold_delta,
    );
    require_min_f32(
        failures,
        "evolution_hierarchy_weight_delta",
        report.evolution_ledger.hierarchy_weight_delta,
        gate.min_evolution_hierarchy_weight_delta,
    );
    require_min_u64(
        failures,
        "evolution_memory_updates",
        report.evolution_ledger.memory_updates(),
        gate.min_evolution_memory_updates,
    );
    require_min_u64(
        failures,
        "evolution_external_feedbacks",
        report.evolution_ledger.external_feedbacks,
        gate.min_evolution_external_feedbacks,
    );
    require_min_u64(
        failures,
        "evolution_external_feedback_reinforcements",
        report.evolution_ledger.external_feedback_reinforcements,
        gate.min_evolution_external_feedback_reinforcements,
    );
    require_min_u64(
        failures,
        "evolution_external_feedback_penalties",
        report.evolution_ledger.external_feedback_penalties,
        gate.min_evolution_external_feedback_penalties,
    );
    require_min_u64(
        failures,
        "evolution_external_feedback_memory_updates",
        report.evolution_ledger.external_feedback_memory_updates,
        gate.min_evolution_external_feedback_memory_updates,
    );
    require_min_f32(
        failures,
        "evolution_external_feedback_strength_delta",
        report.evolution_ledger.external_feedback_strength_delta,
        gate.min_evolution_external_feedback_strength_delta,
    );
    require_max_u64(
        failures,
        "evolution_external_feedback_missing",
        report.evolution_ledger.external_feedback_missing,
        gate.max_evolution_external_feedback_missing,
    );
    require_min_u64(
        failures,
        "evolution_replay_live_memory_feedback_updates",
        report
            .evolution_ledger
            .replay_live_memory_feedback_updates(),
        gate.min_evolution_replay_live_memory_feedback_updates,
    );
    require_min_u64(
        failures,
        "evolution_replay_live_memory_feedback_reinforcements",
        report
            .evolution_ledger
            .replay_live_memory_feedback_reinforcements,
        gate.min_evolution_replay_live_memory_feedback_reinforcements,
    );
    require_min_u64(
        failures,
        "evolution_replay_live_memory_feedback_penalties",
        report
            .evolution_ledger
            .replay_live_memory_feedback_penalties,
        gate.min_evolution_replay_live_memory_feedback_penalties,
    );
    require_min_u64(
        failures,
        "evolution_replay_live_memory_feedback_detail_items",
        report
            .evolution_ledger
            .replay_live_memory_feedback_detail_items,
        gate.min_evolution_replay_live_memory_feedback_detail_items,
    );
    require_min_u64(
        failures,
        "evolution_replay_live_memory_feedback_applied",
        report.evolution_ledger.replay_live_memory_feedback_applied,
        gate.min_evolution_replay_live_memory_feedback_applied,
    );
    require_max_u64(
        failures,
        "evolution_replay_live_memory_feedback_missing",
        report.evolution_ledger.replay_live_memory_feedback_missing,
        gate.max_evolution_replay_live_memory_feedback_missing,
    );
    require_min_f32(
        failures,
        "evolution_replay_live_memory_feedback_strength_delta",
        report
            .evolution_ledger
            .replay_live_memory_feedback_strength_delta,
        gate.min_evolution_replay_live_memory_feedback_strength_delta,
    );
    require_min_u64(
        failures,
        "evolution_replay_rust_check_items",
        report.evolution_ledger.replay_rust_check_items,
        gate.min_evolution_replay_rust_check_items,
    );
    require_min_u64(
        failures,
        "evolution_replay_rust_check_passed",
        report.evolution_ledger.replay_rust_check_passed,
        gate.min_evolution_replay_rust_check_passed,
    );
    require_max_u64(
        failures,
        "evolution_replay_rust_check_failed",
        report.evolution_ledger.replay_rust_check_failed,
        gate.max_evolution_replay_rust_check_failed,
    );
    require_min_u64(
        failures,
        "evolution_replay_rust_check_live_memory_feedback_updates",
        report
            .evolution_ledger
            .replay_rust_check_live_memory_feedback_updates,
        gate.min_evolution_replay_rust_check_live_memory_feedback_updates,
    );
    require_min_u64(
        failures,
        "evolution_replay_rust_check_live_memory_feedback_applied",
        report
            .evolution_ledger
            .replay_rust_check_live_memory_feedback_applied,
        gate.min_evolution_replay_rust_check_live_memory_feedback_applied,
    );
    require_min_f32(
        failures,
        "evolution_replay_rust_check_live_memory_feedback_strength_delta",
        report
            .evolution_ledger
            .replay_rust_check_live_memory_feedback_strength_delta,
        gate.min_evolution_replay_rust_check_live_memory_feedback_strength_delta,
    );
    require_min_u64(
        failures,
        "evolution_replay_business_contract_items",
        report.evolution_ledger.replay_business_contract_items,
        gate.min_evolution_replay_business_contract_items,
    );
    require_min_u64(
        failures,
        "evolution_replay_business_contract_passed",
        report.evolution_ledger.replay_business_contract_passed,
        gate.min_evolution_replay_business_contract_passed,
    );
    require_max_u64(
        failures,
        "evolution_replay_business_contract_failed",
        report.evolution_ledger.replay_business_contract_failed,
        gate.max_evolution_replay_business_contract_failed,
    );
    require_min_u64(
        failures,
        "evolution_replay_business_contract_raw_audits",
        report
            .evolution_ledger
            .replay_business_contract_raw_passed
            .saturating_add(report.evolution_ledger.replay_business_contract_raw_failed),
        gate.min_evolution_replay_business_contract_raw_audits,
    );
    require_min_u64(
        failures,
        "evolution_replay_live_evolution_items",
        report.evolution_ledger.replay_live_evolution_items,
        gate.min_evolution_replay_live_evolution_items,
    );
    require_min_u64(
        failures,
        "evolution_replay_live_evolution_online_reward_feedbacks",
        report
            .evolution_ledger
            .replay_live_evolution_online_reward_feedbacks,
        gate.min_evolution_replay_live_evolution_online_reward_feedbacks,
    );
    require_min_u64(
        failures,
        "evolution_replay_live_evolution_online_reward_reinforcements",
        report
            .evolution_ledger
            .replay_live_evolution_online_reward_reinforcements,
        gate.min_evolution_replay_live_evolution_online_reward_reinforcements,
    );
    require_min_u64(
        failures,
        "evolution_replay_live_evolution_online_reward_penalties",
        report
            .evolution_ledger
            .replay_live_evolution_online_reward_penalties,
        gate.min_evolution_replay_live_evolution_online_reward_penalties,
    );
    require_min_f32(
        failures,
        "evolution_replay_live_evolution_online_reward_strength",
        report
            .evolution_ledger
            .replay_live_evolution_online_reward_strength,
        gate.min_evolution_replay_live_evolution_online_reward_strength,
    );
    require_min_f32(
        failures,
        "evolution_replay_live_evolution_online_reward_reinforcement_strength",
        report
            .evolution_ledger
            .replay_live_evolution_online_reward_reinforcement_strength,
        gate.min_evolution_replay_live_evolution_online_reward_reinforcement_strength,
    );
    require_min_f32(
        failures,
        "evolution_replay_live_evolution_online_reward_penalty_strength",
        report
            .evolution_ledger
            .replay_live_evolution_online_reward_penalty_strength,
        gate.min_evolution_replay_live_evolution_online_reward_penalty_strength,
    );
    require_min_u64(
        failures,
        "evolution_replay_live_evolution_memory_updates",
        report.evolution_ledger.replay_live_evolution_memory_updates,
        gate.min_evolution_replay_live_evolution_memory_updates,
    );
    require_min_u64(
        failures,
        "evolution_replay_live_evolution_stored_memory_updates",
        report
            .evolution_ledger
            .replay_live_evolution_stored_memory_updates,
        gate.min_evolution_replay_live_evolution_stored_memory_updates,
    );
    require_min_u64(
        failures,
        "evolution_replay_live_evolution_reflection_issues",
        report
            .evolution_ledger
            .replay_live_evolution_reflection_issues,
        gate.min_evolution_replay_live_evolution_reflection_issues,
    );
    require_min_u64(
        failures,
        "evolution_replay_live_evolution_critical_reflection_issues",
        report
            .evolution_ledger
            .replay_live_evolution_critical_reflection_issues,
        gate.min_evolution_replay_live_evolution_critical_reflection_issues,
    );
    require_min_u64(
        failures,
        "evolution_replay_live_evolution_revision_actions",
        report
            .evolution_ledger
            .replay_live_evolution_revision_actions,
        gate.min_evolution_replay_live_evolution_revision_actions,
    );
    require_min_u64(
        failures,
        "evolution_recursive_replay_items",
        report.evolution_ledger.recursive_replay_items,
        gate.min_evolution_recursive_replay_items,
    );
    require_min_u64(
        failures,
        "evolution_recursive_runtime_calls",
        report.evolution_ledger.recursive_runtime_calls,
        gate.min_evolution_recursive_runtime_calls,
    );
    require_max_u64(
        failures,
        "evolution_drift_rollbacks",
        report.evolution_ledger.drift_rollbacks,
        gate.max_evolution_drift_rollbacks,
    );
    require_max_f32(
        failures,
        "evolution_rollback_router_threshold_delta",
        report.evolution_ledger.rollback_router_threshold_delta,
        gate.max_evolution_rollback_router_threshold_delta,
    );
    require_max_f32(
        failures,
        "evolution_rollback_hierarchy_weight_delta",
        report.evolution_ledger.rollback_hierarchy_weight_delta,
        gate.max_evolution_rollback_hierarchy_weight_delta,
    );
}
