use super::super::*;

pub(super) fn evaluate_runtime_evidence(
    report: &StateInspectionReport,
    gate: &StateInspectionGate,
    failures: &mut Vec<String>,
) {
    require_min_usize(
        failures,
        "runtime_model_experience_count",
        report.runtime_model_experience_count,
        gate.min_runtime_model_experiences,
    );
    require_min_usize(
        failures,
        "runtime_adapter_experience_count",
        report.runtime_adapter_experience_count,
        gate.min_runtime_adapter_experiences,
    );
    require_max_usize(
        failures,
        "runtime_adapter_selection_mismatch_count",
        report.runtime_adapter_selection_mismatch_count,
        gate.max_runtime_adapter_selection_mismatches,
    );
    require_min_usize(
        failures,
        "runtime_forward_energy_experience_count",
        report.runtime_forward_energy_experience_count,
        gate.min_runtime_forward_energy_experiences,
    );
    require_min_usize(
        failures,
        "runtime_kv_influence_experience_count",
        report.runtime_kv_influence_experience_count,
        gate.min_runtime_kv_influence_experiences,
    );
    require_min_usize(
        failures,
        "runtime_token_count",
        report.runtime_token_count,
        gate.min_runtime_tokens,
    );
    require_min_usize(
        failures,
        "runtime_uncertainty_experience_count",
        report.runtime_uncertainty_experience_count,
        gate.min_runtime_uncertainty_experiences,
    );
    require_min_usize(
        failures,
        "runtime_uncertainty_token_count",
        report.runtime_uncertainty_token_count,
        gate.min_runtime_uncertainty_tokens,
    );
    require_min_usize(
        failures,
        "runtime_architecture_experience_count",
        report.runtime_architecture_experience_count,
        gate.min_runtime_architecture_experiences,
    );
    require_min_usize(
        failures,
        "runtime_kv_precision_experience_count",
        report.runtime_kv_precision_experience_count,
        gate.min_runtime_kv_precision_experiences,
    );
    require_max_usize(
        failures,
        "runtime_kv_precision_mismatch_count",
        report.runtime_kv_precision_mismatch_count,
        gate.max_runtime_kv_precision_mismatches,
    );
    require_max_usize(
        failures,
        "runtime_error_count",
        report.runtime_error_count,
        gate.max_runtime_errors,
    );
    require_max_usize(
        failures,
        "runtime_timeout_count",
        report.runtime_timeout_count,
        gate.max_runtime_timeouts,
    );
    require_min_usize(
        failures,
        "runtime_device_execution_experience_count",
        report.runtime_device_execution_experience_count,
        gate.min_runtime_device_execution_experiences,
    );
    require_min_usize(
        failures,
        "runtime_layer_mode_experience_count",
        report.runtime_layer_mode_experience_count,
        gate.min_runtime_layer_mode_experiences,
    );
    require_min_usize(
        failures,
        "runtime_all_layer_mode_experience_count",
        report.runtime_all_layer_mode_experience_count,
        gate.min_runtime_all_layer_mode_experiences,
    );
    require_min_usize(
        failures,
        "runtime_global_layers",
        report.runtime_global_layers,
        gate.min_runtime_global_layers,
    );
    require_min_usize(
        failures,
        "runtime_local_window_layers",
        report.runtime_local_window_layers,
        gate.min_runtime_local_window_layers,
    );
    require_min_usize(
        failures,
        "runtime_convolutional_fusion_layers",
        report.runtime_convolutional_fusion_layers,
        gate.min_runtime_convolutional_fusion_layers,
    );
    require_min_usize(
        failures,
        "runtime_kv_import_experience_count",
        report.runtime_kv_import_experience_count,
        gate.min_runtime_kv_import_experiences,
    );
    require_min_usize(
        failures,
        "runtime_kv_weak_import_skip_experience_count",
        report.runtime_kv_weak_import_skip_experience_count,
        gate.min_runtime_kv_weak_import_skip_experiences,
    );
    require_min_usize(
        failures,
        "weak_runtime_kv_imports_skipped",
        report.weak_runtime_kv_imports_skipped,
        gate.min_weak_runtime_kv_imports_skipped,
    );
    require_min_usize(
        failures,
        "runtime_kv_budget_import_skip_experience_count",
        report.runtime_kv_budget_import_skip_experience_count,
        gate.min_runtime_kv_budget_import_skip_experiences,
    );
    require_min_usize(
        failures,
        "budget_limited_runtime_kv_imports_skipped",
        report.budget_limited_runtime_kv_imports_skipped,
        gate.min_budget_limited_runtime_kv_imports_skipped,
    );
    require_min_usize(
        failures,
        "runtime_kv_export_experience_count",
        report.runtime_kv_export_experience_count,
        gate.min_runtime_kv_export_experiences,
    );
    require_min_usize(
        failures,
        "runtime_kv_segment_experience_count",
        report.runtime_kv_segment_experience_count,
        gate.min_runtime_kv_segment_experiences,
    );
    require_min_usize(
        failures,
        "runtime_kv_segments_included",
        report.runtime_kv_segments_included,
        gate.min_runtime_kv_segments_included,
    );
    require_max_usize(
        failures,
        "runtime_kv_segments_rejected",
        report.runtime_kv_segments_rejected,
        gate.max_runtime_kv_segments_rejected,
    );
    require_min_usize(
        failures,
        "runtime_kv_hold_experience_count",
        report.runtime_kv_hold_experience_count,
        gate.min_runtime_kv_hold_experiences,
    );
    require_min_usize(
        failures,
        "runtime_kv_held_blocks",
        report.runtime_kv_held_blocks,
        gate.min_runtime_kv_held_blocks,
    );
}
