mod construction;
mod evidence_builders;

use crate::hardware::DeviceClass;

use super::gate_report::StateInspectionGateReport;

#[derive(Debug, Clone, PartialEq)]
pub struct StateInspectionDeviceGateReport {
    pub device: DeviceClass,
    pub report: StateInspectionGateReport,
    pub runtime_kv_memories: usize,
    pub runtime_model_experiences: usize,
    pub runtime_adapter_experiences: usize,
    pub runtime_adapter_selection_mismatches: usize,
    pub runtime_forward_energy_experiences: usize,
    pub runtime_kv_influence_experiences: usize,
    pub runtime_uncertainty_experiences: usize,
    pub runtime_uncertainty_tokens: usize,
    pub runtime_architecture_experiences: usize,
    pub runtime_kv_precision_experiences: usize,
    pub runtime_kv_precision_mismatches: usize,
    pub runtime_device_execution_experiences: usize,
    pub runtime_layer_mode_experiences: usize,
    pub runtime_all_layer_mode_experiences: usize,
    pub runtime_kv_import_experiences: usize,
    pub runtime_kv_weak_import_skip_experiences: usize,
    pub weak_runtime_kv_imports_skipped: usize,
    pub runtime_kv_weak_import_pressure_experiences: usize,
    pub runtime_kv_budget_import_skip_experiences: usize,
    pub budget_limited_runtime_kv_imports_skipped: usize,
    pub runtime_kv_budget_pressure_experiences: usize,
    pub runtime_kv_export_experiences: usize,
    pub runtime_kv_segment_experiences: usize,
    pub runtime_kv_segments_included: usize,
    pub runtime_kv_segments_skipped: usize,
    pub runtime_kv_segments_rejected: usize,
    pub runtime_kv_hold_experiences: usize,
    pub runtime_kv_held_blocks: usize,
    pub reflection_issue_experiences: usize,
    pub critical_reflection_issue_experiences: usize,
    pub revision_action_experiences: usize,
    pub live_memory_feedback_experiences: usize,
    pub live_memory_feedback_updates: usize,
    pub live_memory_feedback_detail_experiences: usize,
    pub live_memory_feedback_applied: usize,
    pub live_memory_feedback_removed: usize,
    pub live_memory_feedback_missing: usize,
    pub live_memory_feedback_strength_delta: f32,
    pub evolution_live_inference_runs: u64,
    pub evolution_live_router_threshold_mutations: u64,
    pub evolution_live_hierarchy_weight_mutations: u64,
    pub evolution_live_online_reward_feedbacks: u64,
    pub evolution_live_online_reward_reinforcements: u64,
    pub evolution_live_online_reward_penalties: u64,
    pub evolution_live_online_reward_strength: f32,
    pub evolution_live_online_reward_reinforcement_strength: f32,
    pub evolution_live_online_reward_penalty_strength: f32,
    pub evolution_live_memory_updates: u64,
    pub evolution_live_stored_memory_updates: u64,
    pub evolution_live_reflection_issues: u64,
    pub evolution_live_critical_reflection_issues: u64,
    pub evolution_live_revision_actions: u64,
    pub evolution_replay_runs: u64,
    pub evolution_replay_items: u64,
    pub evolution_router_threshold_mutations: u64,
    pub evolution_hierarchy_weight_mutations: u64,
    pub evolution_memory_updates: u64,
    pub evolution_replay_live_memory_feedback_updates: u64,
    pub evolution_replay_live_memory_feedback_detail_items: u64,
    pub evolution_replay_live_memory_feedback_applied: u64,
    pub evolution_replay_live_memory_feedback_removed: u64,
    pub evolution_replay_live_memory_feedback_missing: u64,
    pub evolution_replay_live_memory_feedback_strength_delta: f32,
    pub evolution_replay_live_evolution_items: u64,
    pub evolution_replay_live_evolution_online_reward_feedbacks: u64,
    pub evolution_replay_live_evolution_online_reward_reinforcements: u64,
    pub evolution_replay_live_evolution_online_reward_penalties: u64,
    pub evolution_replay_live_evolution_online_reward_strength: f32,
    pub evolution_replay_live_evolution_online_reward_reinforcement_strength: f32,
    pub evolution_replay_live_evolution_online_reward_penalty_strength: f32,
    pub evolution_replay_live_evolution_memory_updates: u64,
    pub evolution_replay_live_evolution_stored_memory_updates: u64,
    pub evolution_replay_live_evolution_reflection_issues: u64,
    pub evolution_replay_live_evolution_critical_reflection_issues: u64,
    pub evolution_replay_live_evolution_revision_actions: u64,
    pub evolution_recursive_replay_items: u64,
    pub evolution_recursive_runtime_calls: u64,
}
