use crate::adaptive_state::EvolutionLedger;
use crate::experience::ExperienceHygieneSeverity;
use crate::hierarchy::{
    HierarchyWeights, ProfileHierarchyObservations, ProfileHierarchyWeights, TaskProfile,
};
use crate::kv_cache::{MemoryCompactionPolicy, MemoryRetentionPolicy};
use crate::process_reward::RewardAction;
use crate::router::{ProfileObservations, ProfileThresholds};
use crate::tiered_cache::TierCounts;

#[derive(Debug, Clone)]
pub struct StateMemorySummary {
    pub id: u64,
    pub key: String,
    pub vector_dimensions: usize,
    pub strength: f32,
    pub hits: u64,
    pub failures: u64,
    pub last_score: f32,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct StateMemoryVectorDimensions {
    pub dimensions: usize,
    pub count: usize,
}

#[derive(Debug, Clone)]
pub struct StateExperienceSummary {
    pub id: u64,
    pub profile: TaskProfile,
    pub quality: f32,
    pub process_reward: f32,
    pub reward_action: RewardAction,
    pub runtime_model_id: Option<String>,
    pub runtime_selected_adapter: Option<String>,
    pub runtime_device_profile: Option<String>,
    pub runtime_primary_lane: Option<String>,
    pub runtime_fallback_lane: Option<String>,
    pub runtime_memory_mode: Option<String>,
    pub runtime_layer_count: usize,
    pub runtime_global_layers: usize,
    pub runtime_local_window_layers: usize,
    pub runtime_convolutional_fusion_layers: usize,
    pub runtime_hidden_size: usize,
    pub runtime_local_window_tokens: usize,
    pub runtime_forward_energy: Option<f32>,
    pub runtime_kv_influence: Option<f32>,
    pub runtime_token_count: usize,
    pub runtime_uncertainty_token_count: usize,
    pub runtime_uncertainty_perplexity: Option<f32>,
    pub runtime_hot_kv_precision_bits: Option<u8>,
    pub runtime_cold_kv_precision_bits: Option<u8>,
    pub runtime_imported_kv_blocks: usize,
    pub runtime_weak_kv_imports_skipped: usize,
    pub runtime_budget_limited_kv_imports_skipped: usize,
    pub runtime_exported_kv_blocks: usize,
    pub runtime_kv_segments_included: usize,
    pub runtime_kv_segments_skipped: usize,
    pub runtime_kv_segments_rejected: usize,
    pub recursive_runtime_calls: Option<usize>,
    pub runtime_errors: usize,
    pub runtime_timeouts: usize,
    pub runtime_error_message_chars: usize,
    pub live_online_reward_feedbacks: usize,
    pub live_online_reward_reinforcements: usize,
    pub live_online_reward_penalties: usize,
    pub live_memory_feedback_updates: usize,
    pub live_memory_feedback_reinforced: usize,
    pub live_memory_feedback_penalized: usize,
    pub live_memory_feedback_applied: usize,
    pub live_memory_feedback_removed: usize,
    pub live_memory_feedback_missing: usize,
    pub live_memory_feedback_strength_delta: f32,
    pub live_memory_feedback_detail: bool,
    pub rust_check_passed: usize,
    pub rust_check_failed: usize,
    pub rust_check_diagnostic_chars: usize,
    pub business_contract_passed: usize,
    pub business_contract_failed: usize,
    pub business_contract_missing_signals: usize,
    pub business_contract_protocol_leaks: usize,
    pub business_contract_substitutions: usize,
    pub business_contract_evasive_denials: usize,
    pub business_contract_missing_handling_signals: usize,
    pub business_contract_raw_passed: usize,
    pub business_contract_raw_failed: usize,
    pub business_contract_response_normalized: usize,
    pub business_contract_sanitized: usize,
    pub business_contract_canonical_fallbacks: usize,
    pub pool_dispatch_items: usize,
    pub pool_dispatch_selected_roles: Vec<String>,
    pub pool_dispatch_forwarded: usize,
    pub pool_dispatch_clamped: usize,
    pub pool_dispatch_low_priority: usize,
    pub reflection_issues: usize,
    pub critical_reflection_issues: usize,
    pub revision_actions: usize,
    pub lesson: String,
}

#[derive(Debug, Clone)]
pub struct StateExperienceHygieneFinding {
    pub experience_id: u64,
    pub severity: ExperienceHygieneSeverity,
    pub reason: String,
    pub markers: Vec<String>,
    pub prompt_preview: String,
    pub lesson_preview: String,
}

#[derive(Debug, Clone)]
pub struct StateExperienceIndexFinding {
    pub experience_id: u64,
    pub reason: String,
    pub compacted: bool,
    pub noise_penalty: f32,
    pub duplicate_of: Option<u64>,
    pub prompt_chars: usize,
    pub lesson_chars: usize,
    pub prompt_preview: String,
    pub lesson_preview: String,
}

#[derive(Debug, Clone)]
pub struct StateInspectionReport {
    pub memory_count: usize,
    pub runtime_kv_memory_count: usize,
    pub experience_count: usize,
    pub experience_hygiene_finding_count: usize,
    pub experience_hygiene_watch_count: usize,
    pub experience_hygiene_quarantine_candidate_count: usize,
    pub experience_hygiene_legacy_metadata_lesson_count: usize,
    pub experience_hygiene_legacy_metadata_without_clean_gist_count: usize,
    pub experience_repairable_legacy_metadata_lesson_count: usize,
    pub experience_repairable_index_record_count: usize,
    pub experience_repair_projected_hygiene_finding_count: usize,
    pub experience_repair_projected_hygiene_watch_count: usize,
    pub experience_repair_projected_hygiene_quarantine_candidate_count: usize,
    pub experience_repair_projected_legacy_metadata_lesson_count: usize,
    pub experience_repair_projected_legacy_metadata_without_clean_gist_count: usize,
    pub experience_repair_skipped_quarantine_candidate_count: usize,
    pub experience_repair_skipped_missing_clean_gist_count: usize,
    pub experience_index_compacted_record_count: usize,
    pub experience_index_overlong_record_count: usize,
    pub experience_index_overlong_without_clean_gist_count: usize,
    pub experience_index_max_record_chars: usize,
    pub experience_index_noisy_record_count: usize,
    pub experience_index_duplicate_output_count: usize,
    pub experience_index_max_noise_penalty: f32,
    pub experience_index_quality_score: f32,
    pub experience_index_retrieval_ready: bool,
    pub experience_index_risk_level: String,
    pub runtime_model_experience_count: usize,
    pub runtime_adapter_experience_count: usize,
    pub runtime_adapter_selection_mismatch_count: usize,
    pub runtime_forward_energy_experience_count: usize,
    pub runtime_kv_influence_experience_count: usize,
    pub runtime_token_count: usize,
    pub runtime_uncertainty_experience_count: usize,
    pub runtime_uncertainty_token_count: usize,
    pub runtime_architecture_experience_count: usize,
    pub runtime_kv_precision_experience_count: usize,
    pub runtime_kv_precision_mismatch_count: usize,
    pub runtime_device_execution_experience_count: usize,
    pub runtime_layer_mode_experience_count: usize,
    pub runtime_all_layer_mode_experience_count: usize,
    pub runtime_global_layers: usize,
    pub runtime_local_window_layers: usize,
    pub runtime_convolutional_fusion_layers: usize,
    pub runtime_kv_import_experience_count: usize,
    pub runtime_kv_weak_import_skip_experience_count: usize,
    pub weak_runtime_kv_imports_skipped: usize,
    pub runtime_kv_budget_import_skip_experience_count: usize,
    pub budget_limited_runtime_kv_imports_skipped: usize,
    pub runtime_kv_export_experience_count: usize,
    pub runtime_kv_segment_experience_count: usize,
    pub runtime_kv_segments_included: usize,
    pub runtime_kv_segments_skipped: usize,
    pub runtime_kv_segments_rejected: usize,
    pub runtime_kv_hold_experience_count: usize,
    pub runtime_kv_held_blocks: usize,
    pub runtime_error_experience_count: usize,
    pub runtime_error_count: usize,
    pub runtime_timeout_experience_count: usize,
    pub runtime_timeout_count: usize,
    pub runtime_error_message_chars: usize,
    pub reflection_issue_experience_count: usize,
    pub critical_reflection_issue_experience_count: usize,
    pub revision_action_experience_count: usize,
    pub live_memory_feedback_experience_count: usize,
    pub live_memory_feedback_update_count: usize,
    pub live_memory_feedback_detail_experience_count: usize,
    pub live_memory_feedback_applied_count: usize,
    pub live_memory_feedback_removed_count: usize,
    pub live_memory_feedback_missing_count: usize,
    pub live_memory_feedback_strength_delta: f32,
    pub rust_check_experience_count: usize,
    pub rust_check_passed_count: usize,
    pub rust_check_failed_count: usize,
    pub rust_check_diagnostic_chars: usize,
    pub business_contract_experience_count: usize,
    pub business_contract_passed_count: usize,
    pub business_contract_failed_count: usize,
    pub business_contract_required_signals: usize,
    pub business_contract_matched_signals: usize,
    pub business_contract_missing_signals: usize,
    pub business_contract_protocol_leaks: usize,
    pub business_contract_substitutions: usize,
    pub business_contract_evasive_denials: usize,
    pub business_contract_missing_handling_signals: usize,
    pub business_contract_raw_passed_count: usize,
    pub business_contract_raw_failed_count: usize,
    pub business_contract_response_normalized_count: usize,
    pub business_contract_sanitized_count: usize,
    pub business_contract_canonical_fallback_count: usize,
    pub pool_dispatch_experience_count: usize,
    pub pool_dispatch_item_count: usize,
    pub pool_dispatch_forwarded_count: usize,
    pub pool_dispatch_clamped_count: usize,
    pub pool_dispatch_low_priority_count: usize,
    pub router_threshold: f32,
    pub router_observations: u64,
    pub profile_thresholds: ProfileThresholds,
    pub profile_observations: ProfileObservations,
    pub hierarchy: HierarchyWeights,
    pub profile_hierarchy_weights: ProfileHierarchyWeights,
    pub profile_hierarchy_observations: ProfileHierarchyObservations,
    pub tier_counts: TierCounts,
    pub memory_retention_policy: MemoryRetentionPolicy,
    pub memory_compaction_policy: MemoryCompactionPolicy,
    pub evolution_ledger: EvolutionLedger,
    pub memory_vector_dimensions: Vec<StateMemoryVectorDimensions>,
    pub runtime_kv_vector_dimensions: Vec<StateMemoryVectorDimensions>,
    pub top_memories: Vec<StateMemorySummary>,
    pub top_runtime_kv_memories: Vec<StateMemorySummary>,
    pub top_experiences: Vec<StateExperienceSummary>,
    pub experience_hygiene_findings: Vec<StateExperienceHygieneFinding>,
    pub experience_index_findings: Vec<StateExperienceIndexFinding>,
}
