mod from_plan;
mod memory_updates;
mod summary;

use crate::kv_cache::MemoryUpdateReport;

#[derive(Debug, Clone, Default)]
pub struct ExperienceReplayReport {
    pub planned: usize,
    pub applied: usize,
    pub router_updates: usize,
    pub hierarchy_updates: usize,
    pub router_threshold_mutations: usize,
    pub hierarchy_weight_mutations: usize,
    pub router_threshold_delta: f32,
    pub hierarchy_weight_delta: f32,
    pub reinforced: usize,
    pub penalized: usize,
    pub touched_memories: usize,
    pub memory_reinforcements: usize,
    pub memory_penalties: usize,
    pub memory_update_reports: Vec<MemoryUpdateReport>,
    pub applied_memory_updates: usize,
    pub removed_memory_updates: usize,
    pub missing_memory_updates: usize,
    pub memory_strength_delta: f32,
    pub average_reward: f32,
    pub external_semantic_context_items: usize,
    pub external_semantic_contexts: usize,
    pub runtime_kv_budget_pressure_items: usize,
    pub average_runtime_kv_budget_pressure: f32,
    pub max_runtime_kv_budget_pressure: f32,
    pub runtime_kv_weak_import_pressure_items: usize,
    pub average_runtime_kv_weak_import_pressure: f32,
    pub max_runtime_kv_weak_import_pressure: f32,
    pub recursive_runtime_items: usize,
    pub recursive_runtime_calls: usize,
    pub average_recursive_call_pressure: f32,
    pub max_recursive_call_pressure: f32,
    pub live_memory_feedback_items: usize,
    pub live_memory_feedback_updates: usize,
    pub live_memory_feedback_reinforcements: usize,
    pub live_memory_feedback_penalties: usize,
    pub live_memory_feedback_detail_items: usize,
    pub live_memory_feedback_applied: usize,
    pub live_memory_feedback_removed: usize,
    pub live_memory_feedback_missing: usize,
    pub live_memory_feedback_strength_delta: f32,
    pub live_evolution_items: usize,
    pub live_evolution_router_threshold_mutations: usize,
    pub live_evolution_hierarchy_weight_mutations: usize,
    pub live_evolution_router_threshold_delta: f32,
    pub live_evolution_hierarchy_weight_delta: f32,
    pub live_evolution_online_reward_feedbacks: usize,
    pub live_evolution_online_reward_reinforcements: usize,
    pub live_evolution_online_reward_penalties: usize,
    pub live_evolution_online_reward_strength: f32,
    pub live_evolution_online_reward_reinforcement_strength: f32,
    pub live_evolution_online_reward_penalty_strength: f32,
    pub live_evolution_memory_updates: usize,
    pub live_evolution_stored_memory_updates: usize,
    pub live_evolution_reflection_issues: usize,
    pub live_evolution_critical_reflection_issues: usize,
    pub live_evolution_revision_actions: usize,
    pub rust_check_items: usize,
    pub rust_check_passed: usize,
    pub rust_check_failed: usize,
    pub rust_check_diagnostic_chars: usize,
    pub rust_check_live_memory_feedback_items: usize,
    pub rust_check_live_memory_feedback_updates: usize,
    pub rust_check_live_memory_feedback_applied: usize,
    pub rust_check_live_memory_feedback_missing: usize,
    pub rust_check_live_memory_feedback_strength_delta: f32,
    pub business_contract_items: usize,
    pub business_contract_passed: usize,
    pub business_contract_failed: usize,
    pub business_contract_raw_passed: usize,
    pub business_contract_raw_failed: usize,
    pub business_contract_response_normalized: usize,
    pub business_contract_sanitized: usize,
    pub business_contract_canonical_fallbacks: usize,
    pub pool_dispatch_items: usize,
    pub pool_dispatch_forwarded: usize,
    pub pool_dispatch_clamped: usize,
    pub pool_dispatch_low_priority: usize,
    pub notes: Vec<String>,
}
