use rust_norion::{DeviceClass, HardwareSnapshot, normalize_runtime_metadata};

use crate::model_service::profile::detect_profile;

use super::super::super::Args;
use super::super::super::gemma::{GemmaSmokeDefaults, GemmaSmokeKind, prompt_or_default};
use super::model::ParseState;

impl ParseState {
    pub(crate) fn finalize(mut self) -> Args {
        let gemma_smoke_kind = GemmaSmokeKind::from_flags(
            self.gemma_business_smoke,
            self.gemma_business_cycle_smoke,
            self.gemma_model_service_smoke,
        );
        if let Some(smoke_kind) = gemma_smoke_kind {
            GemmaSmokeDefaults {
                kind: smoke_kind,
                memory_path: &mut self.memory_path,
                experience_path: &mut self.experience_path,
                adaptive_path: &mut self.adaptive_path,
                trace_path: &mut self.trace_path,
                trace_schema_gate_path: &mut self.trace_schema_gate_path,
                memory_path_set: self.memory_path_set,
                experience_path_set: self.experience_path_set,
                adaptive_path_set: self.adaptive_path_set,
                trace_path_set: self.trace_path_set,
                trace_schema_gate_path_set: self.trace_schema_gate_path_set,
                gemma_runtime: &mut self.gemma_runtime,
                runtime_metadata: &self.runtime_metadata,
                profile: &mut self.profile,
                runtime_timeout_ms: &mut self.runtime_timeout_ms,
                runtime_args: &mut self.runtime_args,
            }
            .apply();
        }

        let prompt = prompt_or_default(&self.prompt_parts, gemma_smoke_kind);
        self.runtime_metadata = normalize_runtime_metadata(self.runtime_metadata);
        let profile = self.profile.unwrap_or_else(|| detect_profile(&prompt));
        if self.inspect_state && self.benchmark_all_devices {
            self.inspect_gate = true;
        }
        if self.device == DeviceClass::Auto {
            let detected = HardwareSnapshot::auto_detect_report();
            self.device = detected.device;
            if !self.cpu_load_set {
                self.cpu_load = detected.cpu_load;
            }
            if !self.gpu_load_set {
                self.gpu_load = detected.gpu_load;
            }
            if !self.ram_load_set {
                self.ram_load = detected.ram_load;
            }
            if !self.disk_load_set {
                self.disk_load = detected.disk_load;
            }
            self.auto_device_probe = Some(detected);
        }

        Args {
            prompt,
            profile,
            max_tokens: self.max_tokens,
            memory_path: self.memory_path,
            experience_path: self.experience_path,
            adaptive_path: self.adaptive_path,
            trace_path: self.trace_path,
            trace_schema_gate_path: self.trace_schema_gate_path,
            self_goal_queue: self.self_goal_queue,
            self_goal_queue_store_path: self.self_goal_queue_store_path,
            self_goal_queue_store_apply: self.self_goal_queue_store_apply,
            self_goal_queue_evidence_packets: self.self_goal_queue_evidence_packets,
            self_goal_queue_evidence_path: self.self_goal_queue_evidence_path,
            self_goal_queue_local_evidence: self.self_goal_queue_local_evidence,
            self_goal_queue_local_evidence_dry_run: self.self_goal_queue_local_evidence_dry_run,
            self_goal_queue_tenant: self.self_goal_queue_tenant,
            self_goal_queue_workspace: self.self_goal_queue_workspace,
            self_goal_queue_session: self.self_goal_queue_session,
            self_goal_queue_key: self.self_goal_queue_key,
            self_goal_queue_operator: self.self_goal_queue_operator,
            self_goal_queue_ticket: self.self_goal_queue_ticket,
            coding_service_eval_readiness: self.coding_service_eval_readiness,
            coding_service_eval_runner: self.coding_service_eval_runner,
            experience_hygiene: self.experience_hygiene,
            experience_hygiene_limit: self.experience_hygiene_limit,
            experience_hygiene_quarantine: self.experience_hygiene_quarantine,
            experience_hygiene_apply: self.experience_hygiene_apply,
            experience_hygiene_quarantine_path: self.experience_hygiene_quarantine_path,
            experience_hygiene_backup_path: self.experience_hygiene_backup_path,
            experience_repair: self.experience_repair,
            experience_repair_limit: self.experience_repair_limit,
            experience_repair_apply: self.experience_repair_apply,
            experience_repair_backup_path: self.experience_repair_backup_path,
            experience_retrieval: self.experience_retrieval,
            experience_retrieval_limit: self.experience_retrieval_limit,
            experience_cleanup_audit: self.experience_cleanup_audit,
            experience_cleanup_audit_limit: self.experience_cleanup_audit_limit,
            experience_cleanup_audit_path: self.experience_cleanup_audit_path,
            experience_index_add_clean_gist: self.experience_index_add_clean_gist,
            experience_index_record_id: self.experience_index_record_id,
            experience_index_clean_gist: self.experience_index_clean_gist,
            experience_index_clean_gist_title: self.experience_index_clean_gist_title,
            experience_index_clean_gist_importance: self.experience_index_clean_gist_importance,
            experience_index_backup_path: self.experience_index_backup_path,
            benchmark_path: self.benchmark_path,
            benchmark_all_devices: self.benchmark_all_devices,
            benchmark_gate_enabled: self.benchmark_gate_enabled,
            benchmark_min_quality: self.benchmark_min_quality,
            benchmark_min_reward: self.benchmark_min_reward,
            benchmark_max_total_ms: self.benchmark_max_total_ms,
            benchmark_max_recursive_chunks: self.benchmark_max_recursive_chunks,
            benchmark_min_recursive_cases: self.benchmark_min_recursive_cases,
            benchmark_min_recursive_runtime_calls: self.benchmark_min_recursive_runtime_calls,
            benchmark_min_auto_replay_router_updates: self.benchmark_min_auto_replay_router_updates,
            benchmark_min_auto_replay_hierarchy_updates: self.benchmark_min_auto_replay_hierarchy_updates,
            benchmark_min_auto_replay_router_threshold_mutations: self.benchmark_min_auto_replay_router_threshold_mutations,
            benchmark_min_auto_replay_hierarchy_weight_mutations: self.benchmark_min_auto_replay_hierarchy_weight_mutations,
            benchmark_min_auto_replay_router_threshold_delta: self.benchmark_min_auto_replay_router_threshold_delta,
            benchmark_min_auto_replay_hierarchy_weight_delta: self.benchmark_min_auto_replay_hierarchy_weight_delta,
            benchmark_min_auto_replay_memory_updates: self.benchmark_min_auto_replay_memory_updates,
            benchmark_min_live_memory_feedback_updates: self.benchmark_min_live_memory_feedback_updates,
            benchmark_min_auto_replay_live_memory_feedback_updates: self.benchmark_min_auto_replay_live_memory_feedback_updates,
            benchmark_min_auto_replay_live_memory_feedback_detail_items: self.benchmark_min_auto_replay_live_memory_feedback_detail_items,
            benchmark_min_auto_replay_live_memory_feedback_applied: self.benchmark_min_auto_replay_live_memory_feedback_applied,
            benchmark_min_auto_replay_live_memory_feedback_strength_delta: self.benchmark_min_auto_replay_live_memory_feedback_strength_delta,
            benchmark_min_auto_replay_recursive_items: self.benchmark_min_auto_replay_recursive_items,
            benchmark_min_auto_replay_recursive_call_pressure: self.benchmark_min_auto_replay_recursive_call_pressure,
            benchmark_max_auto_replay_recursive_call_pressure: self.benchmark_max_auto_replay_recursive_call_pressure,
            benchmark_min_auto_replay_runtime_kv_budget_pressure_items: self
                .benchmark_min_auto_replay_runtime_kv_budget_pressure_items,
            benchmark_min_auto_replay_runtime_kv_budget_pressure: self
                .benchmark_min_auto_replay_runtime_kv_budget_pressure,
            benchmark_max_auto_replay_runtime_kv_budget_pressure: self
                .benchmark_max_auto_replay_runtime_kv_budget_pressure,
            benchmark_min_auto_replay_runtime_kv_weak_import_pressure_items: self
                .benchmark_min_auto_replay_runtime_kv_weak_import_pressure_items,
            benchmark_min_auto_replay_runtime_kv_weak_import_pressure: self
                .benchmark_min_auto_replay_runtime_kv_weak_import_pressure,
            benchmark_max_auto_replay_runtime_kv_weak_import_pressure: self
                .benchmark_max_auto_replay_runtime_kv_weak_import_pressure,
            benchmark_min_evolution_live_inference_runs: self.benchmark_min_evolution_live_inference_runs,
            benchmark_min_evolution_live_router_threshold_mutations: self.benchmark_min_evolution_live_router_threshold_mutations,
            benchmark_min_evolution_live_hierarchy_weight_mutations: self.benchmark_min_evolution_live_hierarchy_weight_mutations,
            benchmark_min_evolution_live_router_threshold_delta: self.benchmark_min_evolution_live_router_threshold_delta,
            benchmark_min_evolution_live_hierarchy_weight_delta: self.benchmark_min_evolution_live_hierarchy_weight_delta,
            benchmark_min_evolution_live_online_reward_feedbacks: self.benchmark_min_evolution_live_online_reward_feedbacks,
            benchmark_min_evolution_live_online_reward_reinforcements: self.benchmark_min_evolution_live_online_reward_reinforcements,
            benchmark_min_evolution_live_online_reward_penalties: self.benchmark_min_evolution_live_online_reward_penalties,
            benchmark_min_evolution_live_online_reward_strength: self.benchmark_min_evolution_live_online_reward_strength,
            benchmark_min_evolution_live_online_reward_reinforcement_strength: self.benchmark_min_evolution_live_online_reward_reinforcement_strength,
            benchmark_min_evolution_live_online_reward_penalty_strength: self.benchmark_min_evolution_live_online_reward_penalty_strength,
            benchmark_min_evolution_live_memory_updates: self.benchmark_min_evolution_live_memory_updates,
            benchmark_min_evolution_live_stored_memory_updates: self.benchmark_min_evolution_live_stored_memory_updates,
            benchmark_min_evolution_live_reflection_issues: self.benchmark_min_evolution_live_reflection_issues,
            benchmark_min_evolution_live_critical_reflection_issues: self.benchmark_min_evolution_live_critical_reflection_issues,
            benchmark_min_evolution_live_revision_actions: self.benchmark_min_evolution_live_revision_actions,
            benchmark_min_evolution_live_inference_device_profiles: self.benchmark_min_evolution_live_inference_device_profiles,
            benchmark_min_evolution_live_router_threshold_mutation_device_profiles: self.benchmark_min_evolution_live_router_threshold_mutation_device_profiles,
            benchmark_min_evolution_live_hierarchy_weight_mutation_device_profiles: self.benchmark_min_evolution_live_hierarchy_weight_mutation_device_profiles,
            benchmark_min_evolution_live_online_reward_device_profiles: self.benchmark_min_evolution_live_online_reward_device_profiles,
            benchmark_min_evolution_live_online_reward_strength_device_profiles: self.benchmark_min_evolution_live_online_reward_strength_device_profiles,
            benchmark_min_evolution_live_memory_update_device_profiles: self.benchmark_min_evolution_live_memory_update_device_profiles,
            benchmark_min_evolution_live_stored_memory_update_device_profiles: self.benchmark_min_evolution_live_stored_memory_update_device_profiles,
            benchmark_min_evolution_live_reflection_issue_device_profiles: self.benchmark_min_evolution_live_reflection_issue_device_profiles,
            benchmark_min_evolution_live_critical_reflection_issue_device_profiles: self.benchmark_min_evolution_live_critical_reflection_issue_device_profiles,
            benchmark_min_evolution_live_revision_action_device_profiles: self.benchmark_min_evolution_live_revision_action_device_profiles,
            benchmark_min_evolution_replay_runs: self.benchmark_min_evolution_replay_runs,
            benchmark_min_evolution_replay_items: self.benchmark_min_evolution_replay_items,
            benchmark_min_evolution_router_threshold_mutations: self.benchmark_min_evolution_router_threshold_mutations,
            benchmark_min_evolution_hierarchy_weight_mutations: self.benchmark_min_evolution_hierarchy_weight_mutations,
            benchmark_min_evolution_router_threshold_delta: self.benchmark_min_evolution_router_threshold_delta,
            benchmark_min_evolution_hierarchy_weight_delta: self.benchmark_min_evolution_hierarchy_weight_delta,
            benchmark_min_evolution_memory_updates: self.benchmark_min_evolution_memory_updates,
            benchmark_min_evolution_replay_live_memory_feedback_updates: self.benchmark_min_evolution_replay_live_memory_feedback_updates,
            benchmark_min_evolution_replay_live_memory_feedback_detail_items: self.benchmark_min_evolution_replay_live_memory_feedback_detail_items,
            benchmark_min_evolution_replay_live_memory_feedback_applied: self.benchmark_min_evolution_replay_live_memory_feedback_applied,
            benchmark_min_evolution_replay_live_memory_feedback_strength_delta: self.benchmark_min_evolution_replay_live_memory_feedback_strength_delta,
            benchmark_min_evolution_replay_rust_check_items: self.benchmark_min_evolution_replay_rust_check_items,
            benchmark_min_evolution_replay_rust_check_passed: self.benchmark_min_evolution_replay_rust_check_passed,
            benchmark_max_evolution_replay_rust_check_failed: self.benchmark_max_evolution_replay_rust_check_failed,
            benchmark_min_evolution_replay_rust_check_live_memory_feedback_updates: self.benchmark_min_evolution_replay_rust_check_live_memory_feedback_updates,
            benchmark_min_evolution_replay_rust_check_live_memory_feedback_applied: self.benchmark_min_evolution_replay_rust_check_live_memory_feedback_applied,
            benchmark_min_evolution_replay_rust_check_live_memory_feedback_strength_delta: self.benchmark_min_evolution_replay_rust_check_live_memory_feedback_strength_delta,
            benchmark_min_evolution_replay_live_evolution_items: self.benchmark_min_evolution_replay_live_evolution_items,
            benchmark_min_evolution_replay_live_evolution_online_reward_feedbacks: self.benchmark_min_evolution_replay_live_evolution_online_reward_feedbacks,
            benchmark_min_evolution_replay_live_evolution_online_reward_reinforcements: self.benchmark_min_evolution_replay_live_evolution_online_reward_reinforcements,
            benchmark_min_evolution_replay_live_evolution_online_reward_penalties: self.benchmark_min_evolution_replay_live_evolution_online_reward_penalties,
            benchmark_min_evolution_replay_live_evolution_online_reward_strength: self.benchmark_min_evolution_replay_live_evolution_online_reward_strength,
            benchmark_min_evolution_replay_live_evolution_online_reward_reinforcement_strength: self.benchmark_min_evolution_replay_live_evolution_online_reward_reinforcement_strength,
            benchmark_min_evolution_replay_live_evolution_online_reward_penalty_strength: self.benchmark_min_evolution_replay_live_evolution_online_reward_penalty_strength,
            benchmark_min_evolution_replay_live_evolution_memory_updates: self.benchmark_min_evolution_replay_live_evolution_memory_updates,
            benchmark_min_evolution_replay_live_evolution_stored_memory_updates: self.benchmark_min_evolution_replay_live_evolution_stored_memory_updates,
            benchmark_min_evolution_replay_live_evolution_reflection_issues: self.benchmark_min_evolution_replay_live_evolution_reflection_issues,
            benchmark_min_evolution_replay_live_evolution_critical_reflection_issues: self.benchmark_min_evolution_replay_live_evolution_critical_reflection_issues,
            benchmark_min_evolution_replay_live_evolution_revision_actions: self.benchmark_min_evolution_replay_live_evolution_revision_actions,
            benchmark_min_evolution_replay_live_evolution_device_profiles: self.benchmark_min_evolution_replay_live_evolution_device_profiles,
            benchmark_min_evolution_replay_live_evolution_online_reward_device_profiles: self.benchmark_min_evolution_replay_live_evolution_online_reward_device_profiles,
            benchmark_min_evolution_replay_live_evolution_online_reward_strength_device_profiles: self.benchmark_min_evolution_replay_live_evolution_online_reward_strength_device_profiles,
            benchmark_min_evolution_replay_live_evolution_memory_update_device_profiles: self.benchmark_min_evolution_replay_live_evolution_memory_update_device_profiles,
            benchmark_min_evolution_replay_live_evolution_critical_reflection_issue_device_profiles: self.benchmark_min_evolution_replay_live_evolution_critical_reflection_issue_device_profiles,
            benchmark_min_evolution_replay_live_evolution_revision_action_device_profiles: self.benchmark_min_evolution_replay_live_evolution_revision_action_device_profiles,
            benchmark_min_evolution_recursive_replay_items: self.benchmark_min_evolution_recursive_replay_items,
            benchmark_min_evolution_recursive_runtime_calls: self.benchmark_min_evolution_recursive_runtime_calls,
            benchmark_max_evolution_drift_rollbacks: self.benchmark_max_evolution_drift_rollbacks,
            benchmark_max_evolution_rollback_router_threshold_delta: self.benchmark_max_evolution_rollback_router_threshold_delta,
            benchmark_max_evolution_rollback_hierarchy_weight_delta: self.benchmark_max_evolution_rollback_hierarchy_weight_delta,
            benchmark_min_sparse_skipped_cases: self.benchmark_min_sparse_skipped_cases,
            benchmark_min_sparse_skipped_tokens: self.benchmark_min_sparse_skipped_tokens,
            benchmark_min_runtime_forward_cases: self.benchmark_min_runtime_forward_cases,
            benchmark_min_runtime_forward_energy_cases: self.benchmark_min_runtime_forward_energy_cases,
            benchmark_min_runtime_kv_influence_cases: self.benchmark_min_runtime_kv_influence_cases,
            benchmark_min_runtime_architecture_cases: self.benchmark_min_runtime_architecture_cases,
            benchmark_min_runtime_architecture_device_profiles: self.benchmark_min_runtime_architecture_device_profiles,
            benchmark_min_runtime_kv_precision_cases: self.benchmark_min_runtime_kv_precision_cases,
            benchmark_min_runtime_layer_mode_cases: self.benchmark_min_runtime_layer_mode_cases,
            benchmark_min_runtime_all_layer_mode_cases: self.benchmark_min_runtime_all_layer_mode_cases,
            benchmark_min_runtime_global_layers: self.benchmark_min_runtime_global_layers,
            benchmark_min_runtime_local_window_layers: self.benchmark_min_runtime_local_window_layers,
            benchmark_min_runtime_convolutional_fusion_layers: self.benchmark_min_runtime_convolutional_fusion_layers,
            benchmark_min_runtime_uncertainty_cases: self.benchmark_min_runtime_uncertainty_cases,
            benchmark_min_runtime_uncertainty_tokens: self.benchmark_min_runtime_uncertainty_tokens,
            benchmark_min_runtime_uncertainty_device_profiles: self.benchmark_min_runtime_uncertainty_device_profiles,
            benchmark_min_runtime_uncertainty_token_device_profiles: self.benchmark_min_runtime_uncertainty_token_device_profiles,
            benchmark_min_runtime_kv_import_cases: self.benchmark_min_runtime_kv_import_cases,
            benchmark_min_runtime_kv_weak_import_skip_cases: self.benchmark_min_runtime_kv_weak_import_skip_cases,
            benchmark_min_weak_runtime_kv_imports_skipped: self.benchmark_min_weak_runtime_kv_imports_skipped,
            benchmark_min_runtime_kv_weak_import_skip_device_profiles: self
                .benchmark_min_runtime_kv_weak_import_skip_device_profiles,
            benchmark_min_runtime_kv_budget_import_skip_cases: self
                .benchmark_min_runtime_kv_budget_import_skip_cases,
            benchmark_min_budget_limited_runtime_kv_imports_skipped: self
                .benchmark_min_budget_limited_runtime_kv_imports_skipped,
            benchmark_min_runtime_kv_budget_import_skip_device_profiles: self
                .benchmark_min_runtime_kv_budget_import_skip_device_profiles,
            benchmark_min_runtime_kv_budget_pressure_cases: self
                .benchmark_min_runtime_kv_budget_pressure_cases,
            benchmark_min_runtime_kv_budget_pressure_device_profiles: self
                .benchmark_min_runtime_kv_budget_pressure_device_profiles,
            benchmark_min_runtime_kv_segment_cases: self.benchmark_min_runtime_kv_segment_cases,
            benchmark_min_runtime_kv_segments_included: self.benchmark_min_runtime_kv_segments_included,
            benchmark_max_runtime_kv_segments_rejected: self.benchmark_max_runtime_kv_segments_rejected,
            benchmark_min_runtime_kv_segment_device_profiles: self.benchmark_min_runtime_kv_segment_device_profiles,
            benchmark_min_runtime_kv_imported: self.benchmark_min_runtime_kv_imported,
            benchmark_min_runtime_kv_import_device_profiles: self.benchmark_min_runtime_kv_import_device_profiles,
            benchmark_min_runtime_kv_exported: self.benchmark_min_runtime_kv_exported,
            benchmark_min_runtime_kv_export_device_profiles: self.benchmark_min_runtime_kv_export_device_profiles,
            benchmark_min_runtime_kv_stored: self.benchmark_min_runtime_kv_stored,
            benchmark_min_runtime_kv_stored_device_profiles: self.benchmark_min_runtime_kv_stored_device_profiles,
            benchmark_min_runtime_kv_hold_cases: self.benchmark_min_runtime_kv_hold_cases,
            benchmark_min_runtime_kv_held: self.benchmark_min_runtime_kv_held,
            benchmark_min_runtime_kv_hold_device_profiles: self.benchmark_min_runtime_kv_hold_device_profiles,
            benchmark_min_runtime_adapter_contract_cases: self.benchmark_min_runtime_adapter_contract_cases,
            benchmark_min_runtime_adapter_kinds: self.benchmark_min_runtime_adapter_kinds,
            benchmark_min_runtime_adapter_cache_modes: self
                .benchmark_min_runtime_adapter_cache_modes,
            benchmark_min_runtime_adapter_stream_trace_cases: self
                .benchmark_min_runtime_adapter_stream_trace_cases,
            benchmark_min_runtime_adapter_stream_gate_summary_cases: self
                .benchmark_min_runtime_adapter_stream_gate_summary_cases,
            benchmark_min_runtime_adapter_observations: self.benchmark_min_runtime_adapter_observations,
            benchmark_min_runtime_adapter_current_signals: self
                .benchmark_min_runtime_adapter_current_signals,
            benchmark_min_runtime_adapter_best_score: self.benchmark_min_runtime_adapter_best_score,
            benchmark_max_runtime_adapter_contract_violations: self.benchmark_max_runtime_adapter_contract_violations,
            benchmark_max_runtime_adapter_selection_mismatches: self.benchmark_max_runtime_adapter_selection_mismatches,
            benchmark_min_runtime_embedding_cases: self.benchmark_min_runtime_embedding_cases,
            benchmark_min_runtime_embedding_device_profiles: self.benchmark_min_runtime_embedding_device_profiles,
            benchmark_max_embedding_fallback_cases: self.benchmark_max_embedding_fallback_cases,
            benchmark_max_embedding_evidence_failures: self.benchmark_max_embedding_evidence_failures,
            benchmark_min_runtime_device_execution_cases: self.benchmark_min_runtime_device_execution_cases,
            benchmark_min_runtime_device_execution_device_profiles: self.benchmark_min_runtime_device_execution_device_profiles,
            benchmark_min_runtime_kv_precision_device_profiles: self.benchmark_min_runtime_kv_precision_device_profiles,
            benchmark_max_runtime_device_execution_violations: self.benchmark_max_runtime_device_execution_violations,
            benchmark_max_memory_governance_failures: self.benchmark_max_memory_governance_failures,
            benchmark_min_reasoning_genome_expression_cases: self.benchmark_min_reasoning_genome_expression_cases,
            benchmark_min_reasoning_genome_expression_device_profiles: self.benchmark_min_reasoning_genome_expression_device_profiles,
            benchmark_min_reasoning_genome_splice_cases: self.benchmark_min_reasoning_genome_splice_cases,
            benchmark_min_reasoning_genome_splice_device_profiles: self.benchmark_min_reasoning_genome_splice_device_profiles,
            benchmark_min_gene_scissors_proposal_cases: self.benchmark_min_gene_scissors_proposal_cases,
            benchmark_min_gene_scissors_proposal_device_profiles: self.benchmark_min_gene_scissors_proposal_device_profiles,
            benchmark_min_reasoning_genome_repair_payloads: self.benchmark_min_reasoning_genome_repair_payloads,
            benchmark_min_reasoning_genome_regeneration_payloads: self.benchmark_min_reasoning_genome_regeneration_payloads,
            benchmark_min_mutation_repair_fixtures: self.benchmark_min_mutation_repair_fixtures,
            benchmark_min_mutation_repair_fixture_kinds: self
                .benchmark_min_mutation_repair_fixture_kinds,
            benchmark_min_mutation_repair_candidates: self
                .benchmark_min_mutation_repair_candidates,
            benchmark_min_mutation_repair_review_packets: self
                .benchmark_min_mutation_repair_review_packets,
            benchmark_min_malignant_gene_recovery_drills: self
                .benchmark_min_malignant_gene_recovery_drills,
            benchmark_min_malignant_gene_quarantines: self
                .benchmark_min_malignant_gene_quarantines,
            benchmark_min_malignant_gene_cut_candidates: self
                .benchmark_min_malignant_gene_cut_candidates,
            benchmark_min_malignant_gene_regeneration_candidates: self
                .benchmark_min_malignant_gene_regeneration_candidates,
            benchmark_min_dna_evolution_reports: self.benchmark_min_dna_evolution_reports,
            benchmark_min_dna_evolution_candidates: self.benchmark_min_dna_evolution_candidates,
            benchmark_min_dna_evolution_candidate_previews: self
                .benchmark_min_dna_evolution_candidate_previews,
            benchmark_max_dna_evolution_activation_eligible: self
                .benchmark_max_dna_evolution_activation_eligible,
            benchmark_min_dna_evolution_transaction_replays: self
                .benchmark_min_dna_evolution_transaction_replays,
            benchmark_min_dna_evolution_replay_passed: self
                .benchmark_min_dna_evolution_replay_passed,
            benchmark_min_dna_evolution_validation_passed: self
                .benchmark_min_dna_evolution_validation_passed,
            benchmark_min_dna_evolution_writer_gate_reports: self
                .benchmark_min_dna_evolution_writer_gate_reports,
            benchmark_min_dna_evolution_writer_gate_holds: self
                .benchmark_min_dna_evolution_writer_gate_holds,
            benchmark_min_dna_evolution_writer_gate_explicit_apply_required: self
                .benchmark_min_dna_evolution_writer_gate_explicit_apply_required,
            benchmark_max_dna_evolution_writer_gate_ready: self
                .benchmark_max_dna_evolution_writer_gate_ready,
            benchmark_max_dna_evolution_writer_gate_durable_write_allowed: self
                .benchmark_max_dna_evolution_writer_gate_durable_write_allowed,
            benchmark_min_memory_governance_cases: self.benchmark_min_memory_governance_cases,
            benchmark_min_memory_governance_device_profiles: self.benchmark_min_memory_governance_device_profiles,
            benchmark_min_memory_retention_activity_cases: self.benchmark_min_memory_retention_activity_cases,
            benchmark_min_memory_compaction_activity_cases: self.benchmark_min_memory_compaction_activity_cases,
            benchmark_min_reflection_issue_cases: self.benchmark_min_reflection_issue_cases,
            benchmark_min_reflection_issues: self.benchmark_min_reflection_issues,
            benchmark_min_critical_reflection_issue_cases: self.benchmark_min_critical_reflection_issue_cases,
            benchmark_min_critical_reflection_issues: self.benchmark_min_critical_reflection_issues,
            benchmark_min_revision_action_cases: self.benchmark_min_revision_action_cases,
            benchmark_min_revision_actions: self.benchmark_min_revision_actions,
            benchmark_min_reflection_issue_device_profiles: self.benchmark_min_reflection_issue_device_profiles,
            benchmark_min_critical_reflection_issue_device_profiles: self.benchmark_min_critical_reflection_issue_device_profiles,
            benchmark_min_revision_action_device_profiles: self.benchmark_min_revision_action_device_profiles,
            benchmark_min_device_profiles: self.benchmark_min_device_profiles,
            benchmark_min_recursive_device_profiles: self.benchmark_min_recursive_device_profiles,
            benchmark_max_drift_blocks: self.benchmark_max_drift_blocks,
            benchmark_max_drift_rollbacks: self.benchmark_max_drift_rollbacks,
            benchmark_roundtrip: self.benchmark_roundtrip,
            serve: self.serve,
            serve_bind: self.serve_bind,
            serve_max_requests: self.serve_max_requests,
            model_pool_manifest_path: self.model_pool_manifest_path,
            list_devices: self.list_devices,
            probe_device: self.probe_device,
            device_gate: self.device_gate,
            kv_quant_gate: self.kv_quant_gate,
            kv_quant_max_total_us: self.kv_quant_max_total_us,
            runtime_manifest_gate: self.runtime_manifest_gate,
            runtime_manifest_all_devices_gate: self.runtime_manifest_all_devices_gate,
            runtime_weights_path: self.runtime_weights_path,
            runtime_tokenizer_path: self.runtime_tokenizer_path,
            runtime_config_path: self.runtime_config_path,
            runtime_layer_count: self.runtime_layer_count,
            runtime_hidden_size: self.runtime_hidden_size,
            runtime_attention_heads: self.runtime_attention_heads,
            runtime_kv_heads: self.runtime_kv_heads,
            runtime_local_window_tokens: self.runtime_local_window_tokens,
            runtime_timeout_ms: self.runtime_timeout_ms,
            runtime_stream_idle_timeout_ms: self.runtime_stream_idle_timeout_ms,
            inspect_state: self.inspect_state,
            inspect_limit: self.inspect_limit,
            inspect_gate: self.inspect_gate,
            inspect_min_memories: self.inspect_min_memories,
            inspect_min_runtime_kv_memories: self.inspect_min_runtime_kv_memories,
            inspect_min_experiences: self.inspect_min_experiences,
            inspect_max_experience_hygiene_quarantine_candidates: self
                .inspect_max_experience_hygiene_quarantine_candidates,
            inspect_max_experience_repairable_legacy_metadata_lessons: self
                .inspect_max_experience_repairable_legacy_metadata_lessons,
            inspect_max_experience_repairable_index_records: self
                .inspect_max_experience_repairable_index_records,
            inspect_max_experience_repair_projected_legacy_metadata_lessons: self
                .inspect_max_experience_repair_projected_legacy_metadata_lessons,
            inspect_max_experience_repair_skipped_missing_clean_gist: self
                .inspect_max_experience_repair_skipped_missing_clean_gist,
            inspect_max_experience_index_overlong_records: self
                .inspect_max_experience_index_overlong_records,
            inspect_max_experience_index_overlong_without_clean_gist: self
                .inspect_max_experience_index_overlong_without_clean_gist,
            inspect_max_experience_index_record_chars: self
                .inspect_max_experience_index_record_chars,
            inspect_max_experience_index_noisy_records: self
                .inspect_max_experience_index_noisy_records,
            inspect_max_experience_index_noise_penalty: self
                .inspect_max_experience_index_noise_penalty,
            inspect_min_experience_index_quality_score: self
                .inspect_min_experience_index_quality_score,
            inspect_require_experience_index_retrieval_ready: self
                .inspect_require_experience_index_retrieval_ready,
            inspect_min_runtime_model_experiences: self.inspect_min_runtime_model_experiences,
            inspect_min_runtime_adapter_experiences: self.inspect_min_runtime_adapter_experiences,
            inspect_max_runtime_adapter_selection_mismatches: self.inspect_max_runtime_adapter_selection_mismatches,
            inspect_min_runtime_forward_energy_experiences: self.inspect_min_runtime_forward_energy_experiences,
            inspect_min_runtime_kv_influence_experiences: self.inspect_min_runtime_kv_influence_experiences,
            inspect_min_runtime_tokens: self.inspect_min_runtime_tokens,
            inspect_min_runtime_uncertainty_experiences: self.inspect_min_runtime_uncertainty_experiences,
            inspect_min_runtime_uncertainty_tokens: self.inspect_min_runtime_uncertainty_tokens,
            inspect_min_runtime_architecture_experiences: self.inspect_min_runtime_architecture_experiences,
            inspect_min_runtime_kv_precision_experiences: self.inspect_min_runtime_kv_precision_experiences,
            inspect_max_runtime_kv_precision_mismatches: self.inspect_max_runtime_kv_precision_mismatches,
            inspect_max_runtime_errors: self.inspect_max_runtime_errors,
            inspect_max_runtime_timeouts: self.inspect_max_runtime_timeouts,
            inspect_min_runtime_device_execution_experiences: self.inspect_min_runtime_device_execution_experiences,
            inspect_min_runtime_layer_mode_experiences: self.inspect_min_runtime_layer_mode_experiences,
            inspect_min_runtime_all_layer_mode_experiences: self.inspect_min_runtime_all_layer_mode_experiences,
            inspect_min_runtime_global_layers: self.inspect_min_runtime_global_layers,
            inspect_min_runtime_local_window_layers: self.inspect_min_runtime_local_window_layers,
            inspect_min_runtime_convolutional_fusion_layers: self.inspect_min_runtime_convolutional_fusion_layers,
            inspect_min_runtime_kv_import_experiences: self.inspect_min_runtime_kv_import_experiences,
            inspect_min_runtime_kv_weak_import_skip_experiences: self.inspect_min_runtime_kv_weak_import_skip_experiences,
            inspect_min_weak_runtime_kv_imports_skipped: self.inspect_min_weak_runtime_kv_imports_skipped,
            inspect_min_runtime_kv_weak_import_pressure_experiences: self
                .inspect_min_runtime_kv_weak_import_pressure_experiences,
            inspect_min_runtime_kv_weak_import_pressure: self
                .inspect_min_runtime_kv_weak_import_pressure,
            inspect_max_runtime_kv_weak_import_pressure: self
                .inspect_max_runtime_kv_weak_import_pressure,
            inspect_min_runtime_kv_budget_import_skip_experiences: self
                .inspect_min_runtime_kv_budget_import_skip_experiences,
            inspect_min_budget_limited_runtime_kv_imports_skipped: self
                .inspect_min_budget_limited_runtime_kv_imports_skipped,
            inspect_min_runtime_kv_budget_pressure_experiences: self
                .inspect_min_runtime_kv_budget_pressure_experiences,
            inspect_min_runtime_kv_budget_pressure: self.inspect_min_runtime_kv_budget_pressure,
            inspect_max_runtime_kv_budget_pressure: self.inspect_max_runtime_kv_budget_pressure,
            inspect_min_runtime_kv_export_experiences: self.inspect_min_runtime_kv_export_experiences,
            inspect_min_runtime_kv_segment_experiences: self.inspect_min_runtime_kv_segment_experiences,
            inspect_min_runtime_kv_segments_included: self.inspect_min_runtime_kv_segments_included,
            inspect_max_runtime_kv_segments_rejected: self.inspect_max_runtime_kv_segments_rejected,
            inspect_min_runtime_kv_hold_experiences: self.inspect_min_runtime_kv_hold_experiences,
            inspect_min_runtime_kv_held_blocks: self.inspect_min_runtime_kv_held_blocks,
            inspect_min_runtime_kv_memory_device_profiles: self.inspect_min_runtime_kv_memory_device_profiles,
            inspect_min_runtime_model_device_profiles: self.inspect_min_runtime_model_device_profiles,
            inspect_min_runtime_adapter_device_profiles: self.inspect_min_runtime_adapter_device_profiles,
            inspect_min_runtime_forward_energy_device_profiles: self.inspect_min_runtime_forward_energy_device_profiles,
            inspect_min_runtime_kv_influence_device_profiles: self.inspect_min_runtime_kv_influence_device_profiles,
            inspect_min_runtime_uncertainty_device_profiles: self.inspect_min_runtime_uncertainty_device_profiles,
            inspect_min_runtime_uncertainty_token_device_profiles: self.inspect_min_runtime_uncertainty_token_device_profiles,
            inspect_min_runtime_kv_precision_device_profiles: self.inspect_min_runtime_kv_precision_device_profiles,
            inspect_min_runtime_device_execution_device_profiles: self.inspect_min_runtime_device_execution_device_profiles,
            inspect_min_runtime_layer_mode_device_profiles: self.inspect_min_runtime_layer_mode_device_profiles,
            inspect_min_runtime_all_layer_mode_device_profiles: self.inspect_min_runtime_all_layer_mode_device_profiles,
            inspect_min_runtime_kv_import_device_profiles: self.inspect_min_runtime_kv_import_device_profiles,
            inspect_min_runtime_kv_weak_import_skip_device_profiles: self
                .inspect_min_runtime_kv_weak_import_skip_device_profiles,
            inspect_min_runtime_kv_budget_import_skip_device_profiles: self
                .inspect_min_runtime_kv_budget_import_skip_device_profiles,
            inspect_min_runtime_kv_budget_pressure_device_profiles: self
                .inspect_min_runtime_kv_budget_pressure_device_profiles,
            inspect_min_runtime_kv_export_device_profiles: self.inspect_min_runtime_kv_export_device_profiles,
            inspect_min_runtime_kv_segment_device_profiles: self
                .inspect_min_runtime_kv_segment_device_profiles,
            inspect_min_runtime_kv_hold_device_profiles: self.inspect_min_runtime_kv_hold_device_profiles,
            inspect_min_reflection_issue_experiences: self.inspect_min_reflection_issue_experiences,
            inspect_min_critical_reflection_issue_experiences: self.inspect_min_critical_reflection_issue_experiences,
            inspect_min_revision_action_experiences: self.inspect_min_revision_action_experiences,
            inspect_min_live_memory_feedback_experiences: self.inspect_min_live_memory_feedback_experiences,
            inspect_min_live_memory_feedback_updates: self.inspect_min_live_memory_feedback_updates,
            inspect_min_live_memory_feedback_detail_experiences: self.inspect_min_live_memory_feedback_detail_experiences,
            inspect_min_live_memory_feedback_applied: self.inspect_min_live_memory_feedback_applied,
            inspect_min_live_memory_feedback_strength_delta: self.inspect_min_live_memory_feedback_strength_delta,
            inspect_min_rust_check_experiences: self.inspect_min_rust_check_experiences,
            inspect_min_rust_check_passed: self.inspect_min_rust_check_passed,
            inspect_max_rust_check_failed: self.inspect_max_rust_check_failed,
            inspect_min_rust_check_diagnostic_chars: self.inspect_min_rust_check_diagnostic_chars,
            inspect_min_reflection_issue_device_profiles: self.inspect_min_reflection_issue_device_profiles,
            inspect_min_critical_reflection_issue_device_profiles: self.inspect_min_critical_reflection_issue_device_profiles,
            inspect_min_revision_action_device_profiles: self.inspect_min_revision_action_device_profiles,
            inspect_min_live_memory_feedback_device_profiles: self.inspect_min_live_memory_feedback_device_profiles,
            inspect_min_evolution_live_inference_device_profiles: self.inspect_min_evolution_live_inference_device_profiles,
            inspect_min_evolution_live_router_threshold_mutation_device_profiles: self.inspect_min_evolution_live_router_threshold_mutation_device_profiles,
            inspect_min_evolution_live_hierarchy_weight_mutation_device_profiles: self.inspect_min_evolution_live_hierarchy_weight_mutation_device_profiles,
            inspect_min_evolution_live_online_reward_device_profiles: self.inspect_min_evolution_live_online_reward_device_profiles,
            inspect_min_evolution_live_online_reward_strength_device_profiles: self.inspect_min_evolution_live_online_reward_strength_device_profiles,
            inspect_min_evolution_live_memory_update_device_profiles: self.inspect_min_evolution_live_memory_update_device_profiles,
            inspect_min_evolution_live_stored_memory_update_device_profiles: self.inspect_min_evolution_live_stored_memory_update_device_profiles,
            inspect_min_evolution_live_reflection_issue_device_profiles: self.inspect_min_evolution_live_reflection_issue_device_profiles,
            inspect_min_evolution_live_critical_reflection_issue_device_profiles: self.inspect_min_evolution_live_critical_reflection_issue_device_profiles,
            inspect_min_evolution_live_revision_action_device_profiles: self.inspect_min_evolution_live_revision_action_device_profiles,
            inspect_min_evolution_replay_run_device_profiles: self.inspect_min_evolution_replay_run_device_profiles,
            inspect_min_evolution_replay_item_device_profiles: self.inspect_min_evolution_replay_item_device_profiles,
            inspect_min_evolution_router_threshold_mutation_device_profiles: self.inspect_min_evolution_router_threshold_mutation_device_profiles,
            inspect_min_evolution_hierarchy_weight_mutation_device_profiles: self.inspect_min_evolution_hierarchy_weight_mutation_device_profiles,
            inspect_min_evolution_memory_update_device_profiles: self.inspect_min_evolution_memory_update_device_profiles,
            inspect_min_evolution_replay_live_memory_feedback_device_profiles: self.inspect_min_evolution_replay_live_memory_feedback_device_profiles,
            inspect_min_evolution_replay_live_memory_feedback_detail_device_profiles: self.inspect_min_evolution_replay_live_memory_feedback_detail_device_profiles,
            inspect_min_evolution_replay_live_evolution_device_profiles: self.inspect_min_evolution_replay_live_evolution_device_profiles,
            inspect_min_evolution_replay_live_evolution_online_reward_device_profiles: self.inspect_min_evolution_replay_live_evolution_online_reward_device_profiles,
            inspect_min_evolution_replay_live_evolution_online_reward_strength_device_profiles: self.inspect_min_evolution_replay_live_evolution_online_reward_strength_device_profiles,
            inspect_min_evolution_replay_live_evolution_memory_update_device_profiles: self.inspect_min_evolution_replay_live_evolution_memory_update_device_profiles,
            inspect_min_evolution_replay_live_evolution_critical_reflection_issue_device_profiles: self.inspect_min_evolution_replay_live_evolution_critical_reflection_issue_device_profiles,
            inspect_min_evolution_replay_live_evolution_revision_action_device_profiles: self.inspect_min_evolution_replay_live_evolution_revision_action_device_profiles,
            inspect_min_evolution_recursive_replay_device_profiles: self.inspect_min_evolution_recursive_replay_device_profiles,
            inspect_min_evolution_recursive_runtime_call_device_profiles: self.inspect_min_evolution_recursive_runtime_call_device_profiles,
            inspect_min_router_observations: self.inspect_min_router_observations,
            inspect_min_evolution_live_inference_runs: self.inspect_min_evolution_live_inference_runs,
            inspect_min_evolution_live_router_threshold_mutations: self.inspect_min_evolution_live_router_threshold_mutations,
            inspect_min_evolution_live_hierarchy_weight_mutations: self.inspect_min_evolution_live_hierarchy_weight_mutations,
            inspect_min_evolution_live_router_threshold_delta: self.inspect_min_evolution_live_router_threshold_delta,
            inspect_min_evolution_live_hierarchy_weight_delta: self.inspect_min_evolution_live_hierarchy_weight_delta,
            inspect_min_evolution_live_online_reward_feedbacks: self.inspect_min_evolution_live_online_reward_feedbacks,
            inspect_min_evolution_live_online_reward_reinforcements: self.inspect_min_evolution_live_online_reward_reinforcements,
            inspect_min_evolution_live_online_reward_penalties: self.inspect_min_evolution_live_online_reward_penalties,
            inspect_min_evolution_live_online_reward_strength: self.inspect_min_evolution_live_online_reward_strength,
            inspect_min_evolution_live_online_reward_reinforcement_strength: self.inspect_min_evolution_live_online_reward_reinforcement_strength,
            inspect_min_evolution_live_online_reward_penalty_strength: self.inspect_min_evolution_live_online_reward_penalty_strength,
            inspect_min_evolution_live_memory_updates: self.inspect_min_evolution_live_memory_updates,
            inspect_min_evolution_live_stored_memory_updates: self.inspect_min_evolution_live_stored_memory_updates,
            inspect_min_evolution_live_reflection_issues: self.inspect_min_evolution_live_reflection_issues,
            inspect_min_evolution_live_critical_reflection_issues: self.inspect_min_evolution_live_critical_reflection_issues,
            inspect_min_evolution_live_revision_actions: self.inspect_min_evolution_live_revision_actions,
            inspect_min_evolution_replay_runs: self.inspect_min_evolution_replay_runs,
            inspect_min_evolution_replay_items: self.inspect_min_evolution_replay_items,
            inspect_min_evolution_router_threshold_mutations: self.inspect_min_evolution_router_threshold_mutations,
            inspect_min_evolution_hierarchy_weight_mutations: self.inspect_min_evolution_hierarchy_weight_mutations,
            inspect_min_evolution_router_threshold_delta: self.inspect_min_evolution_router_threshold_delta,
            inspect_min_evolution_hierarchy_weight_delta: self.inspect_min_evolution_hierarchy_weight_delta,
            inspect_min_evolution_memory_updates: self.inspect_min_evolution_memory_updates,
            inspect_min_evolution_external_feedbacks: self.inspect_min_evolution_external_feedbacks,
            inspect_min_evolution_external_feedback_memory_updates: self.inspect_min_evolution_external_feedback_memory_updates,
            inspect_min_evolution_external_feedback_strength_delta: self.inspect_min_evolution_external_feedback_strength_delta,
            inspect_min_evolution_replay_live_memory_feedback_updates: self.inspect_min_evolution_replay_live_memory_feedback_updates,
            inspect_min_evolution_replay_live_memory_feedback_detail_items: self.inspect_min_evolution_replay_live_memory_feedback_detail_items,
            inspect_min_evolution_replay_live_memory_feedback_applied: self.inspect_min_evolution_replay_live_memory_feedback_applied,
            inspect_min_evolution_replay_live_memory_feedback_strength_delta: self.inspect_min_evolution_replay_live_memory_feedback_strength_delta,
            inspect_min_evolution_replay_rust_check_items: self.inspect_min_evolution_replay_rust_check_items,
            inspect_min_evolution_replay_rust_check_passed: self.inspect_min_evolution_replay_rust_check_passed,
            inspect_max_evolution_replay_rust_check_failed: self.inspect_max_evolution_replay_rust_check_failed,
            inspect_min_evolution_replay_rust_check_live_memory_feedback_updates: self.inspect_min_evolution_replay_rust_check_live_memory_feedback_updates,
            inspect_min_evolution_replay_rust_check_live_memory_feedback_applied: self.inspect_min_evolution_replay_rust_check_live_memory_feedback_applied,
            inspect_min_evolution_replay_rust_check_live_memory_feedback_strength_delta: self.inspect_min_evolution_replay_rust_check_live_memory_feedback_strength_delta,
            inspect_min_evolution_replay_live_evolution_items: self.inspect_min_evolution_replay_live_evolution_items,
            inspect_min_evolution_replay_live_evolution_online_reward_feedbacks: self.inspect_min_evolution_replay_live_evolution_online_reward_feedbacks,
            inspect_min_evolution_replay_live_evolution_online_reward_reinforcements: self.inspect_min_evolution_replay_live_evolution_online_reward_reinforcements,
            inspect_min_evolution_replay_live_evolution_online_reward_penalties: self.inspect_min_evolution_replay_live_evolution_online_reward_penalties,
            inspect_min_evolution_replay_live_evolution_online_reward_strength: self.inspect_min_evolution_replay_live_evolution_online_reward_strength,
            inspect_min_evolution_replay_live_evolution_online_reward_reinforcement_strength: self.inspect_min_evolution_replay_live_evolution_online_reward_reinforcement_strength,
            inspect_min_evolution_replay_live_evolution_online_reward_penalty_strength: self.inspect_min_evolution_replay_live_evolution_online_reward_penalty_strength,
            inspect_min_evolution_replay_live_evolution_memory_updates: self.inspect_min_evolution_replay_live_evolution_memory_updates,
            inspect_min_evolution_replay_live_evolution_stored_memory_updates: self.inspect_min_evolution_replay_live_evolution_stored_memory_updates,
            inspect_min_evolution_replay_live_evolution_reflection_issues: self.inspect_min_evolution_replay_live_evolution_reflection_issues,
            inspect_min_evolution_replay_live_evolution_critical_reflection_issues: self.inspect_min_evolution_replay_live_evolution_critical_reflection_issues,
            inspect_min_evolution_replay_live_evolution_revision_actions: self.inspect_min_evolution_replay_live_evolution_revision_actions,
            inspect_min_evolution_recursive_replay_items: self.inspect_min_evolution_recursive_replay_items,
            inspect_min_evolution_recursive_runtime_calls: self.inspect_min_evolution_recursive_runtime_calls,
            inspect_max_evolution_drift_rollbacks: self.inspect_max_evolution_drift_rollbacks,
            inspect_max_evolution_rollback_router_threshold_delta: self.inspect_max_evolution_rollback_router_threshold_delta,
            inspect_max_evolution_rollback_hierarchy_weight_delta: self.inspect_max_evolution_rollback_hierarchy_weight_delta,
            inspect_require_runtime_kv_dimensions: self.inspect_require_runtime_kv_dimensions,
            local_runtime: self.local_runtime,
            production_runtime: self.production_runtime,
            production_reference_kernel: self.production_reference_kernel,
            production_local_kernel: self.production_local_kernel,
            production_kernel_conformance_gate: self.production_kernel_conformance_gate,
            production_kernel_conformance_all_devices_gate: self.production_kernel_conformance_all_devices_gate,
            gemma_business_smoke: self.gemma_business_smoke,
            gemma_business_cycle_smoke: self.gemma_business_cycle_smoke,
            gemma_business_regression_gate_path: self.gemma_business_regression_gate_path,
            gemma_business_cycle_smoke_report_gate_path: self.gemma_business_cycle_smoke_report_gate_path,
            gemma_model_service_smoke: self.gemma_model_service_smoke,
            gemma_smoke_check_only: self.gemma_smoke_check_only,
            gemma_smoke_keep_runs: self.gemma_smoke_keep_runs,
            gemma_12b_runtime: self.gemma_runtime.enabled,
            gemma_runtime_program: self.gemma_runtime.program,
            gemma_runtime_server: self.gemma_runtime.server,
            gemma_runtime_quantization: self.gemma_runtime.quantization,
            gemma_runtime_quantization_mode: self.gemma_runtime.quantization_mode,
            gemma_runtime_token_source: self.gemma_runtime.token_source,
            gemma_runtime_paged_attn: self.gemma_runtime.paged_attn,
            gemma_runtime_thinking: self.gemma_runtime.thinking,
            gemma_runtime_hf_cache: self.gemma_runtime.hf_cache,
            runtime_command: self.runtime_command,
            runtime_args: self.runtime_args,
            runtime_prompt_mode: self.runtime_prompt_mode,
            runtime_wire_format: self.runtime_wire_format,
            runtime_metadata: self.runtime_metadata,
            native_window_tokens: self.native_window_tokens,
            chunk_tokens: self.chunk_tokens,
            chunk_overlap_tokens: self.chunk_overlap_tokens,
            merge_fan_in: self.merge_fan_in,
            replay_limit: self.replay_limit,
            auto_replay_limit: self.auto_replay_limit,
            retention_stale_after: self.retention_stale_after,
            retention_decay_rate: self.retention_decay_rate,
            retention_remove_below: self.retention_remove_below,
            retention_remove_after_failures: self.retention_remove_after_failures,
            compaction_similarity_threshold: self.compaction_similarity_threshold,
            compaction_max_candidates: self.compaction_max_candidates,
            compaction_max_merges: self.compaction_max_merges,
            device: self.device,
            device_flag_provided: self.device_flag_provided,
            auto_device_probe: self.auto_device_probe,
            cpu_load_override: self.cpu_load_set,
            gpu_load_override: self.gpu_load_set,
            ram_load_override: self.ram_load_set,
            disk_load_override: self.disk_load_set,
            cpu_load: self.cpu_load,
            gpu_load: self.gpu_load,
            ram_load: self.ram_load,
            disk_load: self.disk_load,
        }
    }
}
