use crate::experience_replay::ExperienceReplayReport;

#[derive(Debug, Clone, Copy, Default)]
pub(super) struct AutoReplayTraceFields {
    pub applied: usize,
    pub router_updates: usize,
    pub hierarchy_updates: usize,
    pub router_threshold_mutations: usize,
    pub hierarchy_weight_mutations: usize,
    pub router_threshold_delta: f32,
    pub hierarchy_weight_delta: f32,
    pub reinforced: usize,
    pub penalized: usize,
    pub touched_memories: usize,
    pub memory_reinforcements: usize,
    pub memory_penalties: usize,
    pub live_memory_feedback_items: usize,
    pub live_memory_feedback_updates: usize,
    pub live_memory_feedback_reinforcements: usize,
    pub live_memory_feedback_penalties: usize,
    pub live_memory_feedback_detail_items: usize,
    pub live_memory_feedback_applied: usize,
    pub live_memory_feedback_removed: usize,
    pub live_memory_feedback_missing: usize,
    pub live_memory_feedback_strength_delta: f32,
    pub business_contract_items: usize,
    pub business_contract_passed: usize,
    pub business_contract_failed: usize,
    pub business_contract_raw_passed: usize,
    pub business_contract_raw_failed: usize,
    pub business_contract_response_normalized: usize,
    pub business_contract_sanitized: usize,
    pub business_contract_canonical_fallbacks: usize,
    pub live_evolution_items: usize,
    pub live_evolution_router_threshold_mutations: usize,
    pub live_evolution_hierarchy_weight_mutations: usize,
    pub live_evolution_router_threshold_delta: f32,
    pub live_evolution_hierarchy_weight_delta: f32,
    pub live_evolution_online_reward_feedbacks: usize,
    pub live_evolution_online_reward_reinforcements: usize,
    pub live_evolution_online_reward_penalties: usize,
    pub live_evolution_online_reward_strength: f32,
    pub live_evolution_online_reward_reinforcement_strength: f32,
    pub live_evolution_online_reward_penalty_strength: f32,
    pub live_evolution_memory_updates: usize,
    pub live_evolution_stored_memory_updates: usize,
    pub live_evolution_reflection_issues: usize,
    pub live_evolution_critical_reflection_issues: usize,
    pub live_evolution_revision_actions: usize,
    pub runtime_kv_budget_pressure_items: usize,
    pub average_runtime_kv_budget_pressure: f32,
    pub max_runtime_kv_budget_pressure: f32,
    pub runtime_kv_weak_import_pressure_items: usize,
    pub average_runtime_kv_weak_import_pressure: f32,
    pub max_runtime_kv_weak_import_pressure: f32,
    pub recursive_runtime_items: usize,
    pub recursive_runtime_calls: usize,
    pub average_recursive_call_pressure: f32,
    pub max_recursive_call_pressure: f32,
}

impl From<Option<&ExperienceReplayReport>> for AutoReplayTraceFields {
    fn from(report: Option<&ExperienceReplayReport>) -> Self {
        let Some(report) = report else {
            return Self::default();
        };

        Self {
            applied: report.applied,
            router_updates: report.router_updates,
            hierarchy_updates: report.hierarchy_updates,
            router_threshold_mutations: report.router_threshold_mutations,
            hierarchy_weight_mutations: report.hierarchy_weight_mutations,
            router_threshold_delta: report.router_threshold_delta,
            hierarchy_weight_delta: report.hierarchy_weight_delta,
            reinforced: report.reinforced,
            penalized: report.penalized,
            touched_memories: report.touched_memories,
            memory_reinforcements: report.memory_reinforcements,
            memory_penalties: report.memory_penalties,
            live_memory_feedback_items: report.live_memory_feedback_items,
            live_memory_feedback_updates: report.live_memory_feedback_updates,
            live_memory_feedback_reinforcements: report.live_memory_feedback_reinforcements,
            live_memory_feedback_penalties: report.live_memory_feedback_penalties,
            live_memory_feedback_detail_items: report.live_memory_feedback_detail_items,
            live_memory_feedback_applied: report.live_memory_feedback_applied,
            live_memory_feedback_removed: report.live_memory_feedback_removed,
            live_memory_feedback_missing: report.live_memory_feedback_missing,
            live_memory_feedback_strength_delta: report.live_memory_feedback_strength_delta,
            business_contract_items: report.business_contract_items,
            business_contract_passed: report.business_contract_passed,
            business_contract_failed: report.business_contract_failed,
            business_contract_raw_passed: report.business_contract_raw_passed,
            business_contract_raw_failed: report.business_contract_raw_failed,
            business_contract_response_normalized: report.business_contract_response_normalized,
            business_contract_sanitized: report.business_contract_sanitized,
            business_contract_canonical_fallbacks: report.business_contract_canonical_fallbacks,
            live_evolution_items: report.live_evolution_items,
            live_evolution_router_threshold_mutations: report
                .live_evolution_router_threshold_mutations,
            live_evolution_hierarchy_weight_mutations: report
                .live_evolution_hierarchy_weight_mutations,
            live_evolution_router_threshold_delta: report.live_evolution_router_threshold_delta,
            live_evolution_hierarchy_weight_delta: report.live_evolution_hierarchy_weight_delta,
            live_evolution_online_reward_feedbacks: report.live_evolution_online_reward_feedbacks,
            live_evolution_online_reward_reinforcements: report
                .live_evolution_online_reward_reinforcements,
            live_evolution_online_reward_penalties: report.live_evolution_online_reward_penalties,
            live_evolution_online_reward_strength: report.live_evolution_online_reward_strength,
            live_evolution_online_reward_reinforcement_strength: report
                .live_evolution_online_reward_reinforcement_strength,
            live_evolution_online_reward_penalty_strength: report
                .live_evolution_online_reward_penalty_strength,
            live_evolution_memory_updates: report.live_evolution_memory_updates,
            live_evolution_stored_memory_updates: report.live_evolution_stored_memory_updates,
            live_evolution_reflection_issues: report.live_evolution_reflection_issues,
            live_evolution_critical_reflection_issues: report
                .live_evolution_critical_reflection_issues,
            live_evolution_revision_actions: report.live_evolution_revision_actions,
            runtime_kv_budget_pressure_items: report.runtime_kv_budget_pressure_items,
            average_runtime_kv_budget_pressure: report.average_runtime_kv_budget_pressure,
            max_runtime_kv_budget_pressure: report.max_runtime_kv_budget_pressure,
            runtime_kv_weak_import_pressure_items: report.runtime_kv_weak_import_pressure_items,
            average_runtime_kv_weak_import_pressure: report.average_runtime_kv_weak_import_pressure,
            max_runtime_kv_weak_import_pressure: report.max_runtime_kv_weak_import_pressure,
            recursive_runtime_items: report.recursive_runtime_items,
            recursive_runtime_calls: report.recursive_runtime_calls,
            average_recursive_call_pressure: report.average_recursive_call_pressure,
            max_recursive_call_pressure: report.max_recursive_call_pressure,
        }
    }
}
